// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRLDPCDecoderHDL\dec_CodeParameters.v
// Created: 2026-06-03 20:19:59
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec_CodeParameters
// Source Path: NRLDPCDecoderHDL/HDL Algorithm/NR LDPC Decoder/CodeParameters
// Hierarchy Level: 2
// Model version: 10.1
// 
// Code Parameters
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec_CodeParameters
          (clk,
           reset,
           enb,
           dataIn_0,
           dataIn_1,
           dataIn_2,
           dataIn_3,
           dataIn_4,
           dataIn_5,
           dataIn_6,
           dataIn_7,
           dataIn_8,
           dataIn_9,
           dataIn_10,
           dataIn_11,
           dataIn_12,
           dataIn_13,
           dataIn_14,
           dataIn_15,
           dataIn_16,
           dataIn_17,
           dataIn_18,
           dataIn_19,
           dataIn_20,
           dataIn_21,
           dataIn_22,
           dataIn_23,
           dataIn_24,
           dataIn_25,
           dataIn_26,
           dataIn_27,
           dataIn_28,
           dataIn_29,
           dataIn_30,
           dataIn_31,
           dataIn_32,
           dataIn_33,
           dataIn_34,
           dataIn_35,
           dataIn_36,
           dataIn_37,
           dataIn_38,
           dataIn_39,
           dataIn_40,
           dataIn_41,
           dataIn_42,
           dataIn_43,
           dataIn_44,
           dataIn_45,
           dataIn_46,
           dataIn_47,
           dataIn_48,
           dataIn_49,
           dataIn_50,
           dataIn_51,
           dataIn_52,
           dataIn_53,
           dataIn_54,
           dataIn_55,
           dataIn_56,
           dataIn_57,
           dataIn_58,
           dataIn_59,
           dataIn_60,
           dataIn_61,
           dataIn_62,
           dataIn_63,
           startIn,
           endIn,
           validIn,
           bgn,
           liftsize,
           niter,
           dataOut_0,
           dataOut_1,
           dataOut_2,
           dataOut_3,
           dataOut_4,
           dataOut_5,
           dataOut_6,
           dataOut_7,
           dataOut_8,
           dataOut_9,
           dataOut_10,
           dataOut_11,
           dataOut_12,
           dataOut_13,
           dataOut_14,
           dataOut_15,
           dataOut_16,
           dataOut_17,
           dataOut_18,
           dataOut_19,
           dataOut_20,
           dataOut_21,
           dataOut_22,
           dataOut_23,
           dataOut_24,
           dataOut_25,
           dataOut_26,
           dataOut_27,
           dataOut_28,
           dataOut_29,
           dataOut_30,
           dataOut_31,
           dataOut_32,
           dataOut_33,
           dataOut_34,
           dataOut_35,
           dataOut_36,
           dataOut_37,
           dataOut_38,
           dataOut_39,
           dataOut_40,
           dataOut_41,
           dataOut_42,
           dataOut_43,
           dataOut_44,
           dataOut_45,
           dataOut_46,
           dataOut_47,
           dataOut_48,
           dataOut_49,
           dataOut_50,
           dataOut_51,
           dataOut_52,
           dataOut_53,
           dataOut_54,
           dataOut_55,
           dataOut_56,
           dataOut_57,
           dataOut_58,
           dataOut_59,
           dataOut_60,
           dataOut_61,
           dataOut_62,
           dataOut_63,
           validOut,
           frameValid,
           reset_1,
           bgn_1,
           iLS,
           liftsize_1,
           endInd,
           niter_1,
           zAddr,
           rstNextFrame,
           nRowOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [3:0] dataIn_0;  // sfix4
  input   signed [3:0] dataIn_1;  // sfix4
  input   signed [3:0] dataIn_2;  // sfix4
  input   signed [3:0] dataIn_3;  // sfix4
  input   signed [3:0] dataIn_4;  // sfix4
  input   signed [3:0] dataIn_5;  // sfix4
  input   signed [3:0] dataIn_6;  // sfix4
  input   signed [3:0] dataIn_7;  // sfix4
  input   signed [3:0] dataIn_8;  // sfix4
  input   signed [3:0] dataIn_9;  // sfix4
  input   signed [3:0] dataIn_10;  // sfix4
  input   signed [3:0] dataIn_11;  // sfix4
  input   signed [3:0] dataIn_12;  // sfix4
  input   signed [3:0] dataIn_13;  // sfix4
  input   signed [3:0] dataIn_14;  // sfix4
  input   signed [3:0] dataIn_15;  // sfix4
  input   signed [3:0] dataIn_16;  // sfix4
  input   signed [3:0] dataIn_17;  // sfix4
  input   signed [3:0] dataIn_18;  // sfix4
  input   signed [3:0] dataIn_19;  // sfix4
  input   signed [3:0] dataIn_20;  // sfix4
  input   signed [3:0] dataIn_21;  // sfix4
  input   signed [3:0] dataIn_22;  // sfix4
  input   signed [3:0] dataIn_23;  // sfix4
  input   signed [3:0] dataIn_24;  // sfix4
  input   signed [3:0] dataIn_25;  // sfix4
  input   signed [3:0] dataIn_26;  // sfix4
  input   signed [3:0] dataIn_27;  // sfix4
  input   signed [3:0] dataIn_28;  // sfix4
  input   signed [3:0] dataIn_29;  // sfix4
  input   signed [3:0] dataIn_30;  // sfix4
  input   signed [3:0] dataIn_31;  // sfix4
  input   signed [3:0] dataIn_32;  // sfix4
  input   signed [3:0] dataIn_33;  // sfix4
  input   signed [3:0] dataIn_34;  // sfix4
  input   signed [3:0] dataIn_35;  // sfix4
  input   signed [3:0] dataIn_36;  // sfix4
  input   signed [3:0] dataIn_37;  // sfix4
  input   signed [3:0] dataIn_38;  // sfix4
  input   signed [3:0] dataIn_39;  // sfix4
  input   signed [3:0] dataIn_40;  // sfix4
  input   signed [3:0] dataIn_41;  // sfix4
  input   signed [3:0] dataIn_42;  // sfix4
  input   signed [3:0] dataIn_43;  // sfix4
  input   signed [3:0] dataIn_44;  // sfix4
  input   signed [3:0] dataIn_45;  // sfix4
  input   signed [3:0] dataIn_46;  // sfix4
  input   signed [3:0] dataIn_47;  // sfix4
  input   signed [3:0] dataIn_48;  // sfix4
  input   signed [3:0] dataIn_49;  // sfix4
  input   signed [3:0] dataIn_50;  // sfix4
  input   signed [3:0] dataIn_51;  // sfix4
  input   signed [3:0] dataIn_52;  // sfix4
  input   signed [3:0] dataIn_53;  // sfix4
  input   signed [3:0] dataIn_54;  // sfix4
  input   signed [3:0] dataIn_55;  // sfix4
  input   signed [3:0] dataIn_56;  // sfix4
  input   signed [3:0] dataIn_57;  // sfix4
  input   signed [3:0] dataIn_58;  // sfix4
  input   signed [3:0] dataIn_59;  // sfix4
  input   signed [3:0] dataIn_60;  // sfix4
  input   signed [3:0] dataIn_61;  // sfix4
  input   signed [3:0] dataIn_62;  // sfix4
  input   signed [3:0] dataIn_63;  // sfix4
  input   startIn;  // ufix1
  input   endIn;  // ufix1
  input   validIn;  // ufix1
  input   bgn;  // ufix1
  input   [8:0] liftsize;  // ufix9
  input   [7:0] niter;  // ufix8
  output  signed [3:0] dataOut_0;  // sfix4
  output  signed [3:0] dataOut_1;  // sfix4
  output  signed [3:0] dataOut_2;  // sfix4
  output  signed [3:0] dataOut_3;  // sfix4
  output  signed [3:0] dataOut_4;  // sfix4
  output  signed [3:0] dataOut_5;  // sfix4
  output  signed [3:0] dataOut_6;  // sfix4
  output  signed [3:0] dataOut_7;  // sfix4
  output  signed [3:0] dataOut_8;  // sfix4
  output  signed [3:0] dataOut_9;  // sfix4
  output  signed [3:0] dataOut_10;  // sfix4
  output  signed [3:0] dataOut_11;  // sfix4
  output  signed [3:0] dataOut_12;  // sfix4
  output  signed [3:0] dataOut_13;  // sfix4
  output  signed [3:0] dataOut_14;  // sfix4
  output  signed [3:0] dataOut_15;  // sfix4
  output  signed [3:0] dataOut_16;  // sfix4
  output  signed [3:0] dataOut_17;  // sfix4
  output  signed [3:0] dataOut_18;  // sfix4
  output  signed [3:0] dataOut_19;  // sfix4
  output  signed [3:0] dataOut_20;  // sfix4
  output  signed [3:0] dataOut_21;  // sfix4
  output  signed [3:0] dataOut_22;  // sfix4
  output  signed [3:0] dataOut_23;  // sfix4
  output  signed [3:0] dataOut_24;  // sfix4
  output  signed [3:0] dataOut_25;  // sfix4
  output  signed [3:0] dataOut_26;  // sfix4
  output  signed [3:0] dataOut_27;  // sfix4
  output  signed [3:0] dataOut_28;  // sfix4
  output  signed [3:0] dataOut_29;  // sfix4
  output  signed [3:0] dataOut_30;  // sfix4
  output  signed [3:0] dataOut_31;  // sfix4
  output  signed [3:0] dataOut_32;  // sfix4
  output  signed [3:0] dataOut_33;  // sfix4
  output  signed [3:0] dataOut_34;  // sfix4
  output  signed [3:0] dataOut_35;  // sfix4
  output  signed [3:0] dataOut_36;  // sfix4
  output  signed [3:0] dataOut_37;  // sfix4
  output  signed [3:0] dataOut_38;  // sfix4
  output  signed [3:0] dataOut_39;  // sfix4
  output  signed [3:0] dataOut_40;  // sfix4
  output  signed [3:0] dataOut_41;  // sfix4
  output  signed [3:0] dataOut_42;  // sfix4
  output  signed [3:0] dataOut_43;  // sfix4
  output  signed [3:0] dataOut_44;  // sfix4
  output  signed [3:0] dataOut_45;  // sfix4
  output  signed [3:0] dataOut_46;  // sfix4
  output  signed [3:0] dataOut_47;  // sfix4
  output  signed [3:0] dataOut_48;  // sfix4
  output  signed [3:0] dataOut_49;  // sfix4
  output  signed [3:0] dataOut_50;  // sfix4
  output  signed [3:0] dataOut_51;  // sfix4
  output  signed [3:0] dataOut_52;  // sfix4
  output  signed [3:0] dataOut_53;  // sfix4
  output  signed [3:0] dataOut_54;  // sfix4
  output  signed [3:0] dataOut_55;  // sfix4
  output  signed [3:0] dataOut_56;  // sfix4
  output  signed [3:0] dataOut_57;  // sfix4
  output  signed [3:0] dataOut_58;  // sfix4
  output  signed [3:0] dataOut_59;  // sfix4
  output  signed [3:0] dataOut_60;  // sfix4
  output  signed [3:0] dataOut_61;  // sfix4
  output  signed [3:0] dataOut_62;  // sfix4
  output  signed [3:0] dataOut_63;  // sfix4
  output  validOut;  // ufix1
  output  frameValid;  // ufix1
  output  reset_1;  // ufix1
  output  bgn_1;  // ufix1
  output  [2:0] iLS;  // ufix3
  output  [8:0] liftsize_1;  // ufix9
  output  endInd;  // ufix1
  output  [7:0] niter_1;  // ufix8
  output  [2:0] zAddr;  // ufix3
  output  rstNextFrame;  // ufix1
  output  [5:0] nRowOut;  // ufix6


  wire startValid;  // ufix1
  wire newCountMax;  // ufix1
  wire rstCount;  // ufix1
  wire newFrame;  // ufix1
  reg [2:0] newCount;  // ufix3
  reg  newFrame_switch_delay;  // ufix1
  reg  newFrameReg;  // ufix1
  wire signed [3:0] dataIn [0:63];  // sfix4 [64]
  reg signed [3:0] data_reg [0:511];  // sfix4 [512]
  reg signed [3:0] data_reg_next [0:511];  // sfix4 [512]
  reg signed [3:0] dataReg [0:63];  // sfix4 [64]
  wire signed [3:0] zData [0:63];  // sfix4 [64]
  reg signed [3:0] dataOutReg [0:63];  // sfix4 [64]
  reg signed [3:0] dataOut_64 [0:63];  // sfix4 [64]
  reg  [7:0] valid_reg;  // ufix1 [8]
  wire validReg;  // ufix1
  wire const0;  // ufix1
  wire validOutReg;  // ufix1
  reg  validOut_2;  // ufix1
  reg  [7:0] start_reg;  // ufix1 [8]
  wire startReg;  // ufix1
  wire startValidReg;  // ufix1
  wire const1;  // ufix1
  reg  const1_1;  // ufix1
  reg  [7:0] end_rsvd_reg;  // ufix1 [8]
  wire endReg;  // ufix1
  wire endValidReg;  // ufix1
  reg  endValidRegD;  // ufix1
  wire startValidNeg;  // ufix1
  wire rstFrame;  // ufix1
  reg  frame_switch_delay;  // ufix1
  wire frameD;  // ufix1
  wire frame_1;  // ufix1
  wire fValidReg;  // ufix1
  reg  frameValid_1;  // ufix1
  reg  resetReg;  // ufix1
  reg  reset_4;  // ufix1
  reg  bgn_2;  // ufix1
  reg [8:0] ZIn;  // ufix9
  reg [2:0] calculateSetIndex_setIndex;  // ufix3
  reg [2:0] calculateSetIndex_count;  // ufix3
  reg  calculateSetIndex_valid_Z;
  reg  calculateSetIndex_enb;
  reg [8:0] calculateSetIndex_set1;  // ufix9
  reg [8:0] calculateSetIndex_set2;  // ufix9
  reg [8:0] calculateSetIndex_set3;  // ufix9
  reg [8:0] calculateSetIndex_set4;  // ufix9
  reg [8:0] calculateSetIndex_set5;  // ufix9
  reg [8:0] calculateSetIndex_set6;  // ufix9
  reg [8:0] calculateSetIndex_set7;  // ufix9
  reg [8:0] calculateSetIndex_set8;  // ufix9
  wire [2:0] calculateSetIndex_setIndex_next;  // ufix3
  wire [2:0] calculateSetIndex_count_next;  // ufix3
  wire calculateSetIndex_valid_Z_next;
  wire calculateSetIndex_enb_next;
  wire [8:0] calculateSetIndex_set1_next;  // ufix9
  wire [8:0] calculateSetIndex_set2_next;  // ufix9
  wire [8:0] calculateSetIndex_set3_next;  // ufix9
  wire [8:0] calculateSetIndex_set4_next;  // ufix9
  wire [8:0] calculateSetIndex_set5_next;  // ufix9
  wire [8:0] calculateSetIndex_set6_next;  // ufix9
  wire [8:0] calculateSetIndex_set7_next;  // ufix9
  wire [8:0] calculateSetIndex_set8_next;  // ufix9
  wire calculateSetIndex_valid_Z_temp;
  wire calculateSetIndex_enb_temp;
  wire validZ;  // ufix1
  wire [2:0] zCount;  // ufix3
  reg  zEnb;  // ufix1
  wire cntEnb;  // ufix1
  reg [2:0] counter_1;  // ufix3
  wire z_tmp1;  // ufix1
  wire rel_z;  // ufix1
  reg  startValidReg1;  // ufix1
  wire z_tmp2;  // ufix1
  wire invalidZ;  // ufix1
  reg [8:0] ZOut_switch_delay;  // ufix9
  wire [8:0] liftsize_2;  // ufix9
  reg  endReg_1;  // ufix1
  wire endIndNeg;  // ufix1
  wire endIndReg;  // ufix1
  reg  endInd_2;  // ufix1
  wire rangeIter;  // ufix1
  wire [7:0] const8;  // ufix8
  wire [7:0] iterAct;  // ufix8
  reg [7:0] niter_2;  // ufix8
  wire [5:0] nRowTmp;  // ufix6
  wire rowGreat46;  // ufix1
  wire rowGreat42;  // ufix1
  wire rowGreat;  // ufix1
  wire rowLess4;  // ufix1
  wire invalidRow;  // ufix1
  wire invalidFrame;  // ufix1
  wire sofVldD;  // ufix1
  reg  reset_next_frame_switch_delay;  // ufix1
  wire [5:0] const46;  // ufix6
  wire [5:0] const42;  // ufix6
  reg signed [31:0] data_t_0_0;  // int32
  reg signed [31:0] data_t_1;  // int32
  reg signed [31:0] data_t_0_1;  // int32
  reg signed [31:0] data_t_1_0;  // int32
  reg signed [31:0] data_sel_t_0_0;  // int32
  reg signed [31:0] data_sel_t_1;  // int32
  reg signed [31:0] dataOut_t_0_0;  // int32
  reg signed [31:0] dataOut_t_1;  // int32


  assign startValid = startIn & validIn;

  assign rstCount = startValid | newCountMax;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 6
  // newCount counter
  always @(posedge clk or negedge reset)
    begin : new_Count_process
      if (reset == 1'b0) begin
        newCount <= 3'b000;
      end
      else begin
        if (enb) begin
          if (rstCount == 1'b1) begin
            newCount <= 3'b000;
          end
          else if (newFrame == 1'b1) begin
            if (newCount >= 3'b110) begin
              newCount <= 3'b000;
            end
            else begin
              newCount <= newCount + 3'b001;
            end
          end
        end
      end
    end

  // newCount comparison with value 6
  assign newCountMax = newCount == 3'b110;

  // newFrame register
  always @(posedge clk or negedge reset)
    begin : newFrame_1_process
      if (reset == 1'b0) begin
        newFrame_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (newCountMax == 1'b1) begin
            newFrame_switch_delay <= 1'b0;
          end
          else begin
            if (startValid) begin
              newFrame_switch_delay <= startValid;
            end
          end
        end
      end
    end

  assign newFrame = (newCountMax == 1'b1 ? 1'b0 :
              newFrame_switch_delay);

  always @(posedge clk or negedge reset)
    begin : newFrame_2_process
      if (reset == 1'b0) begin
        newFrameReg <= 1'b0;
      end
      else begin
        if (enb) begin
          newFrameReg <= newFrame;
        end
      end
    end

  assign dataIn[0] = dataIn_0;
  assign dataIn[1] = dataIn_1;
  assign dataIn[2] = dataIn_2;
  assign dataIn[3] = dataIn_3;
  assign dataIn[4] = dataIn_4;
  assign dataIn[5] = dataIn_5;
  assign dataIn[6] = dataIn_6;
  assign dataIn[7] = dataIn_7;
  assign dataIn[8] = dataIn_8;
  assign dataIn[9] = dataIn_9;
  assign dataIn[10] = dataIn_10;
  assign dataIn[11] = dataIn_11;
  assign dataIn[12] = dataIn_12;
  assign dataIn[13] = dataIn_13;
  assign dataIn[14] = dataIn_14;
  assign dataIn[15] = dataIn_15;
  assign dataIn[16] = dataIn_16;
  assign dataIn[17] = dataIn_17;
  assign dataIn[18] = dataIn_18;
  assign dataIn[19] = dataIn_19;
  assign dataIn[20] = dataIn_20;
  assign dataIn[21] = dataIn_21;
  assign dataIn[22] = dataIn_22;
  assign dataIn[23] = dataIn_23;
  assign dataIn[24] = dataIn_24;
  assign dataIn[25] = dataIn_25;
  assign dataIn[26] = dataIn_26;
  assign dataIn[27] = dataIn_27;
  assign dataIn[28] = dataIn_28;
  assign dataIn[29] = dataIn_29;
  assign dataIn[30] = dataIn_30;
  assign dataIn[31] = dataIn_31;
  assign dataIn[32] = dataIn_32;
  assign dataIn[33] = dataIn_33;
  assign dataIn[34] = dataIn_34;
  assign dataIn[35] = dataIn_35;
  assign dataIn[36] = dataIn_36;
  assign dataIn[37] = dataIn_37;
  assign dataIn[38] = dataIn_38;
  assign dataIn[39] = dataIn_39;
  assign dataIn[40] = dataIn_40;
  assign dataIn[41] = dataIn_41;
  assign dataIn[42] = dataIn_42;
  assign dataIn[43] = dataIn_43;
  assign dataIn[44] = dataIn_44;
  assign dataIn[45] = dataIn_45;
  assign dataIn[46] = dataIn_46;
  assign dataIn[47] = dataIn_47;
  assign dataIn[48] = dataIn_48;
  assign dataIn[49] = dataIn_49;
  assign dataIn[50] = dataIn_50;
  assign dataIn[51] = dataIn_51;
  assign dataIn[52] = dataIn_52;
  assign dataIn[53] = dataIn_53;
  assign dataIn[54] = dataIn_54;
  assign dataIn[55] = dataIn_55;
  assign dataIn[56] = dataIn_56;
  assign dataIn[57] = dataIn_57;
  assign dataIn[58] = dataIn_58;
  assign dataIn[59] = dataIn_59;
  assign dataIn[60] = dataIn_60;
  assign dataIn[61] = dataIn_61;
  assign dataIn[62] = dataIn_62;
  assign dataIn[63] = dataIn_63;

  // data register
  always @(posedge clk or negedge reset)
    begin : data_process
      if (reset == 1'b0) begin
        for(data_t_1_0 = 32'sd0; data_t_1_0 <= 32'sd511; data_t_1_0 = data_t_1_0 + 32'sd1) begin
          data_reg[data_t_1_0] <= 4'sb0000;
        end
      end
      else begin
        if (enb) begin
          for(data_t_0_1 = 32'sd0; data_t_0_1 <= 32'sd511; data_t_0_1 = data_t_0_1 + 32'sd1) begin
            data_reg[data_t_0_1] <= data_reg_next[data_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(data_t_0_0 = 32'sd0; data_t_0_0 <= 32'sd63; data_t_0_0 = data_t_0_0 + 32'sd1) begin
      dataReg[data_t_0_0] = data_reg[32'sd448 + data_t_0_0];
      data_reg_next[data_t_0_0] = dataIn[data_t_0_0];
    end
    for(data_t_1 = 32'sd0; data_t_1 <= 32'sd447; data_t_1 = data_t_1 + 32'sd1) begin
      data_reg_next[data_t_1 + 32'sd64] = data_reg[data_t_1];
    end

  end


  genvar ii1;
  generate
    for(ii1 = 32'sd0; ii1 <= 32'sd63; ii1 = ii1 + 32'sd1) begin:zData_gen
      assign zData[ii1] = 4'sb0000;
    end
  endgenerate

  // data selection comp
  always @* begin
    if (newFrameReg == 1'b0) begin
      for(data_sel_t_1 = 32'sd0; data_sel_t_1 <= 32'sd63; data_sel_t_1 = data_sel_t_1 + 32'sd1) begin
        dataOutReg[data_sel_t_1] = dataReg[data_sel_t_1];
      end
    end
    else begin
      for(data_sel_t_0_0 = 32'sd0; data_sel_t_0_0 <= 32'sd63; data_sel_t_0_0 = data_sel_t_0_0 + 32'sd1) begin
        dataOutReg[data_sel_t_0_0] = zData[data_sel_t_0_0];
      end
    end
  end

  always @(posedge clk or negedge reset)
    begin : dataOut_process
      if (reset == 1'b0) begin
        for(dataOut_t_1 = 32'sd0; dataOut_t_1 <= 32'sd63; dataOut_t_1 = dataOut_t_1 + 32'sd1) begin
          dataOut_64[dataOut_t_1] <= 4'sb0000;
        end
      end
      else begin
        if (enb) begin
          for(dataOut_t_0_0 = 32'sd0; dataOut_t_0_0 <= 32'sd63; dataOut_t_0_0 = dataOut_t_0_0 + 32'sd1) begin
            dataOut_64[dataOut_t_0_0] <= dataOutReg[dataOut_t_0_0];
          end
        end
      end
    end

  assign dataOut_0 = dataOut_64[0];

  assign dataOut_1 = dataOut_64[1];

  assign dataOut_2 = dataOut_64[2];

  assign dataOut_3 = dataOut_64[3];

  assign dataOut_4 = dataOut_64[4];

  assign dataOut_5 = dataOut_64[5];

  assign dataOut_6 = dataOut_64[6];

  assign dataOut_7 = dataOut_64[7];

  assign dataOut_8 = dataOut_64[8];

  assign dataOut_9 = dataOut_64[9];

  assign dataOut_10 = dataOut_64[10];

  assign dataOut_11 = dataOut_64[11];

  assign dataOut_12 = dataOut_64[12];

  assign dataOut_13 = dataOut_64[13];

  assign dataOut_14 = dataOut_64[14];

  assign dataOut_15 = dataOut_64[15];

  assign dataOut_16 = dataOut_64[16];

  assign dataOut_17 = dataOut_64[17];

  assign dataOut_18 = dataOut_64[18];

  assign dataOut_19 = dataOut_64[19];

  assign dataOut_20 = dataOut_64[20];

  assign dataOut_21 = dataOut_64[21];

  assign dataOut_22 = dataOut_64[22];

  assign dataOut_23 = dataOut_64[23];

  assign dataOut_24 = dataOut_64[24];

  assign dataOut_25 = dataOut_64[25];

  assign dataOut_26 = dataOut_64[26];

  assign dataOut_27 = dataOut_64[27];

  assign dataOut_28 = dataOut_64[28];

  assign dataOut_29 = dataOut_64[29];

  assign dataOut_30 = dataOut_64[30];

  assign dataOut_31 = dataOut_64[31];

  assign dataOut_32 = dataOut_64[32];

  assign dataOut_33 = dataOut_64[33];

  assign dataOut_34 = dataOut_64[34];

  assign dataOut_35 = dataOut_64[35];

  assign dataOut_36 = dataOut_64[36];

  assign dataOut_37 = dataOut_64[37];

  assign dataOut_38 = dataOut_64[38];

  assign dataOut_39 = dataOut_64[39];

  assign dataOut_40 = dataOut_64[40];

  assign dataOut_41 = dataOut_64[41];

  assign dataOut_42 = dataOut_64[42];

  assign dataOut_43 = dataOut_64[43];

  assign dataOut_44 = dataOut_64[44];

  assign dataOut_45 = dataOut_64[45];

  assign dataOut_46 = dataOut_64[46];

  assign dataOut_47 = dataOut_64[47];

  assign dataOut_48 = dataOut_64[48];

  assign dataOut_49 = dataOut_64[49];

  assign dataOut_50 = dataOut_64[50];

  assign dataOut_51 = dataOut_64[51];

  assign dataOut_52 = dataOut_64[52];

  assign dataOut_53 = dataOut_64[53];

  assign dataOut_54 = dataOut_64[54];

  assign dataOut_55 = dataOut_64[55];

  assign dataOut_56 = dataOut_64[56];

  assign dataOut_57 = dataOut_64[57];

  assign dataOut_58 = dataOut_64[58];

  assign dataOut_59 = dataOut_64[59];

  assign dataOut_60 = dataOut_64[60];

  assign dataOut_61 = dataOut_64[61];

  assign dataOut_62 = dataOut_64[62];

  assign dataOut_63 = dataOut_64[63];

  // valid register
  always @(posedge clk or negedge reset)
    begin : valid_process
      if (reset == 1'b0) begin
        valid_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          valid_reg[0] <= validIn;
          valid_reg[32'sd7:32'sd1] <= valid_reg[32'sd6:32'sd0];
        end
      end
    end

  assign validReg = valid_reg[7];

  assign const0 = 1'b0;

  // valid selection comp
  assign validOutReg = (newFrameReg == 1'b0 ? validReg :
              const0);

  always @(posedge clk or negedge reset)
    begin : validOut_1_process
      if (reset == 1'b0) begin
        validOut_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          validOut_2 <= validOutReg;
        end
      end
    end

  // start register
  always @(posedge clk or negedge reset)
    begin : start_process
      if (reset == 1'b0) begin
        start_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          start_reg[0] <= startIn;
          start_reg[32'sd7:32'sd1] <= start_reg[32'sd6:32'sd0];
        end
      end
    end

  assign startReg = start_reg[7];

  assign startValidReg = startReg & validReg;

  assign const1 = 1'b1;

  always @(posedge clk or negedge reset)
    begin : c_process
      if (reset == 1'b0) begin
        const1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          const1_1 <= const1;
        end
      end
    end

  // end register
  always @(posedge clk or negedge reset)
    begin : end_rsvd_process
      if (reset == 1'b0) begin
        end_rsvd_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          if (startValid == 1'b1) begin
            end_rsvd_reg <= {8{1'b0}};
          end
          else begin
            if (const1_1) begin
              end_rsvd_reg[0] <= endIn;
              end_rsvd_reg[32'sd7:32'sd1] <= end_rsvd_reg[32'sd6:32'sd0];
            end
          end
        end
      end
    end

  assign endReg = end_rsvd_reg[7];

  assign endValidReg = endReg & validReg;

  always @(posedge clk or negedge reset)
    begin : end_valid_process
      if (reset == 1'b0) begin
        endValidRegD <= 1'b0;
      end
      else begin
        if (enb) begin
          endValidRegD <= endValidReg;
        end
      end
    end

  assign startValidNeg =  ~ startValidReg;

  assign rstFrame = endValidRegD & startValidNeg;

  // frame register
  always @(posedge clk or negedge reset)
    begin : frame_process
      if (reset == 1'b0) begin
        frame_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (rstFrame == 1'b1) begin
            frame_switch_delay <= 1'b0;
          end
          else begin
            if (startValidReg) begin
              frame_switch_delay <= startValidReg;
            end
          end
        end
      end
    end

  assign frameD = (rstFrame == 1'b1 ? 1'b0 :
              frame_switch_delay);

  assign frame_1 = frameD | startValidReg;

  // framevalid selection comp
  assign fValidReg = (newFrameReg == 1'b0 ? frame_1 :
              const0);

  always @(posedge clk or negedge reset)
    begin : fValidOut_process
      if (reset == 1'b0) begin
        frameValid_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          frameValid_1 <= fValidReg;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : reset_2_process
      if (reset == 1'b0) begin
        resetReg <= 1'b0;
      end
      else begin
        if (enb) begin
          resetReg <= startValid;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : reset_3_process
      if (reset == 1'b0) begin
        reset_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          reset_4 <= resetReg;
        end
      end
    end

  // bgn Sampling
  always @(posedge clk or negedge reset)
    begin : bgn_sampling_process
      if (reset == 1'b0) begin
        bgn_2 <= 1'b0;
      end
      else begin
        if (enb && startValid) begin
          bgn_2 <= bgn;
        end
      end
    end

  // liftingSize Sampling
  always @(posedge clk or negedge reset)
    begin : Z_sampling_process
      if (reset == 1'b0) begin
        ZIn <= 9'b000000010;
      end
      else begin
        if (enb && startValid) begin
          ZIn <= liftsize;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : calculateSetIndex_process
      if (reset == 1'b0) begin
        calculateSetIndex_setIndex <= 3'b000;
        calculateSetIndex_count <= 3'b000;
        calculateSetIndex_valid_Z <= 1'b0;
        calculateSetIndex_enb <= 1'b0;
        calculateSetIndex_set1 <= 9'b000000010;
        calculateSetIndex_set2 <= 9'b000000011;
        calculateSetIndex_set3 <= 9'b000000101;
        calculateSetIndex_set4 <= 9'b000000111;
        calculateSetIndex_set5 <= 9'b000001001;
        calculateSetIndex_set6 <= 9'b000001011;
        calculateSetIndex_set7 <= 9'b000001101;
        calculateSetIndex_set8 <= 9'b000001111;
      end
      else begin
        if (enb) begin
          calculateSetIndex_setIndex <= calculateSetIndex_setIndex_next;
          calculateSetIndex_count <= calculateSetIndex_count_next;
          calculateSetIndex_valid_Z <= calculateSetIndex_valid_Z_next;
          calculateSetIndex_enb <= calculateSetIndex_enb_next;
          calculateSetIndex_set1 <= calculateSetIndex_set1_next;
          calculateSetIndex_set2 <= calculateSetIndex_set2_next;
          calculateSetIndex_set3 <= calculateSetIndex_set3_next;
          calculateSetIndex_set4 <= calculateSetIndex_set4_next;
          calculateSetIndex_set5 <= calculateSetIndex_set5_next;
          calculateSetIndex_set6 <= calculateSetIndex_set6_next;
          calculateSetIndex_set7 <= calculateSetIndex_set7_next;
          calculateSetIndex_set8 <= calculateSetIndex_set8_next;
        end
      end
    end

  assign calculateSetIndex_setIndex_next = (calculateSetIndex_set1 == ZIn ? 3'b000 :
              (calculateSetIndex_set2 == ZIn ? 3'b001 :
              (calculateSetIndex_set3 == ZIn ? 3'b010 :
              (calculateSetIndex_set4 == ZIn ? 3'b011 :
              (calculateSetIndex_set5 == ZIn ? 3'b100 :
              (calculateSetIndex_set6 == ZIn ? 3'b101 :
              (calculateSetIndex_set7 == ZIn ? 3'b110 :
              (calculateSetIndex_set8 == ZIn ? 3'b111 :
              3'b000))))))));
  assign calculateSetIndex_valid_Z_temp = (calculateSetIndex_set1 == ZIn ? 1'b1 :
              (calculateSetIndex_set2 == ZIn ? 1'b1 :
              (calculateSetIndex_set3 == ZIn ? 1'b1 :
              (calculateSetIndex_set4 == ZIn ? 1'b1 :
              (calculateSetIndex_set5 == ZIn ? 1'b1 :
              (calculateSetIndex_set6 == ZIn ? 1'b1 :
              (calculateSetIndex_set7 == ZIn ? 1'b1 :
              (calculateSetIndex_set8 == ZIn ? 1'b1 :
              1'b0))))))));
  assign calculateSetIndex_enb_temp = (startValid != 1'b0 ? 1'b1 :
              (calculateSetIndex_valid_Z_temp ? 1'b0 :
              calculateSetIndex_enb));
  assign calculateSetIndex_count_next = (startValid != 1'b0 ? 3'b000 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_count + 3'b001 :
              calculateSetIndex_count));
  assign calculateSetIndex_set1_next = (startValid != 1'b0 ? 9'b000000010 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set1 <<< 8'd1 :
              calculateSetIndex_set1));
  assign calculateSetIndex_set2_next = (startValid != 1'b0 ? 9'b000000011 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set2 <<< 8'd1 :
              calculateSetIndex_set2));
  assign calculateSetIndex_set3_next = (startValid != 1'b0 ? 9'b000000101 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set3 <<< 8'd1 :
              calculateSetIndex_set3));
  assign calculateSetIndex_set4_next = (startValid != 1'b0 ? 9'b000000111 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set4 <<< 8'd1 :
              calculateSetIndex_set4));
  assign calculateSetIndex_set5_next = (startValid != 1'b0 ? 9'b000001001 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set5 <<< 8'd1 :
              calculateSetIndex_set5));
  assign calculateSetIndex_set6_next = (startValid != 1'b0 ? 9'b000001011 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set6 <<< 8'd1 :
              calculateSetIndex_set6));
  assign calculateSetIndex_set7_next = (startValid != 1'b0 ? 9'b000001101 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set7 <<< 8'd1 :
              calculateSetIndex_set7));
  assign calculateSetIndex_set8_next = (startValid != 1'b0 ? 9'b000001111 :
              (calculateSetIndex_enb_temp ? calculateSetIndex_set8 <<< 8'd1 :
              calculateSetIndex_set8));
  assign iLS = calculateSetIndex_setIndex;
  assign validZ = calculateSetIndex_valid_Z;
  assign zCount = calculateSetIndex_count;
  assign calculateSetIndex_valid_Z_next = calculateSetIndex_valid_Z_temp;
  assign calculateSetIndex_enb_next = calculateSetIndex_enb_temp;

  always @(posedge clk or negedge reset)
    begin : c_1_process
      if (reset == 1'b0) begin
        zEnb <= 1'b0;
      end
      else begin
        if (enb) begin
          zEnb <= startValid;
        end
      end
    end

  assign cntEnb = newFrame | newFrameReg;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  always @(posedge clk or negedge reset)
    begin : counter_process
      if (reset == 1'b0) begin
        counter_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          if (startValid == 1'b1) begin
            counter_1 <= 3'b000;
          end
          else if (cntEnb == 1'b1) begin
            counter_1 <= counter_1 + 3'b001;
          end
        end
      end
    end

  assign z_tmp1 = counter_1 == 3'b111;

  // Signal indicating invalid Z
  assign rel_z =  ~ validZ;

  always @(posedge clk or negedge reset)
    begin : c_2_process
      if (reset == 1'b0) begin
        startValidReg1 <= 1'b0;
      end
      else begin
        if (enb) begin
          startValidReg1 <= startValidReg;
        end
      end
    end

  assign z_tmp2 = z_tmp1 & startValidReg1;

  assign invalidZ = rel_z & z_tmp2;

  // liftingSizeOut
  always @(posedge clk or negedge reset)
    begin : ZOut_process
      if (reset == 1'b0) begin
        ZOut_switch_delay <= 9'b000000010;
      end
      else begin
        if (enb) begin
          if (invalidZ == 1'b1) begin
            ZOut_switch_delay <= 9'b000000010;
          end
          else begin
            if (zEnb) begin
              ZOut_switch_delay <= ZIn;
            end
          end
        end
      end
    end

  assign liftsize_2 = (invalidZ == 1'b1 ? 9'b000000010 :
              ZOut_switch_delay);

  assign endIndNeg =  ~ endReg_1;

  assign endIndReg = endIndNeg & endValidReg;

  // endInd signal generation
  always @(posedge clk or negedge reset)
    begin : Frame_valid_process
      if (reset == 1'b0) begin
        endReg_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (startValidReg == 1'b1) begin
            endReg_1 <= 1'b0;
          end
          else begin
            if (endIndReg) begin
              endReg_1 <= endIndReg;
            end
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : endInd_1_process
      if (reset == 1'b0) begin
        endInd_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          endInd_2 <= endReg_1;
        end
      end
    end

  assign rangeIter = niter > 8'b00111111;

  assign const8 = 8'b00001000;

  assign iterAct = (rangeIter == 1'b0 ? niter :
              const8);

  always @(posedge clk or negedge reset)
    begin : c_3_process
      if (reset == 1'b0) begin
        niter_2 <= 8'b00001000;
      end
      else begin
        if (enb && startValid) begin
          niter_2 <= iterAct;
        end
      end
    end

  assign zAddr = zCount;

  assign rowGreat46 = nRowTmp > 6'b101110;

  assign rowGreat42 = nRowTmp > 6'b101010;

  assign rowGreat = (bgn_2 == 1'b0 ? rowGreat46 :
              rowGreat42);

  assign rowLess4 = nRowTmp < 6'b000100;

  assign invalidRow = rowGreat | rowLess4;

  assign invalidFrame = invalidRow | invalidZ;

  assign sofVldD = startReg & validReg;

  // Resetting next frame incase of invalid conditions
  always @(posedge clk or negedge reset)
    begin : reset_next_frame_process
      if (reset == 1'b0) begin
        reset_next_frame_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (sofVldD == 1'b1) begin
            reset_next_frame_switch_delay <= 1'b0;
          end
          else begin
            if (invalidFrame) begin
              reset_next_frame_switch_delay <= invalidZ;
            end
          end
        end
      end
    end

  assign rstNextFrame = (sofVldD == 1'b1 ? 1'b0 :
              reset_next_frame_switch_delay);

  assign const46 = 6'b101110;

  assign const42 = 6'b101010;

  assign nRowOut = (bgn_2 == 1'b0 ? const46 :
              const42);

  assign validOut = validOut_2;

  assign frameValid = frameValid_1;

  assign reset_1 = reset_4;

  assign bgn_1 = bgn_2;

  assign liftsize_1 = liftsize_2;

  assign endInd = endInd_2;

  assign niter_1 = niter_2;

endmodule  // dec_CodeParameters

