// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRLDPCDecoderHDL\dec_NR_LDPC_Decoder.v
// Created: 2026-06-03 20:20:02
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec_NR_LDPC_Decoder
// Source Path: NRLDPCDecoderHDL/HDL Algorithm/NR LDPC Decoder
// Hierarchy Level: 1
// Model version: 10.1
// 
// NR LDPC Decoder
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec_NR_LDPC_Decoder
          (clk,
           reset,
           enb,
           in0_0,
           in0_1,
           in0_2,
           in0_3,
           in0_4,
           in0_5,
           in0_6,
           in0_7,
           in0_8,
           in0_9,
           in0_10,
           in0_11,
           in0_12,
           in0_13,
           in0_14,
           in0_15,
           in0_16,
           in0_17,
           in0_18,
           in0_19,
           in0_20,
           in0_21,
           in0_22,
           in0_23,
           in0_24,
           in0_25,
           in0_26,
           in0_27,
           in0_28,
           in0_29,
           in0_30,
           in0_31,
           in0_32,
           in0_33,
           in0_34,
           in0_35,
           in0_36,
           in0_37,
           in0_38,
           in0_39,
           in0_40,
           in0_41,
           in0_42,
           in0_43,
           in0_44,
           in0_45,
           in0_46,
           in0_47,
           in0_48,
           in0_49,
           in0_50,
           in0_51,
           in0_52,
           in0_53,
           in0_54,
           in0_55,
           in0_56,
           in0_57,
           in0_58,
           in0_59,
           in0_60,
           in0_61,
           in0_62,
           in0_63,
           in1_start,
           in1_end,
           in1_valid,
           in2,
           in3,
           out0_0,
           out0_1,
           out0_2,
           out0_3,
           out0_4,
           out0_5,
           out0_6,
           out0_7,
           out0_8,
           out0_9,
           out0_10,
           out0_11,
           out0_12,
           out0_13,
           out0_14,
           out0_15,
           out0_16,
           out0_17,
           out0_18,
           out0_19,
           out0_20,
           out0_21,
           out0_22,
           out0_23,
           out0_24,
           out0_25,
           out0_26,
           out0_27,
           out0_28,
           out0_29,
           out0_30,
           out0_31,
           out0_32,
           out0_33,
           out0_34,
           out0_35,
           out0_36,
           out0_37,
           out0_38,
           out0_39,
           out0_40,
           out0_41,
           out0_42,
           out0_43,
           out0_44,
           out0_45,
           out0_46,
           out0_47,
           out0_48,
           out0_49,
           out0_50,
           out0_51,
           out0_52,
           out0_53,
           out0_54,
           out0_55,
           out0_56,
           out0_57,
           out0_58,
           out0_59,
           out0_60,
           out0_61,
           out0_62,
           out0_63,
           out1_start,
           out1_end,
           out1_valid,
           out2,
           out3);


  input   clk;
  input   reset;
  input   enb;
  input   signed [3:0] in0_0;  // sfix4
  input   signed [3:0] in0_1;  // sfix4
  input   signed [3:0] in0_2;  // sfix4
  input   signed [3:0] in0_3;  // sfix4
  input   signed [3:0] in0_4;  // sfix4
  input   signed [3:0] in0_5;  // sfix4
  input   signed [3:0] in0_6;  // sfix4
  input   signed [3:0] in0_7;  // sfix4
  input   signed [3:0] in0_8;  // sfix4
  input   signed [3:0] in0_9;  // sfix4
  input   signed [3:0] in0_10;  // sfix4
  input   signed [3:0] in0_11;  // sfix4
  input   signed [3:0] in0_12;  // sfix4
  input   signed [3:0] in0_13;  // sfix4
  input   signed [3:0] in0_14;  // sfix4
  input   signed [3:0] in0_15;  // sfix4
  input   signed [3:0] in0_16;  // sfix4
  input   signed [3:0] in0_17;  // sfix4
  input   signed [3:0] in0_18;  // sfix4
  input   signed [3:0] in0_19;  // sfix4
  input   signed [3:0] in0_20;  // sfix4
  input   signed [3:0] in0_21;  // sfix4
  input   signed [3:0] in0_22;  // sfix4
  input   signed [3:0] in0_23;  // sfix4
  input   signed [3:0] in0_24;  // sfix4
  input   signed [3:0] in0_25;  // sfix4
  input   signed [3:0] in0_26;  // sfix4
  input   signed [3:0] in0_27;  // sfix4
  input   signed [3:0] in0_28;  // sfix4
  input   signed [3:0] in0_29;  // sfix4
  input   signed [3:0] in0_30;  // sfix4
  input   signed [3:0] in0_31;  // sfix4
  input   signed [3:0] in0_32;  // sfix4
  input   signed [3:0] in0_33;  // sfix4
  input   signed [3:0] in0_34;  // sfix4
  input   signed [3:0] in0_35;  // sfix4
  input   signed [3:0] in0_36;  // sfix4
  input   signed [3:0] in0_37;  // sfix4
  input   signed [3:0] in0_38;  // sfix4
  input   signed [3:0] in0_39;  // sfix4
  input   signed [3:0] in0_40;  // sfix4
  input   signed [3:0] in0_41;  // sfix4
  input   signed [3:0] in0_42;  // sfix4
  input   signed [3:0] in0_43;  // sfix4
  input   signed [3:0] in0_44;  // sfix4
  input   signed [3:0] in0_45;  // sfix4
  input   signed [3:0] in0_46;  // sfix4
  input   signed [3:0] in0_47;  // sfix4
  input   signed [3:0] in0_48;  // sfix4
  input   signed [3:0] in0_49;  // sfix4
  input   signed [3:0] in0_50;  // sfix4
  input   signed [3:0] in0_51;  // sfix4
  input   signed [3:0] in0_52;  // sfix4
  input   signed [3:0] in0_53;  // sfix4
  input   signed [3:0] in0_54;  // sfix4
  input   signed [3:0] in0_55;  // sfix4
  input   signed [3:0] in0_56;  // sfix4
  input   signed [3:0] in0_57;  // sfix4
  input   signed [3:0] in0_58;  // sfix4
  input   signed [3:0] in0_59;  // sfix4
  input   signed [3:0] in0_60;  // sfix4
  input   signed [3:0] in0_61;  // sfix4
  input   signed [3:0] in0_62;  // sfix4
  input   signed [3:0] in0_63;  // sfix4
  input   in1_start;
  input   in1_end;
  input   in1_valid;
  input   in2;
  input   [15:0] in3;  // uint16
  output  out0_0;  // boolean
  output  out0_1;  // boolean
  output  out0_2;  // boolean
  output  out0_3;  // boolean
  output  out0_4;  // boolean
  output  out0_5;  // boolean
  output  out0_6;  // boolean
  output  out0_7;  // boolean
  output  out0_8;  // boolean
  output  out0_9;  // boolean
  output  out0_10;  // boolean
  output  out0_11;  // boolean
  output  out0_12;  // boolean
  output  out0_13;  // boolean
  output  out0_14;  // boolean
  output  out0_15;  // boolean
  output  out0_16;  // boolean
  output  out0_17;  // boolean
  output  out0_18;  // boolean
  output  out0_19;  // boolean
  output  out0_20;  // boolean
  output  out0_21;  // boolean
  output  out0_22;  // boolean
  output  out0_23;  // boolean
  output  out0_24;  // boolean
  output  out0_25;  // boolean
  output  out0_26;  // boolean
  output  out0_27;  // boolean
  output  out0_28;  // boolean
  output  out0_29;  // boolean
  output  out0_30;  // boolean
  output  out0_31;  // boolean
  output  out0_32;  // boolean
  output  out0_33;  // boolean
  output  out0_34;  // boolean
  output  out0_35;  // boolean
  output  out0_36;  // boolean
  output  out0_37;  // boolean
  output  out0_38;  // boolean
  output  out0_39;  // boolean
  output  out0_40;  // boolean
  output  out0_41;  // boolean
  output  out0_42;  // boolean
  output  out0_43;  // boolean
  output  out0_44;  // boolean
  output  out0_45;  // boolean
  output  out0_46;  // boolean
  output  out0_47;  // boolean
  output  out0_48;  // boolean
  output  out0_49;  // boolean
  output  out0_50;  // boolean
  output  out0_51;  // boolean
  output  out0_52;  // boolean
  output  out0_53;  // boolean
  output  out0_54;  // boolean
  output  out0_55;  // boolean
  output  out0_56;  // boolean
  output  out0_57;  // boolean
  output  out0_58;  // boolean
  output  out0_59;  // boolean
  output  out0_60;  // boolean
  output  out0_61;  // boolean
  output  out0_62;  // boolean
  output  out0_63;  // boolean
  output  out1_start;
  output  out1_end;
  output  out1_valid;
  output  [15:0] out2;  // uint16
  output  out3;


  wire endVld;  // ufix1
  wire startVld;  // ufix1
  reg  validIn;
  reg  enbConst;  // ufix1
  wire const0;  // ufix1
  reg  const0Reg;  // ufix1
  reg  frame_switch_delay;  // ufix1
  wire frameVld;  // ufix1
  wire signed [3:0] data [0:63];  // sfix4 [64]
  reg signed [3:0] dataIn [0:63];  // sfix4 [64]
  reg  startIn;
  reg  endIn;
  reg  bgnIn;
  reg [15:0] ZIn;  // uint16
  wire [8:0] Z_dtc;  // ufix9
  wire [7:0] numIter;  // ufix8
  wire signed [3:0] dataOut_0;  // sfix4
  wire signed [3:0] dataOut_1;  // sfix4
  wire signed [3:0] dataOut_2;  // sfix4
  wire signed [3:0] dataOut_3;  // sfix4
  wire signed [3:0] dataOut_4;  // sfix4
  wire signed [3:0] dataOut_5;  // sfix4
  wire signed [3:0] dataOut_6;  // sfix4
  wire signed [3:0] dataOut_7;  // sfix4
  wire signed [3:0] dataOut_8;  // sfix4
  wire signed [3:0] dataOut_9;  // sfix4
  wire signed [3:0] dataOut_10;  // sfix4
  wire signed [3:0] dataOut_11;  // sfix4
  wire signed [3:0] dataOut_12;  // sfix4
  wire signed [3:0] dataOut_13;  // sfix4
  wire signed [3:0] dataOut_14;  // sfix4
  wire signed [3:0] dataOut_15;  // sfix4
  wire signed [3:0] dataOut_16;  // sfix4
  wire signed [3:0] dataOut_17;  // sfix4
  wire signed [3:0] dataOut_18;  // sfix4
  wire signed [3:0] dataOut_19;  // sfix4
  wire signed [3:0] dataOut_20;  // sfix4
  wire signed [3:0] dataOut_21;  // sfix4
  wire signed [3:0] dataOut_22;  // sfix4
  wire signed [3:0] dataOut_23;  // sfix4
  wire signed [3:0] dataOut_24;  // sfix4
  wire signed [3:0] dataOut_25;  // sfix4
  wire signed [3:0] dataOut_26;  // sfix4
  wire signed [3:0] dataOut_27;  // sfix4
  wire signed [3:0] dataOut_28;  // sfix4
  wire signed [3:0] dataOut_29;  // sfix4
  wire signed [3:0] dataOut_30;  // sfix4
  wire signed [3:0] dataOut_31;  // sfix4
  wire signed [3:0] dataOut_32;  // sfix4
  wire signed [3:0] dataOut_33;  // sfix4
  wire signed [3:0] dataOut_34;  // sfix4
  wire signed [3:0] dataOut_35;  // sfix4
  wire signed [3:0] dataOut_36;  // sfix4
  wire signed [3:0] dataOut_37;  // sfix4
  wire signed [3:0] dataOut_38;  // sfix4
  wire signed [3:0] dataOut_39;  // sfix4
  wire signed [3:0] dataOut_40;  // sfix4
  wire signed [3:0] dataOut_41;  // sfix4
  wire signed [3:0] dataOut_42;  // sfix4
  wire signed [3:0] dataOut_43;  // sfix4
  wire signed [3:0] dataOut_44;  // sfix4
  wire signed [3:0] dataOut_45;  // sfix4
  wire signed [3:0] dataOut_46;  // sfix4
  wire signed [3:0] dataOut_47;  // sfix4
  wire signed [3:0] dataOut_48;  // sfix4
  wire signed [3:0] dataOut_49;  // sfix4
  wire signed [3:0] dataOut_50;  // sfix4
  wire signed [3:0] dataOut_51;  // sfix4
  wire signed [3:0] dataOut_52;  // sfix4
  wire signed [3:0] dataOut_53;  // sfix4
  wire signed [3:0] dataOut_54;  // sfix4
  wire signed [3:0] dataOut_55;  // sfix4
  wire signed [3:0] dataOut_56;  // sfix4
  wire signed [3:0] dataOut_57;  // sfix4
  wire signed [3:0] dataOut_58;  // sfix4
  wire signed [3:0] dataOut_59;  // sfix4
  wire signed [3:0] dataOut_60;  // sfix4
  wire signed [3:0] dataOut_61;  // sfix4
  wire signed [3:0] dataOut_62;  // sfix4
  wire signed [3:0] dataOut_63;  // sfix4
  wire valid;  // ufix1
  wire frameValid;  // ufix1
  wire reset_1;  // ufix1
  wire bgn;  // ufix1
  wire [2:0] iLS;  // ufix3
  wire [8:0] shiftReg;  // ufix9
  wire endInd;  // ufix1
  wire [7:0] niterOut;  // ufix8
  wire [2:0] zAddr;  // ufix3
  wire rstNextFrame;  // ufix1
  wire [5:0] nRowReg;  // ufix6
  wire signed [3:0] dataOut [0:63];  // sfix4 [64]
  wire signed [9:0] dataDTC [0:63];  // sfix10_En4 [64]
  wire endTrigger;  // ufix1
  wire startVldNeg;  // ufix1
  wire endTrigger1;  // ufix1
  reg  [1:0] end_in_reg;  // ufix1 [2]
  wire endTriggerReg;  // ufix1
  wire dataOutReg_0;
  wire dataOutReg_1;
  wire dataOutReg_2;
  wire dataOutReg_3;
  wire dataOutReg_4;
  wire dataOutReg_5;
  wire dataOutReg_6;
  wire dataOutReg_7;
  wire dataOutReg_8;
  wire dataOutReg_9;
  wire dataOutReg_10;
  wire dataOutReg_11;
  wire dataOutReg_12;
  wire dataOutReg_13;
  wire dataOutReg_14;
  wire dataOutReg_15;
  wire dataOutReg_16;
  wire dataOutReg_17;
  wire dataOutReg_18;
  wire dataOutReg_19;
  wire dataOutReg_20;
  wire dataOutReg_21;
  wire dataOutReg_22;
  wire dataOutReg_23;
  wire dataOutReg_24;
  wire dataOutReg_25;
  wire dataOutReg_26;
  wire dataOutReg_27;
  wire dataOutReg_28;
  wire dataOutReg_29;
  wire dataOutReg_30;
  wire dataOutReg_31;
  wire dataOutReg_32;
  wire dataOutReg_33;
  wire dataOutReg_34;
  wire dataOutReg_35;
  wire dataOutReg_36;
  wire dataOutReg_37;
  wire dataOutReg_38;
  wire dataOutReg_39;
  wire dataOutReg_40;
  wire dataOutReg_41;
  wire dataOutReg_42;
  wire dataOutReg_43;
  wire dataOutReg_44;
  wire dataOutReg_45;
  wire dataOutReg_46;
  wire dataOutReg_47;
  wire dataOutReg_48;
  wire dataOutReg_49;
  wire dataOutReg_50;
  wire dataOutReg_51;
  wire dataOutReg_52;
  wire dataOutReg_53;
  wire dataOutReg_54;
  wire dataOutReg_55;
  wire dataOutReg_56;
  wire dataOutReg_57;
  wire dataOutReg_58;
  wire dataOutReg_59;
  wire dataOutReg_60;
  wire dataOutReg_61;
  wire dataOutReg_62;
  wire dataOutReg_63;
  wire startOutReg;
  wire endOutReg;
  wire validOutReg;
  reg  endReg;
  wire cntEnb;  // ufix1
  reg [8:0] countData;  // ufix9
  reg  bgnStart;  // ufix1
  wire [8:0] const66;  // ufix9
  wire [8:0] Z_dtc_1;  // ufix9
  reg [8:0] zStart;  // ufix9
  wire const1;  // ufix1
  wire [8:0] subtractor_1;  // ufix9
  wire [8:0] shiftReg_1;  // ufix9
  wire [2:0] shiftE;  // ufix3
  wire [2:0] adder_1;  // ufix3
  wire [2:0] shiftCount;  // ufix3
  wire [11:0] multiplier_mul_temp;  // ufix12
  wire [8:0] maxcount1;  // ufix9
  wire [8:0] const50;  // ufix9
  wire [11:0] multiplier_mul_temp_1;  // ufix12
  wire [8:0] maxcount2;  // ufix9
  wire [8:0] maxCount;  // ufix9
  wire [8:0] subtractor_3;  // ufix9
  wire [8:0] maxCountReg;  // ufix9
  wire rel_count;  // ufix1
  reg  invalid_length_switch_delay;  // ufix1
  wire invalidLength;  // ufix1
  reg  invalid_z_switch_delay;  // ufix1
  wire invalidZ;  // ufix1
  wire newEnb;  // ufix1
  reg  validReg;
  wire nFrameEnb_tmp;  // ufix1
  wire nFrameEnb;  // ufix1
  reg  nextFrame_switch_delay;  // ufix1
  wire nFrame;  // ufix1
  wire validReg_1;
  reg  validOut_1;
  wire nextFrame_1;
  wire endReg_1;
  reg  endOut_1;
  wire endOutVld;  // ufix1
  reg  endOutVldReg;  // ufix1
  wire [63:0] zData;  // boolean [64]
  wire [63:0] dataOutReg;  // boolean [64]
  reg  [63:0] decData;  // boolean [64]
  wire [63:0] decData_1;  // boolean [64]
  reg  [63:0] decBits;  // boolean [64]
  reg  startReg;
  wire startReg_1;
  reg  startOut_1;
  wire startOutVld;  // ufix1
  wire enbZ;  // ufix1
  reg  frameVldReg;  // ufix1
  wire zReset;  // ufix1
  wire [15:0] Z_dtc_2;  // uint16
  reg [15:0] lifting_Size_switch_delay;  // ufix16
  wire [15:0] liftSize;  // uint16
  reg signed [31:0] _t_0_0;  // int32
  reg signed [31:0] _t_1;  // int32


  assign endVld = in1_end & in1_valid;

  assign startVld = in1_start & in1_valid;

  always @(posedge clk or negedge reset)
    begin : c_process
      if (reset == 1'b0) begin
        validIn <= 1'b0;
      end
      else begin
        if (enb) begin
          validIn <= in1_valid;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : c_1_process
      if (reset == 1'b0) begin
        enbConst <= 1'b0;
      end
      else begin
        if (enb) begin
          enbConst <= validIn;
        end
      end
    end

  assign const0 = 1'b0;

  always @(posedge clk or negedge reset)
    begin : c_2_process
      if (reset == 1'b0) begin
        const0Reg <= 1'b0;
      end
      else begin
        if (enb && enbConst) begin
          const0Reg <= const0;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : frame_process
      if (reset == 1'b0) begin
        frame_switch_delay <= 1'b1;
      end
      else begin
        if (enb) begin
          if (startVld == 1'b1) begin
            frame_switch_delay <= 1'b1;
          end
          else begin
            if (endVld) begin
              frame_switch_delay <= const0Reg;
            end
          end
        end
      end
    end

  assign frameVld = (startVld == 1'b1 ? 1'b1 :
              frame_switch_delay);

  assign data[0] = in0_0;
  assign data[1] = in0_1;
  assign data[2] = in0_2;
  assign data[3] = in0_3;
  assign data[4] = in0_4;
  assign data[5] = in0_5;
  assign data[6] = in0_6;
  assign data[7] = in0_7;
  assign data[8] = in0_8;
  assign data[9] = in0_9;
  assign data[10] = in0_10;
  assign data[11] = in0_11;
  assign data[12] = in0_12;
  assign data[13] = in0_13;
  assign data[14] = in0_14;
  assign data[15] = in0_15;
  assign data[16] = in0_16;
  assign data[17] = in0_17;
  assign data[18] = in0_18;
  assign data[19] = in0_19;
  assign data[20] = in0_20;
  assign data[21] = in0_21;
  assign data[22] = in0_22;
  assign data[23] = in0_23;
  assign data[24] = in0_24;
  assign data[25] = in0_25;
  assign data[26] = in0_26;
  assign data[27] = in0_27;
  assign data[28] = in0_28;
  assign data[29] = in0_29;
  assign data[30] = in0_30;
  assign data[31] = in0_31;
  assign data[32] = in0_32;
  assign data[33] = in0_33;
  assign data[34] = in0_34;
  assign data[35] = in0_35;
  assign data[36] = in0_36;
  assign data[37] = in0_37;
  assign data[38] = in0_38;
  assign data[39] = in0_39;
  assign data[40] = in0_40;
  assign data[41] = in0_41;
  assign data[42] = in0_42;
  assign data[43] = in0_43;
  assign data[44] = in0_44;
  assign data[45] = in0_45;
  assign data[46] = in0_46;
  assign data[47] = in0_47;
  assign data[48] = in0_48;
  assign data[49] = in0_49;
  assign data[50] = in0_50;
  assign data[51] = in0_51;
  assign data[52] = in0_52;
  assign data[53] = in0_53;
  assign data[54] = in0_54;
  assign data[55] = in0_55;
  assign data[56] = in0_56;
  assign data[57] = in0_57;
  assign data[58] = in0_58;
  assign data[59] = in0_59;
  assign data[60] = in0_60;
  assign data[61] = in0_61;
  assign data[62] = in0_62;
  assign data[63] = in0_63;

  always @(posedge clk or negedge reset)
    begin : c_3_process
      if (reset == 1'b0) begin
        for(_t_1 = 32'sd0; _t_1 <= 32'sd63; _t_1 = _t_1 + 32'sd1) begin
          dataIn[_t_1] <= 4'sb0000;
        end
      end
      else begin
        if (enb) begin
          for(_t_0_0 = 32'sd0; _t_0_0 <= 32'sd63; _t_0_0 = _t_0_0 + 32'sd1) begin
            dataIn[_t_0_0] <= data[_t_0_0];
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : c_4_process
      if (reset == 1'b0) begin
        startIn <= 1'b0;
      end
      else begin
        if (enb) begin
          startIn <= in1_start;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : c_5_process
      if (reset == 1'b0) begin
        endIn <= 1'b0;
      end
      else begin
        if (enb) begin
          endIn <= in1_end;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : c_6_process
      if (reset == 1'b0) begin
        bgnIn <= 1'b0;
      end
      else begin
        if (enb) begin
          bgnIn <= in2;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : c_7_process
      if (reset == 1'b0) begin
        ZIn <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          ZIn <= in3;
        end
      end
    end

  assign Z_dtc = ZIn[8:0];

  assign numIter = 8'b00001000;

  dec_CodeParameters u_Code_Parameters (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dataIn_0(dataIn[0]),  // sfix4
                                        .dataIn_1(dataIn[1]),  // sfix4
                                        .dataIn_2(dataIn[2]),  // sfix4
                                        .dataIn_3(dataIn[3]),  // sfix4
                                        .dataIn_4(dataIn[4]),  // sfix4
                                        .dataIn_5(dataIn[5]),  // sfix4
                                        .dataIn_6(dataIn[6]),  // sfix4
                                        .dataIn_7(dataIn[7]),  // sfix4
                                        .dataIn_8(dataIn[8]),  // sfix4
                                        .dataIn_9(dataIn[9]),  // sfix4
                                        .dataIn_10(dataIn[10]),  // sfix4
                                        .dataIn_11(dataIn[11]),  // sfix4
                                        .dataIn_12(dataIn[12]),  // sfix4
                                        .dataIn_13(dataIn[13]),  // sfix4
                                        .dataIn_14(dataIn[14]),  // sfix4
                                        .dataIn_15(dataIn[15]),  // sfix4
                                        .dataIn_16(dataIn[16]),  // sfix4
                                        .dataIn_17(dataIn[17]),  // sfix4
                                        .dataIn_18(dataIn[18]),  // sfix4
                                        .dataIn_19(dataIn[19]),  // sfix4
                                        .dataIn_20(dataIn[20]),  // sfix4
                                        .dataIn_21(dataIn[21]),  // sfix4
                                        .dataIn_22(dataIn[22]),  // sfix4
                                        .dataIn_23(dataIn[23]),  // sfix4
                                        .dataIn_24(dataIn[24]),  // sfix4
                                        .dataIn_25(dataIn[25]),  // sfix4
                                        .dataIn_26(dataIn[26]),  // sfix4
                                        .dataIn_27(dataIn[27]),  // sfix4
                                        .dataIn_28(dataIn[28]),  // sfix4
                                        .dataIn_29(dataIn[29]),  // sfix4
                                        .dataIn_30(dataIn[30]),  // sfix4
                                        .dataIn_31(dataIn[31]),  // sfix4
                                        .dataIn_32(dataIn[32]),  // sfix4
                                        .dataIn_33(dataIn[33]),  // sfix4
                                        .dataIn_34(dataIn[34]),  // sfix4
                                        .dataIn_35(dataIn[35]),  // sfix4
                                        .dataIn_36(dataIn[36]),  // sfix4
                                        .dataIn_37(dataIn[37]),  // sfix4
                                        .dataIn_38(dataIn[38]),  // sfix4
                                        .dataIn_39(dataIn[39]),  // sfix4
                                        .dataIn_40(dataIn[40]),  // sfix4
                                        .dataIn_41(dataIn[41]),  // sfix4
                                        .dataIn_42(dataIn[42]),  // sfix4
                                        .dataIn_43(dataIn[43]),  // sfix4
                                        .dataIn_44(dataIn[44]),  // sfix4
                                        .dataIn_45(dataIn[45]),  // sfix4
                                        .dataIn_46(dataIn[46]),  // sfix4
                                        .dataIn_47(dataIn[47]),  // sfix4
                                        .dataIn_48(dataIn[48]),  // sfix4
                                        .dataIn_49(dataIn[49]),  // sfix4
                                        .dataIn_50(dataIn[50]),  // sfix4
                                        .dataIn_51(dataIn[51]),  // sfix4
                                        .dataIn_52(dataIn[52]),  // sfix4
                                        .dataIn_53(dataIn[53]),  // sfix4
                                        .dataIn_54(dataIn[54]),  // sfix4
                                        .dataIn_55(dataIn[55]),  // sfix4
                                        .dataIn_56(dataIn[56]),  // sfix4
                                        .dataIn_57(dataIn[57]),  // sfix4
                                        .dataIn_58(dataIn[58]),  // sfix4
                                        .dataIn_59(dataIn[59]),  // sfix4
                                        .dataIn_60(dataIn[60]),  // sfix4
                                        .dataIn_61(dataIn[61]),  // sfix4
                                        .dataIn_62(dataIn[62]),  // sfix4
                                        .dataIn_63(dataIn[63]),  // sfix4
                                        .startIn(startIn),
                                        .endIn(endIn),
                                        .validIn(validIn),
                                        .bgn(bgnIn),
                                        .liftsize(Z_dtc),  // ufix9
                                        .niter(numIter),  // ufix8
                                        .dataOut_0(dataOut_0),  // sfix4
                                        .dataOut_1(dataOut_1),  // sfix4
                                        .dataOut_2(dataOut_2),  // sfix4
                                        .dataOut_3(dataOut_3),  // sfix4
                                        .dataOut_4(dataOut_4),  // sfix4
                                        .dataOut_5(dataOut_5),  // sfix4
                                        .dataOut_6(dataOut_6),  // sfix4
                                        .dataOut_7(dataOut_7),  // sfix4
                                        .dataOut_8(dataOut_8),  // sfix4
                                        .dataOut_9(dataOut_9),  // sfix4
                                        .dataOut_10(dataOut_10),  // sfix4
                                        .dataOut_11(dataOut_11),  // sfix4
                                        .dataOut_12(dataOut_12),  // sfix4
                                        .dataOut_13(dataOut_13),  // sfix4
                                        .dataOut_14(dataOut_14),  // sfix4
                                        .dataOut_15(dataOut_15),  // sfix4
                                        .dataOut_16(dataOut_16),  // sfix4
                                        .dataOut_17(dataOut_17),  // sfix4
                                        .dataOut_18(dataOut_18),  // sfix4
                                        .dataOut_19(dataOut_19),  // sfix4
                                        .dataOut_20(dataOut_20),  // sfix4
                                        .dataOut_21(dataOut_21),  // sfix4
                                        .dataOut_22(dataOut_22),  // sfix4
                                        .dataOut_23(dataOut_23),  // sfix4
                                        .dataOut_24(dataOut_24),  // sfix4
                                        .dataOut_25(dataOut_25),  // sfix4
                                        .dataOut_26(dataOut_26),  // sfix4
                                        .dataOut_27(dataOut_27),  // sfix4
                                        .dataOut_28(dataOut_28),  // sfix4
                                        .dataOut_29(dataOut_29),  // sfix4
                                        .dataOut_30(dataOut_30),  // sfix4
                                        .dataOut_31(dataOut_31),  // sfix4
                                        .dataOut_32(dataOut_32),  // sfix4
                                        .dataOut_33(dataOut_33),  // sfix4
                                        .dataOut_34(dataOut_34),  // sfix4
                                        .dataOut_35(dataOut_35),  // sfix4
                                        .dataOut_36(dataOut_36),  // sfix4
                                        .dataOut_37(dataOut_37),  // sfix4
                                        .dataOut_38(dataOut_38),  // sfix4
                                        .dataOut_39(dataOut_39),  // sfix4
                                        .dataOut_40(dataOut_40),  // sfix4
                                        .dataOut_41(dataOut_41),  // sfix4
                                        .dataOut_42(dataOut_42),  // sfix4
                                        .dataOut_43(dataOut_43),  // sfix4
                                        .dataOut_44(dataOut_44),  // sfix4
                                        .dataOut_45(dataOut_45),  // sfix4
                                        .dataOut_46(dataOut_46),  // sfix4
                                        .dataOut_47(dataOut_47),  // sfix4
                                        .dataOut_48(dataOut_48),  // sfix4
                                        .dataOut_49(dataOut_49),  // sfix4
                                        .dataOut_50(dataOut_50),  // sfix4
                                        .dataOut_51(dataOut_51),  // sfix4
                                        .dataOut_52(dataOut_52),  // sfix4
                                        .dataOut_53(dataOut_53),  // sfix4
                                        .dataOut_54(dataOut_54),  // sfix4
                                        .dataOut_55(dataOut_55),  // sfix4
                                        .dataOut_56(dataOut_56),  // sfix4
                                        .dataOut_57(dataOut_57),  // sfix4
                                        .dataOut_58(dataOut_58),  // sfix4
                                        .dataOut_59(dataOut_59),  // sfix4
                                        .dataOut_60(dataOut_60),  // sfix4
                                        .dataOut_61(dataOut_61),  // sfix4
                                        .dataOut_62(dataOut_62),  // sfix4
                                        .dataOut_63(dataOut_63),  // sfix4
                                        .validOut(valid),  // ufix1
                                        .frameValid(frameValid),  // ufix1
                                        .reset_1(reset_1),  // ufix1
                                        .bgn_1(bgn),  // ufix1
                                        .iLS(iLS),  // ufix3
                                        .liftsize_1(shiftReg),  // ufix9
                                        .endInd(endInd),  // ufix1
                                        .niter_1(niterOut),  // ufix8
                                        .zAddr(zAddr),  // ufix3
                                        .rstNextFrame(rstNextFrame),  // ufix1
                                        .nRowOut(nRowReg)  // ufix6
                                        );

  assign dataOut[0] = dataOut_0;
  assign dataOut[1] = dataOut_1;
  assign dataOut[2] = dataOut_2;
  assign dataOut[3] = dataOut_3;
  assign dataOut[4] = dataOut_4;
  assign dataOut[5] = dataOut_5;
  assign dataOut[6] = dataOut_6;
  assign dataOut[7] = dataOut_7;
  assign dataOut[8] = dataOut_8;
  assign dataOut[9] = dataOut_9;
  assign dataOut[10] = dataOut_10;
  assign dataOut[11] = dataOut_11;
  assign dataOut[12] = dataOut_12;
  assign dataOut[13] = dataOut_13;
  assign dataOut[14] = dataOut_14;
  assign dataOut[15] = dataOut_15;
  assign dataOut[16] = dataOut_16;
  assign dataOut[17] = dataOut_17;
  assign dataOut[18] = dataOut_18;
  assign dataOut[19] = dataOut_19;
  assign dataOut[20] = dataOut_20;
  assign dataOut[21] = dataOut_21;
  assign dataOut[22] = dataOut_22;
  assign dataOut[23] = dataOut_23;
  assign dataOut[24] = dataOut_24;
  assign dataOut[25] = dataOut_25;
  assign dataOut[26] = dataOut_26;
  assign dataOut[27] = dataOut_27;
  assign dataOut[28] = dataOut_28;
  assign dataOut[29] = dataOut_29;
  assign dataOut[30] = dataOut_30;
  assign dataOut[31] = dataOut_31;
  assign dataOut[32] = dataOut_32;
  assign dataOut[33] = dataOut_33;
  assign dataOut[34] = dataOut_34;
  assign dataOut[35] = dataOut_35;
  assign dataOut[36] = dataOut_36;
  assign dataOut[37] = dataOut_37;
  assign dataOut[38] = dataOut_38;
  assign dataOut[39] = dataOut_39;
  assign dataOut[40] = dataOut_40;
  assign dataOut[41] = dataOut_41;
  assign dataOut[42] = dataOut_42;
  assign dataOut[43] = dataOut_43;
  assign dataOut[44] = dataOut_44;
  assign dataOut[45] = dataOut_45;
  assign dataOut[46] = dataOut_46;
  assign dataOut[47] = dataOut_47;
  assign dataOut[48] = dataOut_48;
  assign dataOut[49] = dataOut_49;
  assign dataOut[50] = dataOut_50;
  assign dataOut[51] = dataOut_51;
  assign dataOut[52] = dataOut_52;
  assign dataOut[53] = dataOut_53;
  assign dataOut[54] = dataOut_54;
  assign dataOut[55] = dataOut_55;
  assign dataOut[56] = dataOut_56;
  assign dataOut[57] = dataOut_57;
  assign dataOut[58] = dataOut_58;
  assign dataOut[59] = dataOut_59;
  assign dataOut[60] = dataOut_60;
  assign dataOut[61] = dataOut_61;
  assign dataOut[62] = dataOut_62;
  assign dataOut[63] = dataOut_63;


  genvar ii1;
  generate
    for(ii1 = 32'sd0; ii1 <= 32'sd63; ii1 = ii1 + 32'sd1) begin:dataDTC_gen
      assign dataDTC[ii1] = {{2{dataOut[ii1][3]}}, {dataOut[ii1], 4'b0000}};
    end
  endgenerate

  assign endTrigger = endVld & frameVld;

  assign startVldNeg =  ~ startVld;

  assign endTrigger1 = endTrigger & startVldNeg;

  always @(posedge clk or negedge reset)
    begin : end_in_process
      if (reset == 1'b0) begin
        end_in_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          end_in_reg[0] <= endTrigger1;
          end_in_reg[1] <= end_in_reg[0];
        end
      end
    end

  assign endTriggerReg = end_in_reg[1];

  dec_DecoderCore u_Decoder_Core (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dataIn_0(dataDTC[0]),  // sfix10_En4
                                  .dataIn_1(dataDTC[1]),  // sfix10_En4
                                  .dataIn_2(dataDTC[2]),  // sfix10_En4
                                  .dataIn_3(dataDTC[3]),  // sfix10_En4
                                  .dataIn_4(dataDTC[4]),  // sfix10_En4
                                  .dataIn_5(dataDTC[5]),  // sfix10_En4
                                  .dataIn_6(dataDTC[6]),  // sfix10_En4
                                  .dataIn_7(dataDTC[7]),  // sfix10_En4
                                  .dataIn_8(dataDTC[8]),  // sfix10_En4
                                  .dataIn_9(dataDTC[9]),  // sfix10_En4
                                  .dataIn_10(dataDTC[10]),  // sfix10_En4
                                  .dataIn_11(dataDTC[11]),  // sfix10_En4
                                  .dataIn_12(dataDTC[12]),  // sfix10_En4
                                  .dataIn_13(dataDTC[13]),  // sfix10_En4
                                  .dataIn_14(dataDTC[14]),  // sfix10_En4
                                  .dataIn_15(dataDTC[15]),  // sfix10_En4
                                  .dataIn_16(dataDTC[16]),  // sfix10_En4
                                  .dataIn_17(dataDTC[17]),  // sfix10_En4
                                  .dataIn_18(dataDTC[18]),  // sfix10_En4
                                  .dataIn_19(dataDTC[19]),  // sfix10_En4
                                  .dataIn_20(dataDTC[20]),  // sfix10_En4
                                  .dataIn_21(dataDTC[21]),  // sfix10_En4
                                  .dataIn_22(dataDTC[22]),  // sfix10_En4
                                  .dataIn_23(dataDTC[23]),  // sfix10_En4
                                  .dataIn_24(dataDTC[24]),  // sfix10_En4
                                  .dataIn_25(dataDTC[25]),  // sfix10_En4
                                  .dataIn_26(dataDTC[26]),  // sfix10_En4
                                  .dataIn_27(dataDTC[27]),  // sfix10_En4
                                  .dataIn_28(dataDTC[28]),  // sfix10_En4
                                  .dataIn_29(dataDTC[29]),  // sfix10_En4
                                  .dataIn_30(dataDTC[30]),  // sfix10_En4
                                  .dataIn_31(dataDTC[31]),  // sfix10_En4
                                  .dataIn_32(dataDTC[32]),  // sfix10_En4
                                  .dataIn_33(dataDTC[33]),  // sfix10_En4
                                  .dataIn_34(dataDTC[34]),  // sfix10_En4
                                  .dataIn_35(dataDTC[35]),  // sfix10_En4
                                  .dataIn_36(dataDTC[36]),  // sfix10_En4
                                  .dataIn_37(dataDTC[37]),  // sfix10_En4
                                  .dataIn_38(dataDTC[38]),  // sfix10_En4
                                  .dataIn_39(dataDTC[39]),  // sfix10_En4
                                  .dataIn_40(dataDTC[40]),  // sfix10_En4
                                  .dataIn_41(dataDTC[41]),  // sfix10_En4
                                  .dataIn_42(dataDTC[42]),  // sfix10_En4
                                  .dataIn_43(dataDTC[43]),  // sfix10_En4
                                  .dataIn_44(dataDTC[44]),  // sfix10_En4
                                  .dataIn_45(dataDTC[45]),  // sfix10_En4
                                  .dataIn_46(dataDTC[46]),  // sfix10_En4
                                  .dataIn_47(dataDTC[47]),  // sfix10_En4
                                  .dataIn_48(dataDTC[48]),  // sfix10_En4
                                  .dataIn_49(dataDTC[49]),  // sfix10_En4
                                  .dataIn_50(dataDTC[50]),  // sfix10_En4
                                  .dataIn_51(dataDTC[51]),  // sfix10_En4
                                  .dataIn_52(dataDTC[52]),  // sfix10_En4
                                  .dataIn_53(dataDTC[53]),  // sfix10_En4
                                  .dataIn_54(dataDTC[54]),  // sfix10_En4
                                  .dataIn_55(dataDTC[55]),  // sfix10_En4
                                  .dataIn_56(dataDTC[56]),  // sfix10_En4
                                  .dataIn_57(dataDTC[57]),  // sfix10_En4
                                  .dataIn_58(dataDTC[58]),  // sfix10_En4
                                  .dataIn_59(dataDTC[59]),  // sfix10_En4
                                  .dataIn_60(dataDTC[60]),  // sfix10_En4
                                  .dataIn_61(dataDTC[61]),  // sfix10_En4
                                  .dataIn_62(dataDTC[62]),  // sfix10_En4
                                  .dataIn_63(dataDTC[63]),  // sfix10_En4
                                  .validIn(valid),  // ufix1
                                  .frameValid(frameValid),  // ufix1
                                  .reset_1(reset_1),  // ufix1
                                  .bgn(bgn),  // ufix1
                                  .iLS(iLS),  // ufix3
                                  .liftsize(shiftReg),  // ufix9
                                  .endInd(endInd),  // ufix1
                                  .niter(niterOut),  // ufix8
                                  .zAddr(zAddr),  // ufix3
                                  .endReg(endTriggerReg),  // ufix1
                                  .nrow(nRowReg),  // ufix6
                                  .dataOut_0(dataOutReg_0),  // boolean
                                  .dataOut_1(dataOutReg_1),  // boolean
                                  .dataOut_2(dataOutReg_2),  // boolean
                                  .dataOut_3(dataOutReg_3),  // boolean
                                  .dataOut_4(dataOutReg_4),  // boolean
                                  .dataOut_5(dataOutReg_5),  // boolean
                                  .dataOut_6(dataOutReg_6),  // boolean
                                  .dataOut_7(dataOutReg_7),  // boolean
                                  .dataOut_8(dataOutReg_8),  // boolean
                                  .dataOut_9(dataOutReg_9),  // boolean
                                  .dataOut_10(dataOutReg_10),  // boolean
                                  .dataOut_11(dataOutReg_11),  // boolean
                                  .dataOut_12(dataOutReg_12),  // boolean
                                  .dataOut_13(dataOutReg_13),  // boolean
                                  .dataOut_14(dataOutReg_14),  // boolean
                                  .dataOut_15(dataOutReg_15),  // boolean
                                  .dataOut_16(dataOutReg_16),  // boolean
                                  .dataOut_17(dataOutReg_17),  // boolean
                                  .dataOut_18(dataOutReg_18),  // boolean
                                  .dataOut_19(dataOutReg_19),  // boolean
                                  .dataOut_20(dataOutReg_20),  // boolean
                                  .dataOut_21(dataOutReg_21),  // boolean
                                  .dataOut_22(dataOutReg_22),  // boolean
                                  .dataOut_23(dataOutReg_23),  // boolean
                                  .dataOut_24(dataOutReg_24),  // boolean
                                  .dataOut_25(dataOutReg_25),  // boolean
                                  .dataOut_26(dataOutReg_26),  // boolean
                                  .dataOut_27(dataOutReg_27),  // boolean
                                  .dataOut_28(dataOutReg_28),  // boolean
                                  .dataOut_29(dataOutReg_29),  // boolean
                                  .dataOut_30(dataOutReg_30),  // boolean
                                  .dataOut_31(dataOutReg_31),  // boolean
                                  .dataOut_32(dataOutReg_32),  // boolean
                                  .dataOut_33(dataOutReg_33),  // boolean
                                  .dataOut_34(dataOutReg_34),  // boolean
                                  .dataOut_35(dataOutReg_35),  // boolean
                                  .dataOut_36(dataOutReg_36),  // boolean
                                  .dataOut_37(dataOutReg_37),  // boolean
                                  .dataOut_38(dataOutReg_38),  // boolean
                                  .dataOut_39(dataOutReg_39),  // boolean
                                  .dataOut_40(dataOutReg_40),  // boolean
                                  .dataOut_41(dataOutReg_41),  // boolean
                                  .dataOut_42(dataOutReg_42),  // boolean
                                  .dataOut_43(dataOutReg_43),  // boolean
                                  .dataOut_44(dataOutReg_44),  // boolean
                                  .dataOut_45(dataOutReg_45),  // boolean
                                  .dataOut_46(dataOutReg_46),  // boolean
                                  .dataOut_47(dataOutReg_47),  // boolean
                                  .dataOut_48(dataOutReg_48),  // boolean
                                  .dataOut_49(dataOutReg_49),  // boolean
                                  .dataOut_50(dataOutReg_50),  // boolean
                                  .dataOut_51(dataOutReg_51),  // boolean
                                  .dataOut_52(dataOutReg_52),  // boolean
                                  .dataOut_53(dataOutReg_53),  // boolean
                                  .dataOut_54(dataOutReg_54),  // boolean
                                  .dataOut_55(dataOutReg_55),  // boolean
                                  .dataOut_56(dataOutReg_56),  // boolean
                                  .dataOut_57(dataOutReg_57),  // boolean
                                  .dataOut_58(dataOutReg_58),  // boolean
                                  .dataOut_59(dataOutReg_59),  // boolean
                                  .dataOut_60(dataOutReg_60),  // boolean
                                  .dataOut_61(dataOutReg_61),  // boolean
                                  .dataOut_62(dataOutReg_62),  // boolean
                                  .dataOut_63(dataOutReg_63),  // boolean
                                  .startOut(startOutReg),
                                  .endOut(endOutReg),
                                  .validOut(validOutReg)
                                  );

  always @(posedge clk or negedge reset)
    begin : c_8_process
      if (reset == 1'b0) begin
        endReg <= 1'b0;
      end
      else begin
        if (enb) begin
          endReg <= endOutReg;
        end
      end
    end

  assign cntEnb = frameVld & in1_valid;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 396
  // Counter for input data length
  always @(posedge clk or negedge reset)
    begin : Counting_Data_process
      if (reset == 1'b0) begin
        countData <= 9'b000000001;
      end
      else begin
        if (enb) begin
          if (startVld == 1'b1) begin
            countData <= 9'b000000001;
          end
          else if (cntEnb == 1'b1) begin
            if (countData >= 9'b110001100) begin
              countData <= 9'b000000001;
            end
            else begin
              countData <= countData + 9'b000000001;
            end
          end
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : alpha1_process
      if (reset == 1'b0) begin
        bgnStart <= 1'b0;
      end
      else begin
        if (enb && startVld) begin
          bgnStart <= in2;
        end
      end
    end

  assign const66 = 9'b001000010;

  assign Z_dtc_1 = in3[8:0];

  always @(posedge clk or negedge reset)
    begin : alpha2_process
      if (reset == 1'b0) begin
        zStart <= 9'b000000000;
      end
      else begin
        if (enb && startVld) begin
          zStart <= Z_dtc_1;
        end
      end
    end

  assign const1 = 1'b1;

  assign subtractor_1 = {8'b0, const1};
  assign shiftReg_1 = zStart - subtractor_1;

  assign shiftE = shiftReg_1[8:6];

  assign adder_1 = {2'b0, const1};
  assign shiftCount = shiftE + adder_1;

  assign multiplier_mul_temp = const66 * shiftCount;
  assign maxcount1 = multiplier_mul_temp[8:0];

  assign const50 = 9'b000110010;

  assign multiplier_mul_temp_1 = const50 * shiftCount;
  assign maxcount2 = multiplier_mul_temp_1[8:0];

  // Input data count based on bgn and lifting size
  assign maxCount = (bgnStart == 1'b0 ? maxcount1 :
              maxcount2);

  assign subtractor_3 = {8'b0, const1};
  assign maxCountReg = maxCount - subtractor_3;

  // Comparison of counter to max count
  assign rel_count = countData != maxCountReg;

  always @(posedge clk or negedge reset)
    begin : invalid_length_process
      if (reset == 1'b0) begin
        invalid_length_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (endTriggerReg == 1'b1) begin
            invalid_length_switch_delay <= 1'b0;
          end
          else begin
            if (endTrigger1) begin
              invalid_length_switch_delay <= rel_count;
            end
          end
        end
      end
    end

  assign invalidLength = (endTriggerReg == 1'b1 ? 1'b0 :
              invalid_length_switch_delay);

  always @(posedge clk or negedge reset)
    begin : invalid_z_process
      if (reset == 1'b0) begin
        invalid_z_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (endTriggerReg == 1'b1) begin
            invalid_z_switch_delay <= 1'b0;
          end
          else begin
            if (endTrigger1) begin
              invalid_z_switch_delay <= rstNextFrame;
            end
          end
        end
      end
    end

  assign invalidZ = (endTriggerReg == 1'b1 ? 1'b0 :
              invalid_z_switch_delay);

  assign newEnb = invalidLength | invalidZ;

  always @(posedge clk or negedge reset)
    begin : c_9_process
      if (reset == 1'b0) begin
        validReg <= 1'b0;
      end
      else begin
        if (enb) begin
          validReg <= validOutReg;
        end
      end
    end

  assign nFrameEnb = nFrameEnb_tmp & startVldNeg;

  always @(posedge clk or negedge reset)
    begin : nextFrame_process
      if (reset == 1'b0) begin
        nextFrame_switch_delay <= 1'b1;
      end
      else begin
        if (enb) begin
          if (nFrameEnb == 1'b1) begin
            nextFrame_switch_delay <= 1'b1;
          end
          else begin
            if (startVld) begin
              nextFrame_switch_delay <= const0Reg;
            end
          end
        end
      end
    end

  assign nFrame = (nFrameEnb == 1'b1 ? 1'b1 :
              nextFrame_switch_delay);

  always @(posedge clk or negedge reset)
    begin : validOut_process
      if (reset == 1'b0) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (frameVld == 1'b1) begin
            validOut_1 <= 1'b0;
          end
          else begin
            validOut_1 <= validReg_1;
          end
        end
      end
    end

  assign endReg_1 = (nextFrame_1 == 1'b0 ? endReg :
              const0);

  always @(posedge clk or negedge reset)
    begin : endOut_process
      if (reset == 1'b0) begin
        endOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (frameVld == 1'b1) begin
            endOut_1 <= 1'b0;
          end
          else begin
            endOut_1 <= endReg_1;
          end
        end
      end
    end

  assign endOutVld = endOut_1 & validOut_1;

  always @(posedge clk or negedge reset)
    begin : c_10_process
      if (reset == 1'b0) begin
        endOutVldReg <= 1'b0;
      end
      else begin
        if (enb) begin
          endOutVldReg <= endOutVld;
        end
      end
    end

  assign nFrameEnb_tmp = endOutVldReg | newEnb;

  assign nextFrame_1 = (nFrameEnb_tmp == 1'b0 ? nFrame :
              const1);

  assign validReg_1 = (nextFrame_1 == 1'b0 ? validReg :
              const0);

  assign zData = {64{1'b0}};

  assign dataOutReg[0] = dataOutReg_0;
  assign dataOutReg[1] = dataOutReg_1;
  assign dataOutReg[2] = dataOutReg_2;
  assign dataOutReg[3] = dataOutReg_3;
  assign dataOutReg[4] = dataOutReg_4;
  assign dataOutReg[5] = dataOutReg_5;
  assign dataOutReg[6] = dataOutReg_6;
  assign dataOutReg[7] = dataOutReg_7;
  assign dataOutReg[8] = dataOutReg_8;
  assign dataOutReg[9] = dataOutReg_9;
  assign dataOutReg[10] = dataOutReg_10;
  assign dataOutReg[11] = dataOutReg_11;
  assign dataOutReg[12] = dataOutReg_12;
  assign dataOutReg[13] = dataOutReg_13;
  assign dataOutReg[14] = dataOutReg_14;
  assign dataOutReg[15] = dataOutReg_15;
  assign dataOutReg[16] = dataOutReg_16;
  assign dataOutReg[17] = dataOutReg_17;
  assign dataOutReg[18] = dataOutReg_18;
  assign dataOutReg[19] = dataOutReg_19;
  assign dataOutReg[20] = dataOutReg_20;
  assign dataOutReg[21] = dataOutReg_21;
  assign dataOutReg[22] = dataOutReg_22;
  assign dataOutReg[23] = dataOutReg_23;
  assign dataOutReg[24] = dataOutReg_24;
  assign dataOutReg[25] = dataOutReg_25;
  assign dataOutReg[26] = dataOutReg_26;
  assign dataOutReg[27] = dataOutReg_27;
  assign dataOutReg[28] = dataOutReg_28;
  assign dataOutReg[29] = dataOutReg_29;
  assign dataOutReg[30] = dataOutReg_30;
  assign dataOutReg[31] = dataOutReg_31;
  assign dataOutReg[32] = dataOutReg_32;
  assign dataOutReg[33] = dataOutReg_33;
  assign dataOutReg[34] = dataOutReg_34;
  assign dataOutReg[35] = dataOutReg_35;
  assign dataOutReg[36] = dataOutReg_36;
  assign dataOutReg[37] = dataOutReg_37;
  assign dataOutReg[38] = dataOutReg_38;
  assign dataOutReg[39] = dataOutReg_39;
  assign dataOutReg[40] = dataOutReg_40;
  assign dataOutReg[41] = dataOutReg_41;
  assign dataOutReg[42] = dataOutReg_42;
  assign dataOutReg[43] = dataOutReg_43;
  assign dataOutReg[44] = dataOutReg_44;
  assign dataOutReg[45] = dataOutReg_45;
  assign dataOutReg[46] = dataOutReg_46;
  assign dataOutReg[47] = dataOutReg_47;
  assign dataOutReg[48] = dataOutReg_48;
  assign dataOutReg[49] = dataOutReg_49;
  assign dataOutReg[50] = dataOutReg_50;
  assign dataOutReg[51] = dataOutReg_51;
  assign dataOutReg[52] = dataOutReg_52;
  assign dataOutReg[53] = dataOutReg_53;
  assign dataOutReg[54] = dataOutReg_54;
  assign dataOutReg[55] = dataOutReg_55;
  assign dataOutReg[56] = dataOutReg_56;
  assign dataOutReg[57] = dataOutReg_57;
  assign dataOutReg[58] = dataOutReg_58;
  assign dataOutReg[59] = dataOutReg_59;
  assign dataOutReg[60] = dataOutReg_60;
  assign dataOutReg[61] = dataOutReg_61;
  assign dataOutReg[62] = dataOutReg_62;
  assign dataOutReg[63] = dataOutReg_63;

  always @(posedge clk or negedge reset)
    begin : dataOut_64_process
      if (reset == 1'b0) begin
        decData <= {64{1'b0}};
      end
      else begin
        if (enb && validOutReg) begin
          decData <= dataOutReg;
        end
      end
    end

  assign decData_1 = (validReg_1 == 1'b0 ? zData :
              decData);

  always @(posedge clk or negedge reset)
    begin : dataOut_65_process
      if (reset == 1'b0) begin
        decBits <= {64{1'b0}};
      end
      else begin
        if (enb) begin
          if (frameVld == 1'b1) begin
            decBits <= {64{1'b0}};
          end
          else begin
            decBits <= decData_1;
          end
        end
      end
    end

  assign out0_0 = decBits[0];

  assign out0_1 = decBits[1];

  assign out0_2 = decBits[2];

  assign out0_3 = decBits[3];

  assign out0_4 = decBits[4];

  assign out0_5 = decBits[5];

  assign out0_6 = decBits[6];

  assign out0_7 = decBits[7];

  assign out0_8 = decBits[8];

  assign out0_9 = decBits[9];

  assign out0_10 = decBits[10];

  assign out0_11 = decBits[11];

  assign out0_12 = decBits[12];

  assign out0_13 = decBits[13];

  assign out0_14 = decBits[14];

  assign out0_15 = decBits[15];

  assign out0_16 = decBits[16];

  assign out0_17 = decBits[17];

  assign out0_18 = decBits[18];

  assign out0_19 = decBits[19];

  assign out0_20 = decBits[20];

  assign out0_21 = decBits[21];

  assign out0_22 = decBits[22];

  assign out0_23 = decBits[23];

  assign out0_24 = decBits[24];

  assign out0_25 = decBits[25];

  assign out0_26 = decBits[26];

  assign out0_27 = decBits[27];

  assign out0_28 = decBits[28];

  assign out0_29 = decBits[29];

  assign out0_30 = decBits[30];

  assign out0_31 = decBits[31];

  assign out0_32 = decBits[32];

  assign out0_33 = decBits[33];

  assign out0_34 = decBits[34];

  assign out0_35 = decBits[35];

  assign out0_36 = decBits[36];

  assign out0_37 = decBits[37];

  assign out0_38 = decBits[38];

  assign out0_39 = decBits[39];

  assign out0_40 = decBits[40];

  assign out0_41 = decBits[41];

  assign out0_42 = decBits[42];

  assign out0_43 = decBits[43];

  assign out0_44 = decBits[44];

  assign out0_45 = decBits[45];

  assign out0_46 = decBits[46];

  assign out0_47 = decBits[47];

  assign out0_48 = decBits[48];

  assign out0_49 = decBits[49];

  assign out0_50 = decBits[50];

  assign out0_51 = decBits[51];

  assign out0_52 = decBits[52];

  assign out0_53 = decBits[53];

  assign out0_54 = decBits[54];

  assign out0_55 = decBits[55];

  assign out0_56 = decBits[56];

  assign out0_57 = decBits[57];

  assign out0_58 = decBits[58];

  assign out0_59 = decBits[59];

  assign out0_60 = decBits[60];

  assign out0_61 = decBits[61];

  assign out0_62 = decBits[62];

  assign out0_63 = decBits[63];

  always @(posedge clk or negedge reset)
    begin : c_11_process
      if (reset == 1'b0) begin
        startReg <= 1'b0;
      end
      else begin
        if (enb) begin
          startReg <= startOutReg;
        end
      end
    end

  assign startReg_1 = (nextFrame_1 == 1'b0 ? startReg :
              const0);

  always @(posedge clk or negedge reset)
    begin : startOut_process
      if (reset == 1'b0) begin
        startOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (frameVld == 1'b1) begin
            startOut_1 <= 1'b0;
          end
          else begin
            startOut_1 <= startReg_1;
          end
        end
      end
    end

  assign out1_start = startOut_1;

  assign out1_end = endOut_1;

  assign out1_valid = validOut_1;

  assign startOutVld = startReg & startReg;

  assign enbZ = (nextFrame_1 == 1'b0 ? startOutVld :
              const0);

  always @(posedge clk or negedge reset)
    begin : c_12_process
      if (reset == 1'b0) begin
        frameVldReg <= 1'b0;
      end
      else begin
        if (enb) begin
          frameVldReg <= frameVld;
        end
      end
    end

  assign zReset = endOutVldReg | frameVldReg;

  assign Z_dtc_2 = {7'b0, shiftReg};

  always @(posedge clk or negedge reset)
    begin : lifting_Size_process
      if (reset == 1'b0) begin
        lifting_Size_switch_delay <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          if (zReset == 1'b1) begin
            lifting_Size_switch_delay <= 16'b0000000000000000;
          end
          else begin
            if (enbZ) begin
              lifting_Size_switch_delay <= Z_dtc_2;
            end
          end
        end
      end
    end

  assign liftSize = (zReset == 1'b1 ? 16'b0000000000000000 :
              lifting_Size_switch_delay);

  assign out2 = liftSize;

  assign out3 = nextFrame_1;

endmodule  // dec_NR_LDPC_Decoder

