// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRLDPCDecoderHDL\dec_FinalDecision.v
// Created: 2026-06-03 20:20:02
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec_FinalDecision
// Source Path: NRLDPCDecoderHDL/HDL Algorithm/NR LDPC Decoder/DecoderCore/FinalDecision
// Hierarchy Level: 3
// Model version: 10.1
// 
// Final Decision
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec_FinalDecision
          (clk,
           reset,
           enb,
           data_0,
           data_1,
           data_2,
           data_3,
           data_4,
           data_5,
           data_6,
           data_7,
           data_8,
           data_9,
           data_10,
           data_11,
           data_12,
           data_13,
           data_14,
           data_15,
           data_16,
           data_17,
           data_18,
           data_19,
           data_20,
           data_21,
           data_22,
           data_23,
           data_24,
           data_25,
           data_26,
           data_27,
           data_28,
           data_29,
           data_30,
           data_31,
           data_32,
           data_33,
           data_34,
           data_35,
           data_36,
           data_37,
           data_38,
           data_39,
           data_40,
           data_41,
           data_42,
           data_43,
           data_44,
           data_45,
           data_46,
           data_47,
           data_48,
           data_49,
           data_50,
           data_51,
           data_52,
           data_53,
           data_54,
           data_55,
           data_56,
           data_57,
           data_58,
           data_59,
           data_60,
           data_61,
           data_62,
           data_63,
           data_64,
           data_65,
           data_66,
           data_67,
           data_68,
           data_69,
           data_70,
           data_71,
           data_72,
           data_73,
           data_74,
           data_75,
           data_76,
           data_77,
           data_78,
           data_79,
           data_80,
           data_81,
           data_82,
           data_83,
           data_84,
           data_85,
           data_86,
           data_87,
           data_88,
           data_89,
           data_90,
           data_91,
           data_92,
           data_93,
           data_94,
           data_95,
           data_96,
           data_97,
           data_98,
           data_99,
           data_100,
           data_101,
           data_102,
           data_103,
           data_104,
           data_105,
           data_106,
           data_107,
           data_108,
           data_109,
           data_110,
           data_111,
           data_112,
           data_113,
           data_114,
           data_115,
           data_116,
           data_117,
           data_118,
           data_119,
           data_120,
           data_121,
           data_122,
           data_123,
           data_124,
           data_125,
           data_126,
           data_127,
           data_128,
           data_129,
           data_130,
           data_131,
           data_132,
           data_133,
           data_134,
           data_135,
           data_136,
           data_137,
           data_138,
           data_139,
           data_140,
           data_141,
           data_142,
           data_143,
           data_144,
           data_145,
           data_146,
           data_147,
           data_148,
           data_149,
           data_150,
           data_151,
           data_152,
           data_153,
           data_154,
           data_155,
           data_156,
           data_157,
           data_158,
           data_159,
           data_160,
           data_161,
           data_162,
           data_163,
           data_164,
           data_165,
           data_166,
           data_167,
           data_168,
           data_169,
           data_170,
           data_171,
           data_172,
           data_173,
           data_174,
           data_175,
           data_176,
           data_177,
           data_178,
           data_179,
           data_180,
           data_181,
           data_182,
           data_183,
           data_184,
           data_185,
           data_186,
           data_187,
           data_188,
           data_189,
           data_190,
           data_191,
           data_192,
           data_193,
           data_194,
           data_195,
           data_196,
           data_197,
           data_198,
           data_199,
           data_200,
           data_201,
           data_202,
           data_203,
           data_204,
           data_205,
           data_206,
           data_207,
           data_208,
           data_209,
           data_210,
           data_211,
           data_212,
           data_213,
           data_214,
           data_215,
           data_216,
           data_217,
           data_218,
           data_219,
           data_220,
           data_221,
           data_222,
           data_223,
           data_224,
           data_225,
           data_226,
           data_227,
           data_228,
           data_229,
           data_230,
           data_231,
           data_232,
           data_233,
           data_234,
           data_235,
           data_236,
           data_237,
           data_238,
           data_239,
           data_240,
           data_241,
           data_242,
           data_243,
           data_244,
           data_245,
           data_246,
           data_247,
           data_248,
           data_249,
           data_250,
           data_251,
           data_252,
           data_253,
           data_254,
           data_255,
           data_256,
           data_257,
           data_258,
           data_259,
           data_260,
           data_261,
           data_262,
           data_263,
           data_264,
           data_265,
           data_266,
           data_267,
           data_268,
           data_269,
           data_270,
           data_271,
           data_272,
           data_273,
           data_274,
           data_275,
           data_276,
           data_277,
           data_278,
           data_279,
           data_280,
           data_281,
           data_282,
           data_283,
           data_284,
           data_285,
           data_286,
           data_287,
           data_288,
           data_289,
           data_290,
           data_291,
           data_292,
           data_293,
           data_294,
           data_295,
           data_296,
           data_297,
           data_298,
           data_299,
           data_300,
           data_301,
           data_302,
           data_303,
           data_304,
           data_305,
           data_306,
           data_307,
           data_308,
           data_309,
           data_310,
           data_311,
           data_312,
           data_313,
           data_314,
           data_315,
           data_316,
           data_317,
           data_318,
           data_319,
           data_320,
           data_321,
           data_322,
           data_323,
           data_324,
           data_325,
           data_326,
           data_327,
           data_328,
           data_329,
           data_330,
           data_331,
           data_332,
           data_333,
           data_334,
           data_335,
           data_336,
           data_337,
           data_338,
           data_339,
           data_340,
           data_341,
           data_342,
           data_343,
           data_344,
           data_345,
           data_346,
           data_347,
           data_348,
           data_349,
           data_350,
           data_351,
           data_352,
           data_353,
           data_354,
           data_355,
           data_356,
           data_357,
           data_358,
           data_359,
           data_360,
           data_361,
           data_362,
           data_363,
           data_364,
           data_365,
           data_366,
           data_367,
           data_368,
           data_369,
           data_370,
           data_371,
           data_372,
           data_373,
           data_374,
           data_375,
           data_376,
           data_377,
           data_378,
           data_379,
           data_380,
           data_381,
           data_382,
           data_383,
           iterdone,
           liftsize,
           bgn,
           fin_shift_0,
           fin_shift_1,
           fin_shift_2,
           fin_shift_3,
           fin_shift_4,
           fin_shift_5,
           fin_shift_6,
           fin_shift_7,
           fin_shift_8,
           fin_shift_9,
           fin_shift_10,
           fin_shift_11,
           fin_shift_12,
           fin_shift_13,
           fin_shift_14,
           fin_shift_15,
           fin_shift_16,
           fin_shift_17,
           fin_shift_18,
           fin_shift_19,
           fin_shift_20,
           fin_shift_21,
           reset_1,
           decbits_0,
           decbits_1,
           decbits_2,
           decbits_3,
           decbits_4,
           decbits_5,
           decbits_6,
           decbits_7,
           decbits_8,
           decbits_9,
           decbits_10,
           decbits_11,
           decbits_12,
           decbits_13,
           decbits_14,
           decbits_15,
           decbits_16,
           decbits_17,
           decbits_18,
           decbits_19,
           decbits_20,
           decbits_21,
           decbits_22,
           decbits_23,
           decbits_24,
           decbits_25,
           decbits_26,
           decbits_27,
           decbits_28,
           decbits_29,
           decbits_30,
           decbits_31,
           decbits_32,
           decbits_33,
           decbits_34,
           decbits_35,
           decbits_36,
           decbits_37,
           decbits_38,
           decbits_39,
           decbits_40,
           decbits_41,
           decbits_42,
           decbits_43,
           decbits_44,
           decbits_45,
           decbits_46,
           decbits_47,
           decbits_48,
           decbits_49,
           decbits_50,
           decbits_51,
           decbits_52,
           decbits_53,
           decbits_54,
           decbits_55,
           decbits_56,
           decbits_57,
           decbits_58,
           decbits_59,
           decbits_60,
           decbits_61,
           decbits_62,
           decbits_63,
           decbits_64,
           decbits_65,
           decbits_66,
           decbits_67,
           decbits_68,
           decbits_69,
           decbits_70,
           decbits_71,
           decbits_72,
           decbits_73,
           decbits_74,
           decbits_75,
           decbits_76,
           decbits_77,
           decbits_78,
           decbits_79,
           decbits_80,
           decbits_81,
           decbits_82,
           decbits_83,
           decbits_84,
           decbits_85,
           decbits_86,
           decbits_87,
           decbits_88,
           decbits_89,
           decbits_90,
           decbits_91,
           decbits_92,
           decbits_93,
           decbits_94,
           decbits_95,
           decbits_96,
           decbits_97,
           decbits_98,
           decbits_99,
           decbits_100,
           decbits_101,
           decbits_102,
           decbits_103,
           decbits_104,
           decbits_105,
           decbits_106,
           decbits_107,
           decbits_108,
           decbits_109,
           decbits_110,
           decbits_111,
           decbits_112,
           decbits_113,
           decbits_114,
           decbits_115,
           decbits_116,
           decbits_117,
           decbits_118,
           decbits_119,
           decbits_120,
           decbits_121,
           decbits_122,
           decbits_123,
           decbits_124,
           decbits_125,
           decbits_126,
           decbits_127,
           decbits_128,
           decbits_129,
           decbits_130,
           decbits_131,
           decbits_132,
           decbits_133,
           decbits_134,
           decbits_135,
           decbits_136,
           decbits_137,
           decbits_138,
           decbits_139,
           decbits_140,
           decbits_141,
           decbits_142,
           decbits_143,
           decbits_144,
           decbits_145,
           decbits_146,
           decbits_147,
           decbits_148,
           decbits_149,
           decbits_150,
           decbits_151,
           decbits_152,
           decbits_153,
           decbits_154,
           decbits_155,
           decbits_156,
           decbits_157,
           decbits_158,
           decbits_159,
           decbits_160,
           decbits_161,
           decbits_162,
           decbits_163,
           decbits_164,
           decbits_165,
           decbits_166,
           decbits_167,
           decbits_168,
           decbits_169,
           decbits_170,
           decbits_171,
           decbits_172,
           decbits_173,
           decbits_174,
           decbits_175,
           decbits_176,
           decbits_177,
           decbits_178,
           decbits_179,
           decbits_180,
           decbits_181,
           decbits_182,
           decbits_183,
           decbits_184,
           decbits_185,
           decbits_186,
           decbits_187,
           decbits_188,
           decbits_189,
           decbits_190,
           decbits_191,
           decbits_192,
           decbits_193,
           decbits_194,
           decbits_195,
           decbits_196,
           decbits_197,
           decbits_198,
           decbits_199,
           decbits_200,
           decbits_201,
           decbits_202,
           decbits_203,
           decbits_204,
           decbits_205,
           decbits_206,
           decbits_207,
           decbits_208,
           decbits_209,
           decbits_210,
           decbits_211,
           decbits_212,
           decbits_213,
           decbits_214,
           decbits_215,
           decbits_216,
           decbits_217,
           decbits_218,
           decbits_219,
           decbits_220,
           decbits_221,
           decbits_222,
           decbits_223,
           decbits_224,
           decbits_225,
           decbits_226,
           decbits_227,
           decbits_228,
           decbits_229,
           decbits_230,
           decbits_231,
           decbits_232,
           decbits_233,
           decbits_234,
           decbits_235,
           decbits_236,
           decbits_237,
           decbits_238,
           decbits_239,
           decbits_240,
           decbits_241,
           decbits_242,
           decbits_243,
           decbits_244,
           decbits_245,
           decbits_246,
           decbits_247,
           decbits_248,
           decbits_249,
           decbits_250,
           decbits_251,
           decbits_252,
           decbits_253,
           decbits_254,
           decbits_255,
           decbits_256,
           decbits_257,
           decbits_258,
           decbits_259,
           decbits_260,
           decbits_261,
           decbits_262,
           decbits_263,
           decbits_264,
           decbits_265,
           decbits_266,
           decbits_267,
           decbits_268,
           decbits_269,
           decbits_270,
           decbits_271,
           decbits_272,
           decbits_273,
           decbits_274,
           decbits_275,
           decbits_276,
           decbits_277,
           decbits_278,
           decbits_279,
           decbits_280,
           decbits_281,
           decbits_282,
           decbits_283,
           decbits_284,
           decbits_285,
           decbits_286,
           decbits_287,
           decbits_288,
           decbits_289,
           decbits_290,
           decbits_291,
           decbits_292,
           decbits_293,
           decbits_294,
           decbits_295,
           decbits_296,
           decbits_297,
           decbits_298,
           decbits_299,
           decbits_300,
           decbits_301,
           decbits_302,
           decbits_303,
           decbits_304,
           decbits_305,
           decbits_306,
           decbits_307,
           decbits_308,
           decbits_309,
           decbits_310,
           decbits_311,
           decbits_312,
           decbits_313,
           decbits_314,
           decbits_315,
           decbits_316,
           decbits_317,
           decbits_318,
           decbits_319,
           decbits_320,
           decbits_321,
           decbits_322,
           decbits_323,
           decbits_324,
           decbits_325,
           decbits_326,
           decbits_327,
           decbits_328,
           decbits_329,
           decbits_330,
           decbits_331,
           decbits_332,
           decbits_333,
           decbits_334,
           decbits_335,
           decbits_336,
           decbits_337,
           decbits_338,
           decbits_339,
           decbits_340,
           decbits_341,
           decbits_342,
           decbits_343,
           decbits_344,
           decbits_345,
           decbits_346,
           decbits_347,
           decbits_348,
           decbits_349,
           decbits_350,
           decbits_351,
           decbits_352,
           decbits_353,
           decbits_354,
           decbits_355,
           decbits_356,
           decbits_357,
           decbits_358,
           decbits_359,
           decbits_360,
           decbits_361,
           decbits_362,
           decbits_363,
           decbits_364,
           decbits_365,
           decbits_366,
           decbits_367,
           decbits_368,
           decbits_369,
           decbits_370,
           decbits_371,
           decbits_372,
           decbits_373,
           decbits_374,
           decbits_375,
           decbits_376,
           decbits_377,
           decbits_378,
           decbits_379,
           decbits_380,
           decbits_381,
           decbits_382,
           decbits_383,
           start,
           end_rsvd,
           valid,
           shift);


  input   clk;
  input   reset;
  input   enb;
  input   signed [9:0] data_0;  // sfix10_En4
  input   signed [9:0] data_1;  // sfix10_En4
  input   signed [9:0] data_2;  // sfix10_En4
  input   signed [9:0] data_3;  // sfix10_En4
  input   signed [9:0] data_4;  // sfix10_En4
  input   signed [9:0] data_5;  // sfix10_En4
  input   signed [9:0] data_6;  // sfix10_En4
  input   signed [9:0] data_7;  // sfix10_En4
  input   signed [9:0] data_8;  // sfix10_En4
  input   signed [9:0] data_9;  // sfix10_En4
  input   signed [9:0] data_10;  // sfix10_En4
  input   signed [9:0] data_11;  // sfix10_En4
  input   signed [9:0] data_12;  // sfix10_En4
  input   signed [9:0] data_13;  // sfix10_En4
  input   signed [9:0] data_14;  // sfix10_En4
  input   signed [9:0] data_15;  // sfix10_En4
  input   signed [9:0] data_16;  // sfix10_En4
  input   signed [9:0] data_17;  // sfix10_En4
  input   signed [9:0] data_18;  // sfix10_En4
  input   signed [9:0] data_19;  // sfix10_En4
  input   signed [9:0] data_20;  // sfix10_En4
  input   signed [9:0] data_21;  // sfix10_En4
  input   signed [9:0] data_22;  // sfix10_En4
  input   signed [9:0] data_23;  // sfix10_En4
  input   signed [9:0] data_24;  // sfix10_En4
  input   signed [9:0] data_25;  // sfix10_En4
  input   signed [9:0] data_26;  // sfix10_En4
  input   signed [9:0] data_27;  // sfix10_En4
  input   signed [9:0] data_28;  // sfix10_En4
  input   signed [9:0] data_29;  // sfix10_En4
  input   signed [9:0] data_30;  // sfix10_En4
  input   signed [9:0] data_31;  // sfix10_En4
  input   signed [9:0] data_32;  // sfix10_En4
  input   signed [9:0] data_33;  // sfix10_En4
  input   signed [9:0] data_34;  // sfix10_En4
  input   signed [9:0] data_35;  // sfix10_En4
  input   signed [9:0] data_36;  // sfix10_En4
  input   signed [9:0] data_37;  // sfix10_En4
  input   signed [9:0] data_38;  // sfix10_En4
  input   signed [9:0] data_39;  // sfix10_En4
  input   signed [9:0] data_40;  // sfix10_En4
  input   signed [9:0] data_41;  // sfix10_En4
  input   signed [9:0] data_42;  // sfix10_En4
  input   signed [9:0] data_43;  // sfix10_En4
  input   signed [9:0] data_44;  // sfix10_En4
  input   signed [9:0] data_45;  // sfix10_En4
  input   signed [9:0] data_46;  // sfix10_En4
  input   signed [9:0] data_47;  // sfix10_En4
  input   signed [9:0] data_48;  // sfix10_En4
  input   signed [9:0] data_49;  // sfix10_En4
  input   signed [9:0] data_50;  // sfix10_En4
  input   signed [9:0] data_51;  // sfix10_En4
  input   signed [9:0] data_52;  // sfix10_En4
  input   signed [9:0] data_53;  // sfix10_En4
  input   signed [9:0] data_54;  // sfix10_En4
  input   signed [9:0] data_55;  // sfix10_En4
  input   signed [9:0] data_56;  // sfix10_En4
  input   signed [9:0] data_57;  // sfix10_En4
  input   signed [9:0] data_58;  // sfix10_En4
  input   signed [9:0] data_59;  // sfix10_En4
  input   signed [9:0] data_60;  // sfix10_En4
  input   signed [9:0] data_61;  // sfix10_En4
  input   signed [9:0] data_62;  // sfix10_En4
  input   signed [9:0] data_63;  // sfix10_En4
  input   signed [9:0] data_64;  // sfix10_En4
  input   signed [9:0] data_65;  // sfix10_En4
  input   signed [9:0] data_66;  // sfix10_En4
  input   signed [9:0] data_67;  // sfix10_En4
  input   signed [9:0] data_68;  // sfix10_En4
  input   signed [9:0] data_69;  // sfix10_En4
  input   signed [9:0] data_70;  // sfix10_En4
  input   signed [9:0] data_71;  // sfix10_En4
  input   signed [9:0] data_72;  // sfix10_En4
  input   signed [9:0] data_73;  // sfix10_En4
  input   signed [9:0] data_74;  // sfix10_En4
  input   signed [9:0] data_75;  // sfix10_En4
  input   signed [9:0] data_76;  // sfix10_En4
  input   signed [9:0] data_77;  // sfix10_En4
  input   signed [9:0] data_78;  // sfix10_En4
  input   signed [9:0] data_79;  // sfix10_En4
  input   signed [9:0] data_80;  // sfix10_En4
  input   signed [9:0] data_81;  // sfix10_En4
  input   signed [9:0] data_82;  // sfix10_En4
  input   signed [9:0] data_83;  // sfix10_En4
  input   signed [9:0] data_84;  // sfix10_En4
  input   signed [9:0] data_85;  // sfix10_En4
  input   signed [9:0] data_86;  // sfix10_En4
  input   signed [9:0] data_87;  // sfix10_En4
  input   signed [9:0] data_88;  // sfix10_En4
  input   signed [9:0] data_89;  // sfix10_En4
  input   signed [9:0] data_90;  // sfix10_En4
  input   signed [9:0] data_91;  // sfix10_En4
  input   signed [9:0] data_92;  // sfix10_En4
  input   signed [9:0] data_93;  // sfix10_En4
  input   signed [9:0] data_94;  // sfix10_En4
  input   signed [9:0] data_95;  // sfix10_En4
  input   signed [9:0] data_96;  // sfix10_En4
  input   signed [9:0] data_97;  // sfix10_En4
  input   signed [9:0] data_98;  // sfix10_En4
  input   signed [9:0] data_99;  // sfix10_En4
  input   signed [9:0] data_100;  // sfix10_En4
  input   signed [9:0] data_101;  // sfix10_En4
  input   signed [9:0] data_102;  // sfix10_En4
  input   signed [9:0] data_103;  // sfix10_En4
  input   signed [9:0] data_104;  // sfix10_En4
  input   signed [9:0] data_105;  // sfix10_En4
  input   signed [9:0] data_106;  // sfix10_En4
  input   signed [9:0] data_107;  // sfix10_En4
  input   signed [9:0] data_108;  // sfix10_En4
  input   signed [9:0] data_109;  // sfix10_En4
  input   signed [9:0] data_110;  // sfix10_En4
  input   signed [9:0] data_111;  // sfix10_En4
  input   signed [9:0] data_112;  // sfix10_En4
  input   signed [9:0] data_113;  // sfix10_En4
  input   signed [9:0] data_114;  // sfix10_En4
  input   signed [9:0] data_115;  // sfix10_En4
  input   signed [9:0] data_116;  // sfix10_En4
  input   signed [9:0] data_117;  // sfix10_En4
  input   signed [9:0] data_118;  // sfix10_En4
  input   signed [9:0] data_119;  // sfix10_En4
  input   signed [9:0] data_120;  // sfix10_En4
  input   signed [9:0] data_121;  // sfix10_En4
  input   signed [9:0] data_122;  // sfix10_En4
  input   signed [9:0] data_123;  // sfix10_En4
  input   signed [9:0] data_124;  // sfix10_En4
  input   signed [9:0] data_125;  // sfix10_En4
  input   signed [9:0] data_126;  // sfix10_En4
  input   signed [9:0] data_127;  // sfix10_En4
  input   signed [9:0] data_128;  // sfix10_En4
  input   signed [9:0] data_129;  // sfix10_En4
  input   signed [9:0] data_130;  // sfix10_En4
  input   signed [9:0] data_131;  // sfix10_En4
  input   signed [9:0] data_132;  // sfix10_En4
  input   signed [9:0] data_133;  // sfix10_En4
  input   signed [9:0] data_134;  // sfix10_En4
  input   signed [9:0] data_135;  // sfix10_En4
  input   signed [9:0] data_136;  // sfix10_En4
  input   signed [9:0] data_137;  // sfix10_En4
  input   signed [9:0] data_138;  // sfix10_En4
  input   signed [9:0] data_139;  // sfix10_En4
  input   signed [9:0] data_140;  // sfix10_En4
  input   signed [9:0] data_141;  // sfix10_En4
  input   signed [9:0] data_142;  // sfix10_En4
  input   signed [9:0] data_143;  // sfix10_En4
  input   signed [9:0] data_144;  // sfix10_En4
  input   signed [9:0] data_145;  // sfix10_En4
  input   signed [9:0] data_146;  // sfix10_En4
  input   signed [9:0] data_147;  // sfix10_En4
  input   signed [9:0] data_148;  // sfix10_En4
  input   signed [9:0] data_149;  // sfix10_En4
  input   signed [9:0] data_150;  // sfix10_En4
  input   signed [9:0] data_151;  // sfix10_En4
  input   signed [9:0] data_152;  // sfix10_En4
  input   signed [9:0] data_153;  // sfix10_En4
  input   signed [9:0] data_154;  // sfix10_En4
  input   signed [9:0] data_155;  // sfix10_En4
  input   signed [9:0] data_156;  // sfix10_En4
  input   signed [9:0] data_157;  // sfix10_En4
  input   signed [9:0] data_158;  // sfix10_En4
  input   signed [9:0] data_159;  // sfix10_En4
  input   signed [9:0] data_160;  // sfix10_En4
  input   signed [9:0] data_161;  // sfix10_En4
  input   signed [9:0] data_162;  // sfix10_En4
  input   signed [9:0] data_163;  // sfix10_En4
  input   signed [9:0] data_164;  // sfix10_En4
  input   signed [9:0] data_165;  // sfix10_En4
  input   signed [9:0] data_166;  // sfix10_En4
  input   signed [9:0] data_167;  // sfix10_En4
  input   signed [9:0] data_168;  // sfix10_En4
  input   signed [9:0] data_169;  // sfix10_En4
  input   signed [9:0] data_170;  // sfix10_En4
  input   signed [9:0] data_171;  // sfix10_En4
  input   signed [9:0] data_172;  // sfix10_En4
  input   signed [9:0] data_173;  // sfix10_En4
  input   signed [9:0] data_174;  // sfix10_En4
  input   signed [9:0] data_175;  // sfix10_En4
  input   signed [9:0] data_176;  // sfix10_En4
  input   signed [9:0] data_177;  // sfix10_En4
  input   signed [9:0] data_178;  // sfix10_En4
  input   signed [9:0] data_179;  // sfix10_En4
  input   signed [9:0] data_180;  // sfix10_En4
  input   signed [9:0] data_181;  // sfix10_En4
  input   signed [9:0] data_182;  // sfix10_En4
  input   signed [9:0] data_183;  // sfix10_En4
  input   signed [9:0] data_184;  // sfix10_En4
  input   signed [9:0] data_185;  // sfix10_En4
  input   signed [9:0] data_186;  // sfix10_En4
  input   signed [9:0] data_187;  // sfix10_En4
  input   signed [9:0] data_188;  // sfix10_En4
  input   signed [9:0] data_189;  // sfix10_En4
  input   signed [9:0] data_190;  // sfix10_En4
  input   signed [9:0] data_191;  // sfix10_En4
  input   signed [9:0] data_192;  // sfix10_En4
  input   signed [9:0] data_193;  // sfix10_En4
  input   signed [9:0] data_194;  // sfix10_En4
  input   signed [9:0] data_195;  // sfix10_En4
  input   signed [9:0] data_196;  // sfix10_En4
  input   signed [9:0] data_197;  // sfix10_En4
  input   signed [9:0] data_198;  // sfix10_En4
  input   signed [9:0] data_199;  // sfix10_En4
  input   signed [9:0] data_200;  // sfix10_En4
  input   signed [9:0] data_201;  // sfix10_En4
  input   signed [9:0] data_202;  // sfix10_En4
  input   signed [9:0] data_203;  // sfix10_En4
  input   signed [9:0] data_204;  // sfix10_En4
  input   signed [9:0] data_205;  // sfix10_En4
  input   signed [9:0] data_206;  // sfix10_En4
  input   signed [9:0] data_207;  // sfix10_En4
  input   signed [9:0] data_208;  // sfix10_En4
  input   signed [9:0] data_209;  // sfix10_En4
  input   signed [9:0] data_210;  // sfix10_En4
  input   signed [9:0] data_211;  // sfix10_En4
  input   signed [9:0] data_212;  // sfix10_En4
  input   signed [9:0] data_213;  // sfix10_En4
  input   signed [9:0] data_214;  // sfix10_En4
  input   signed [9:0] data_215;  // sfix10_En4
  input   signed [9:0] data_216;  // sfix10_En4
  input   signed [9:0] data_217;  // sfix10_En4
  input   signed [9:0] data_218;  // sfix10_En4
  input   signed [9:0] data_219;  // sfix10_En4
  input   signed [9:0] data_220;  // sfix10_En4
  input   signed [9:0] data_221;  // sfix10_En4
  input   signed [9:0] data_222;  // sfix10_En4
  input   signed [9:0] data_223;  // sfix10_En4
  input   signed [9:0] data_224;  // sfix10_En4
  input   signed [9:0] data_225;  // sfix10_En4
  input   signed [9:0] data_226;  // sfix10_En4
  input   signed [9:0] data_227;  // sfix10_En4
  input   signed [9:0] data_228;  // sfix10_En4
  input   signed [9:0] data_229;  // sfix10_En4
  input   signed [9:0] data_230;  // sfix10_En4
  input   signed [9:0] data_231;  // sfix10_En4
  input   signed [9:0] data_232;  // sfix10_En4
  input   signed [9:0] data_233;  // sfix10_En4
  input   signed [9:0] data_234;  // sfix10_En4
  input   signed [9:0] data_235;  // sfix10_En4
  input   signed [9:0] data_236;  // sfix10_En4
  input   signed [9:0] data_237;  // sfix10_En4
  input   signed [9:0] data_238;  // sfix10_En4
  input   signed [9:0] data_239;  // sfix10_En4
  input   signed [9:0] data_240;  // sfix10_En4
  input   signed [9:0] data_241;  // sfix10_En4
  input   signed [9:0] data_242;  // sfix10_En4
  input   signed [9:0] data_243;  // sfix10_En4
  input   signed [9:0] data_244;  // sfix10_En4
  input   signed [9:0] data_245;  // sfix10_En4
  input   signed [9:0] data_246;  // sfix10_En4
  input   signed [9:0] data_247;  // sfix10_En4
  input   signed [9:0] data_248;  // sfix10_En4
  input   signed [9:0] data_249;  // sfix10_En4
  input   signed [9:0] data_250;  // sfix10_En4
  input   signed [9:0] data_251;  // sfix10_En4
  input   signed [9:0] data_252;  // sfix10_En4
  input   signed [9:0] data_253;  // sfix10_En4
  input   signed [9:0] data_254;  // sfix10_En4
  input   signed [9:0] data_255;  // sfix10_En4
  input   signed [9:0] data_256;  // sfix10_En4
  input   signed [9:0] data_257;  // sfix10_En4
  input   signed [9:0] data_258;  // sfix10_En4
  input   signed [9:0] data_259;  // sfix10_En4
  input   signed [9:0] data_260;  // sfix10_En4
  input   signed [9:0] data_261;  // sfix10_En4
  input   signed [9:0] data_262;  // sfix10_En4
  input   signed [9:0] data_263;  // sfix10_En4
  input   signed [9:0] data_264;  // sfix10_En4
  input   signed [9:0] data_265;  // sfix10_En4
  input   signed [9:0] data_266;  // sfix10_En4
  input   signed [9:0] data_267;  // sfix10_En4
  input   signed [9:0] data_268;  // sfix10_En4
  input   signed [9:0] data_269;  // sfix10_En4
  input   signed [9:0] data_270;  // sfix10_En4
  input   signed [9:0] data_271;  // sfix10_En4
  input   signed [9:0] data_272;  // sfix10_En4
  input   signed [9:0] data_273;  // sfix10_En4
  input   signed [9:0] data_274;  // sfix10_En4
  input   signed [9:0] data_275;  // sfix10_En4
  input   signed [9:0] data_276;  // sfix10_En4
  input   signed [9:0] data_277;  // sfix10_En4
  input   signed [9:0] data_278;  // sfix10_En4
  input   signed [9:0] data_279;  // sfix10_En4
  input   signed [9:0] data_280;  // sfix10_En4
  input   signed [9:0] data_281;  // sfix10_En4
  input   signed [9:0] data_282;  // sfix10_En4
  input   signed [9:0] data_283;  // sfix10_En4
  input   signed [9:0] data_284;  // sfix10_En4
  input   signed [9:0] data_285;  // sfix10_En4
  input   signed [9:0] data_286;  // sfix10_En4
  input   signed [9:0] data_287;  // sfix10_En4
  input   signed [9:0] data_288;  // sfix10_En4
  input   signed [9:0] data_289;  // sfix10_En4
  input   signed [9:0] data_290;  // sfix10_En4
  input   signed [9:0] data_291;  // sfix10_En4
  input   signed [9:0] data_292;  // sfix10_En4
  input   signed [9:0] data_293;  // sfix10_En4
  input   signed [9:0] data_294;  // sfix10_En4
  input   signed [9:0] data_295;  // sfix10_En4
  input   signed [9:0] data_296;  // sfix10_En4
  input   signed [9:0] data_297;  // sfix10_En4
  input   signed [9:0] data_298;  // sfix10_En4
  input   signed [9:0] data_299;  // sfix10_En4
  input   signed [9:0] data_300;  // sfix10_En4
  input   signed [9:0] data_301;  // sfix10_En4
  input   signed [9:0] data_302;  // sfix10_En4
  input   signed [9:0] data_303;  // sfix10_En4
  input   signed [9:0] data_304;  // sfix10_En4
  input   signed [9:0] data_305;  // sfix10_En4
  input   signed [9:0] data_306;  // sfix10_En4
  input   signed [9:0] data_307;  // sfix10_En4
  input   signed [9:0] data_308;  // sfix10_En4
  input   signed [9:0] data_309;  // sfix10_En4
  input   signed [9:0] data_310;  // sfix10_En4
  input   signed [9:0] data_311;  // sfix10_En4
  input   signed [9:0] data_312;  // sfix10_En4
  input   signed [9:0] data_313;  // sfix10_En4
  input   signed [9:0] data_314;  // sfix10_En4
  input   signed [9:0] data_315;  // sfix10_En4
  input   signed [9:0] data_316;  // sfix10_En4
  input   signed [9:0] data_317;  // sfix10_En4
  input   signed [9:0] data_318;  // sfix10_En4
  input   signed [9:0] data_319;  // sfix10_En4
  input   signed [9:0] data_320;  // sfix10_En4
  input   signed [9:0] data_321;  // sfix10_En4
  input   signed [9:0] data_322;  // sfix10_En4
  input   signed [9:0] data_323;  // sfix10_En4
  input   signed [9:0] data_324;  // sfix10_En4
  input   signed [9:0] data_325;  // sfix10_En4
  input   signed [9:0] data_326;  // sfix10_En4
  input   signed [9:0] data_327;  // sfix10_En4
  input   signed [9:0] data_328;  // sfix10_En4
  input   signed [9:0] data_329;  // sfix10_En4
  input   signed [9:0] data_330;  // sfix10_En4
  input   signed [9:0] data_331;  // sfix10_En4
  input   signed [9:0] data_332;  // sfix10_En4
  input   signed [9:0] data_333;  // sfix10_En4
  input   signed [9:0] data_334;  // sfix10_En4
  input   signed [9:0] data_335;  // sfix10_En4
  input   signed [9:0] data_336;  // sfix10_En4
  input   signed [9:0] data_337;  // sfix10_En4
  input   signed [9:0] data_338;  // sfix10_En4
  input   signed [9:0] data_339;  // sfix10_En4
  input   signed [9:0] data_340;  // sfix10_En4
  input   signed [9:0] data_341;  // sfix10_En4
  input   signed [9:0] data_342;  // sfix10_En4
  input   signed [9:0] data_343;  // sfix10_En4
  input   signed [9:0] data_344;  // sfix10_En4
  input   signed [9:0] data_345;  // sfix10_En4
  input   signed [9:0] data_346;  // sfix10_En4
  input   signed [9:0] data_347;  // sfix10_En4
  input   signed [9:0] data_348;  // sfix10_En4
  input   signed [9:0] data_349;  // sfix10_En4
  input   signed [9:0] data_350;  // sfix10_En4
  input   signed [9:0] data_351;  // sfix10_En4
  input   signed [9:0] data_352;  // sfix10_En4
  input   signed [9:0] data_353;  // sfix10_En4
  input   signed [9:0] data_354;  // sfix10_En4
  input   signed [9:0] data_355;  // sfix10_En4
  input   signed [9:0] data_356;  // sfix10_En4
  input   signed [9:0] data_357;  // sfix10_En4
  input   signed [9:0] data_358;  // sfix10_En4
  input   signed [9:0] data_359;  // sfix10_En4
  input   signed [9:0] data_360;  // sfix10_En4
  input   signed [9:0] data_361;  // sfix10_En4
  input   signed [9:0] data_362;  // sfix10_En4
  input   signed [9:0] data_363;  // sfix10_En4
  input   signed [9:0] data_364;  // sfix10_En4
  input   signed [9:0] data_365;  // sfix10_En4
  input   signed [9:0] data_366;  // sfix10_En4
  input   signed [9:0] data_367;  // sfix10_En4
  input   signed [9:0] data_368;  // sfix10_En4
  input   signed [9:0] data_369;  // sfix10_En4
  input   signed [9:0] data_370;  // sfix10_En4
  input   signed [9:0] data_371;  // sfix10_En4
  input   signed [9:0] data_372;  // sfix10_En4
  input   signed [9:0] data_373;  // sfix10_En4
  input   signed [9:0] data_374;  // sfix10_En4
  input   signed [9:0] data_375;  // sfix10_En4
  input   signed [9:0] data_376;  // sfix10_En4
  input   signed [9:0] data_377;  // sfix10_En4
  input   signed [9:0] data_378;  // sfix10_En4
  input   signed [9:0] data_379;  // sfix10_En4
  input   signed [9:0] data_380;  // sfix10_En4
  input   signed [9:0] data_381;  // sfix10_En4
  input   signed [9:0] data_382;  // sfix10_En4
  input   signed [9:0] data_383;  // sfix10_En4
  input   iterdone;  // ufix1
  input   [8:0] liftsize;  // ufix9
  input   bgn;  // ufix1
  input   [8:0] fin_shift_0;  // ufix9
  input   [8:0] fin_shift_1;  // ufix9
  input   [8:0] fin_shift_2;  // ufix9
  input   [8:0] fin_shift_3;  // ufix9
  input   [8:0] fin_shift_4;  // ufix9
  input   [8:0] fin_shift_5;  // ufix9
  input   [8:0] fin_shift_6;  // ufix9
  input   [8:0] fin_shift_7;  // ufix9
  input   [8:0] fin_shift_8;  // ufix9
  input   [8:0] fin_shift_9;  // ufix9
  input   [8:0] fin_shift_10;  // ufix9
  input   [8:0] fin_shift_11;  // ufix9
  input   [8:0] fin_shift_12;  // ufix9
  input   [8:0] fin_shift_13;  // ufix9
  input   [8:0] fin_shift_14;  // ufix9
  input   [8:0] fin_shift_15;  // ufix9
  input   [8:0] fin_shift_16;  // ufix9
  input   [8:0] fin_shift_17;  // ufix9
  input   [8:0] fin_shift_18;  // ufix9
  input   [8:0] fin_shift_19;  // ufix9
  input   [8:0] fin_shift_20;  // ufix9
  input   [8:0] fin_shift_21;  // ufix9
  input   reset_1;  // ufix1
  output  decbits_0;  // ufix1
  output  decbits_1;  // ufix1
  output  decbits_2;  // ufix1
  output  decbits_3;  // ufix1
  output  decbits_4;  // ufix1
  output  decbits_5;  // ufix1
  output  decbits_6;  // ufix1
  output  decbits_7;  // ufix1
  output  decbits_8;  // ufix1
  output  decbits_9;  // ufix1
  output  decbits_10;  // ufix1
  output  decbits_11;  // ufix1
  output  decbits_12;  // ufix1
  output  decbits_13;  // ufix1
  output  decbits_14;  // ufix1
  output  decbits_15;  // ufix1
  output  decbits_16;  // ufix1
  output  decbits_17;  // ufix1
  output  decbits_18;  // ufix1
  output  decbits_19;  // ufix1
  output  decbits_20;  // ufix1
  output  decbits_21;  // ufix1
  output  decbits_22;  // ufix1
  output  decbits_23;  // ufix1
  output  decbits_24;  // ufix1
  output  decbits_25;  // ufix1
  output  decbits_26;  // ufix1
  output  decbits_27;  // ufix1
  output  decbits_28;  // ufix1
  output  decbits_29;  // ufix1
  output  decbits_30;  // ufix1
  output  decbits_31;  // ufix1
  output  decbits_32;  // ufix1
  output  decbits_33;  // ufix1
  output  decbits_34;  // ufix1
  output  decbits_35;  // ufix1
  output  decbits_36;  // ufix1
  output  decbits_37;  // ufix1
  output  decbits_38;  // ufix1
  output  decbits_39;  // ufix1
  output  decbits_40;  // ufix1
  output  decbits_41;  // ufix1
  output  decbits_42;  // ufix1
  output  decbits_43;  // ufix1
  output  decbits_44;  // ufix1
  output  decbits_45;  // ufix1
  output  decbits_46;  // ufix1
  output  decbits_47;  // ufix1
  output  decbits_48;  // ufix1
  output  decbits_49;  // ufix1
  output  decbits_50;  // ufix1
  output  decbits_51;  // ufix1
  output  decbits_52;  // ufix1
  output  decbits_53;  // ufix1
  output  decbits_54;  // ufix1
  output  decbits_55;  // ufix1
  output  decbits_56;  // ufix1
  output  decbits_57;  // ufix1
  output  decbits_58;  // ufix1
  output  decbits_59;  // ufix1
  output  decbits_60;  // ufix1
  output  decbits_61;  // ufix1
  output  decbits_62;  // ufix1
  output  decbits_63;  // ufix1
  output  decbits_64;  // ufix1
  output  decbits_65;  // ufix1
  output  decbits_66;  // ufix1
  output  decbits_67;  // ufix1
  output  decbits_68;  // ufix1
  output  decbits_69;  // ufix1
  output  decbits_70;  // ufix1
  output  decbits_71;  // ufix1
  output  decbits_72;  // ufix1
  output  decbits_73;  // ufix1
  output  decbits_74;  // ufix1
  output  decbits_75;  // ufix1
  output  decbits_76;  // ufix1
  output  decbits_77;  // ufix1
  output  decbits_78;  // ufix1
  output  decbits_79;  // ufix1
  output  decbits_80;  // ufix1
  output  decbits_81;  // ufix1
  output  decbits_82;  // ufix1
  output  decbits_83;  // ufix1
  output  decbits_84;  // ufix1
  output  decbits_85;  // ufix1
  output  decbits_86;  // ufix1
  output  decbits_87;  // ufix1
  output  decbits_88;  // ufix1
  output  decbits_89;  // ufix1
  output  decbits_90;  // ufix1
  output  decbits_91;  // ufix1
  output  decbits_92;  // ufix1
  output  decbits_93;  // ufix1
  output  decbits_94;  // ufix1
  output  decbits_95;  // ufix1
  output  decbits_96;  // ufix1
  output  decbits_97;  // ufix1
  output  decbits_98;  // ufix1
  output  decbits_99;  // ufix1
  output  decbits_100;  // ufix1
  output  decbits_101;  // ufix1
  output  decbits_102;  // ufix1
  output  decbits_103;  // ufix1
  output  decbits_104;  // ufix1
  output  decbits_105;  // ufix1
  output  decbits_106;  // ufix1
  output  decbits_107;  // ufix1
  output  decbits_108;  // ufix1
  output  decbits_109;  // ufix1
  output  decbits_110;  // ufix1
  output  decbits_111;  // ufix1
  output  decbits_112;  // ufix1
  output  decbits_113;  // ufix1
  output  decbits_114;  // ufix1
  output  decbits_115;  // ufix1
  output  decbits_116;  // ufix1
  output  decbits_117;  // ufix1
  output  decbits_118;  // ufix1
  output  decbits_119;  // ufix1
  output  decbits_120;  // ufix1
  output  decbits_121;  // ufix1
  output  decbits_122;  // ufix1
  output  decbits_123;  // ufix1
  output  decbits_124;  // ufix1
  output  decbits_125;  // ufix1
  output  decbits_126;  // ufix1
  output  decbits_127;  // ufix1
  output  decbits_128;  // ufix1
  output  decbits_129;  // ufix1
  output  decbits_130;  // ufix1
  output  decbits_131;  // ufix1
  output  decbits_132;  // ufix1
  output  decbits_133;  // ufix1
  output  decbits_134;  // ufix1
  output  decbits_135;  // ufix1
  output  decbits_136;  // ufix1
  output  decbits_137;  // ufix1
  output  decbits_138;  // ufix1
  output  decbits_139;  // ufix1
  output  decbits_140;  // ufix1
  output  decbits_141;  // ufix1
  output  decbits_142;  // ufix1
  output  decbits_143;  // ufix1
  output  decbits_144;  // ufix1
  output  decbits_145;  // ufix1
  output  decbits_146;  // ufix1
  output  decbits_147;  // ufix1
  output  decbits_148;  // ufix1
  output  decbits_149;  // ufix1
  output  decbits_150;  // ufix1
  output  decbits_151;  // ufix1
  output  decbits_152;  // ufix1
  output  decbits_153;  // ufix1
  output  decbits_154;  // ufix1
  output  decbits_155;  // ufix1
  output  decbits_156;  // ufix1
  output  decbits_157;  // ufix1
  output  decbits_158;  // ufix1
  output  decbits_159;  // ufix1
  output  decbits_160;  // ufix1
  output  decbits_161;  // ufix1
  output  decbits_162;  // ufix1
  output  decbits_163;  // ufix1
  output  decbits_164;  // ufix1
  output  decbits_165;  // ufix1
  output  decbits_166;  // ufix1
  output  decbits_167;  // ufix1
  output  decbits_168;  // ufix1
  output  decbits_169;  // ufix1
  output  decbits_170;  // ufix1
  output  decbits_171;  // ufix1
  output  decbits_172;  // ufix1
  output  decbits_173;  // ufix1
  output  decbits_174;  // ufix1
  output  decbits_175;  // ufix1
  output  decbits_176;  // ufix1
  output  decbits_177;  // ufix1
  output  decbits_178;  // ufix1
  output  decbits_179;  // ufix1
  output  decbits_180;  // ufix1
  output  decbits_181;  // ufix1
  output  decbits_182;  // ufix1
  output  decbits_183;  // ufix1
  output  decbits_184;  // ufix1
  output  decbits_185;  // ufix1
  output  decbits_186;  // ufix1
  output  decbits_187;  // ufix1
  output  decbits_188;  // ufix1
  output  decbits_189;  // ufix1
  output  decbits_190;  // ufix1
  output  decbits_191;  // ufix1
  output  decbits_192;  // ufix1
  output  decbits_193;  // ufix1
  output  decbits_194;  // ufix1
  output  decbits_195;  // ufix1
  output  decbits_196;  // ufix1
  output  decbits_197;  // ufix1
  output  decbits_198;  // ufix1
  output  decbits_199;  // ufix1
  output  decbits_200;  // ufix1
  output  decbits_201;  // ufix1
  output  decbits_202;  // ufix1
  output  decbits_203;  // ufix1
  output  decbits_204;  // ufix1
  output  decbits_205;  // ufix1
  output  decbits_206;  // ufix1
  output  decbits_207;  // ufix1
  output  decbits_208;  // ufix1
  output  decbits_209;  // ufix1
  output  decbits_210;  // ufix1
  output  decbits_211;  // ufix1
  output  decbits_212;  // ufix1
  output  decbits_213;  // ufix1
  output  decbits_214;  // ufix1
  output  decbits_215;  // ufix1
  output  decbits_216;  // ufix1
  output  decbits_217;  // ufix1
  output  decbits_218;  // ufix1
  output  decbits_219;  // ufix1
  output  decbits_220;  // ufix1
  output  decbits_221;  // ufix1
  output  decbits_222;  // ufix1
  output  decbits_223;  // ufix1
  output  decbits_224;  // ufix1
  output  decbits_225;  // ufix1
  output  decbits_226;  // ufix1
  output  decbits_227;  // ufix1
  output  decbits_228;  // ufix1
  output  decbits_229;  // ufix1
  output  decbits_230;  // ufix1
  output  decbits_231;  // ufix1
  output  decbits_232;  // ufix1
  output  decbits_233;  // ufix1
  output  decbits_234;  // ufix1
  output  decbits_235;  // ufix1
  output  decbits_236;  // ufix1
  output  decbits_237;  // ufix1
  output  decbits_238;  // ufix1
  output  decbits_239;  // ufix1
  output  decbits_240;  // ufix1
  output  decbits_241;  // ufix1
  output  decbits_242;  // ufix1
  output  decbits_243;  // ufix1
  output  decbits_244;  // ufix1
  output  decbits_245;  // ufix1
  output  decbits_246;  // ufix1
  output  decbits_247;  // ufix1
  output  decbits_248;  // ufix1
  output  decbits_249;  // ufix1
  output  decbits_250;  // ufix1
  output  decbits_251;  // ufix1
  output  decbits_252;  // ufix1
  output  decbits_253;  // ufix1
  output  decbits_254;  // ufix1
  output  decbits_255;  // ufix1
  output  decbits_256;  // ufix1
  output  decbits_257;  // ufix1
  output  decbits_258;  // ufix1
  output  decbits_259;  // ufix1
  output  decbits_260;  // ufix1
  output  decbits_261;  // ufix1
  output  decbits_262;  // ufix1
  output  decbits_263;  // ufix1
  output  decbits_264;  // ufix1
  output  decbits_265;  // ufix1
  output  decbits_266;  // ufix1
  output  decbits_267;  // ufix1
  output  decbits_268;  // ufix1
  output  decbits_269;  // ufix1
  output  decbits_270;  // ufix1
  output  decbits_271;  // ufix1
  output  decbits_272;  // ufix1
  output  decbits_273;  // ufix1
  output  decbits_274;  // ufix1
  output  decbits_275;  // ufix1
  output  decbits_276;  // ufix1
  output  decbits_277;  // ufix1
  output  decbits_278;  // ufix1
  output  decbits_279;  // ufix1
  output  decbits_280;  // ufix1
  output  decbits_281;  // ufix1
  output  decbits_282;  // ufix1
  output  decbits_283;  // ufix1
  output  decbits_284;  // ufix1
  output  decbits_285;  // ufix1
  output  decbits_286;  // ufix1
  output  decbits_287;  // ufix1
  output  decbits_288;  // ufix1
  output  decbits_289;  // ufix1
  output  decbits_290;  // ufix1
  output  decbits_291;  // ufix1
  output  decbits_292;  // ufix1
  output  decbits_293;  // ufix1
  output  decbits_294;  // ufix1
  output  decbits_295;  // ufix1
  output  decbits_296;  // ufix1
  output  decbits_297;  // ufix1
  output  decbits_298;  // ufix1
  output  decbits_299;  // ufix1
  output  decbits_300;  // ufix1
  output  decbits_301;  // ufix1
  output  decbits_302;  // ufix1
  output  decbits_303;  // ufix1
  output  decbits_304;  // ufix1
  output  decbits_305;  // ufix1
  output  decbits_306;  // ufix1
  output  decbits_307;  // ufix1
  output  decbits_308;  // ufix1
  output  decbits_309;  // ufix1
  output  decbits_310;  // ufix1
  output  decbits_311;  // ufix1
  output  decbits_312;  // ufix1
  output  decbits_313;  // ufix1
  output  decbits_314;  // ufix1
  output  decbits_315;  // ufix1
  output  decbits_316;  // ufix1
  output  decbits_317;  // ufix1
  output  decbits_318;  // ufix1
  output  decbits_319;  // ufix1
  output  decbits_320;  // ufix1
  output  decbits_321;  // ufix1
  output  decbits_322;  // ufix1
  output  decbits_323;  // ufix1
  output  decbits_324;  // ufix1
  output  decbits_325;  // ufix1
  output  decbits_326;  // ufix1
  output  decbits_327;  // ufix1
  output  decbits_328;  // ufix1
  output  decbits_329;  // ufix1
  output  decbits_330;  // ufix1
  output  decbits_331;  // ufix1
  output  decbits_332;  // ufix1
  output  decbits_333;  // ufix1
  output  decbits_334;  // ufix1
  output  decbits_335;  // ufix1
  output  decbits_336;  // ufix1
  output  decbits_337;  // ufix1
  output  decbits_338;  // ufix1
  output  decbits_339;  // ufix1
  output  decbits_340;  // ufix1
  output  decbits_341;  // ufix1
  output  decbits_342;  // ufix1
  output  decbits_343;  // ufix1
  output  decbits_344;  // ufix1
  output  decbits_345;  // ufix1
  output  decbits_346;  // ufix1
  output  decbits_347;  // ufix1
  output  decbits_348;  // ufix1
  output  decbits_349;  // ufix1
  output  decbits_350;  // ufix1
  output  decbits_351;  // ufix1
  output  decbits_352;  // ufix1
  output  decbits_353;  // ufix1
  output  decbits_354;  // ufix1
  output  decbits_355;  // ufix1
  output  decbits_356;  // ufix1
  output  decbits_357;  // ufix1
  output  decbits_358;  // ufix1
  output  decbits_359;  // ufix1
  output  decbits_360;  // ufix1
  output  decbits_361;  // ufix1
  output  decbits_362;  // ufix1
  output  decbits_363;  // ufix1
  output  decbits_364;  // ufix1
  output  decbits_365;  // ufix1
  output  decbits_366;  // ufix1
  output  decbits_367;  // ufix1
  output  decbits_368;  // ufix1
  output  decbits_369;  // ufix1
  output  decbits_370;  // ufix1
  output  decbits_371;  // ufix1
  output  decbits_372;  // ufix1
  output  decbits_373;  // ufix1
  output  decbits_374;  // ufix1
  output  decbits_375;  // ufix1
  output  decbits_376;  // ufix1
  output  decbits_377;  // ufix1
  output  decbits_378;  // ufix1
  output  decbits_379;  // ufix1
  output  decbits_380;  // ufix1
  output  decbits_381;  // ufix1
  output  decbits_382;  // ufix1
  output  decbits_383;  // ufix1
  output  start;  // ufix1
  output  end_rsvd;  // ufix1
  output  valid;  // ufix1
  output  [8:0] shift;  // ufix9


  wire signed [9:0] data [0:383];  // sfix10_En4 [384]
  reg  finaldecision_enb_dec;
  reg [4:0] finaldecision_count;  // ufix5
  reg  finaldecision_iterDone;
  reg [8:0] finaldecision_zCount1;  // ufix9
  reg [8:0] finaldecision_zCount2;  // ufix9
  reg  finaldecision_cntEnb;
  reg  finaldecision_endD;
  reg  finaldecision_ctrlEnd;
  reg  finaldecision_enb_dec_next;
  reg [4:0] finaldecision_count_next;  // ufix5
  reg  finaldecision_iterDone_next;
  reg [8:0] finaldecision_zCount1_next;  // ufix9
  reg [8:0] finaldecision_zCount2_next;  // ufix9
  reg  finaldecision_cntEnb_next;
  reg  finaldecision_endD_next;
  reg  finaldecision_ctrlEnd_next;
  reg  [383:0] data_384;  // ufix1 [384]
  reg  start_out;  // ufix1
  reg  end_out;  // ufix1
  reg  valid_out;  // ufix1
  reg [4:0] count;  // ufix5
  reg  [383:0] decbits;  // ufix1 [384]
  reg  start_1;  // ufix1
  reg  end_rsvd_1;  // ufix1
  wire [8:0] shift_1;  // ufix9
  reg [8:0] shift_2;  // ufix9
  reg signed [31:0] finaldecision_zcount;  // double
  reg  finaldecision_validi;
  reg  finaldecision_starti;
  reg  finaldecision_bgn_reg;
  reg [4:0] finaldecision_countMax;  // ufix5
  reg  finaldecision_enb_dec_temp;
  reg [4:0] finaldecision_count_temp;  // ufix5
  reg [8:0] finaldecision_zCount1_temp;  // ufix9
  reg [8:0] finaldecision_zCount2_temp;  // ufix9
  reg  finaldecision_cntEnb_temp;
  reg  finaldecision_endD_temp;
  reg  finaldecision_ctrlEnd_temp;
  reg signed [31:0] finaldecision_t_0_0;  // int32
  reg [8:0] finaldecision_t_1;  // ufix9
  reg [8:0] finaldecision_t_2;  // ufix9


  assign data[0] = data_0;
  assign data[1] = data_1;
  assign data[2] = data_2;
  assign data[3] = data_3;
  assign data[4] = data_4;
  assign data[5] = data_5;
  assign data[6] = data_6;
  assign data[7] = data_7;
  assign data[8] = data_8;
  assign data[9] = data_9;
  assign data[10] = data_10;
  assign data[11] = data_11;
  assign data[12] = data_12;
  assign data[13] = data_13;
  assign data[14] = data_14;
  assign data[15] = data_15;
  assign data[16] = data_16;
  assign data[17] = data_17;
  assign data[18] = data_18;
  assign data[19] = data_19;
  assign data[20] = data_20;
  assign data[21] = data_21;
  assign data[22] = data_22;
  assign data[23] = data_23;
  assign data[24] = data_24;
  assign data[25] = data_25;
  assign data[26] = data_26;
  assign data[27] = data_27;
  assign data[28] = data_28;
  assign data[29] = data_29;
  assign data[30] = data_30;
  assign data[31] = data_31;
  assign data[32] = data_32;
  assign data[33] = data_33;
  assign data[34] = data_34;
  assign data[35] = data_35;
  assign data[36] = data_36;
  assign data[37] = data_37;
  assign data[38] = data_38;
  assign data[39] = data_39;
  assign data[40] = data_40;
  assign data[41] = data_41;
  assign data[42] = data_42;
  assign data[43] = data_43;
  assign data[44] = data_44;
  assign data[45] = data_45;
  assign data[46] = data_46;
  assign data[47] = data_47;
  assign data[48] = data_48;
  assign data[49] = data_49;
  assign data[50] = data_50;
  assign data[51] = data_51;
  assign data[52] = data_52;
  assign data[53] = data_53;
  assign data[54] = data_54;
  assign data[55] = data_55;
  assign data[56] = data_56;
  assign data[57] = data_57;
  assign data[58] = data_58;
  assign data[59] = data_59;
  assign data[60] = data_60;
  assign data[61] = data_61;
  assign data[62] = data_62;
  assign data[63] = data_63;
  assign data[64] = data_64;
  assign data[65] = data_65;
  assign data[66] = data_66;
  assign data[67] = data_67;
  assign data[68] = data_68;
  assign data[69] = data_69;
  assign data[70] = data_70;
  assign data[71] = data_71;
  assign data[72] = data_72;
  assign data[73] = data_73;
  assign data[74] = data_74;
  assign data[75] = data_75;
  assign data[76] = data_76;
  assign data[77] = data_77;
  assign data[78] = data_78;
  assign data[79] = data_79;
  assign data[80] = data_80;
  assign data[81] = data_81;
  assign data[82] = data_82;
  assign data[83] = data_83;
  assign data[84] = data_84;
  assign data[85] = data_85;
  assign data[86] = data_86;
  assign data[87] = data_87;
  assign data[88] = data_88;
  assign data[89] = data_89;
  assign data[90] = data_90;
  assign data[91] = data_91;
  assign data[92] = data_92;
  assign data[93] = data_93;
  assign data[94] = data_94;
  assign data[95] = data_95;
  assign data[96] = data_96;
  assign data[97] = data_97;
  assign data[98] = data_98;
  assign data[99] = data_99;
  assign data[100] = data_100;
  assign data[101] = data_101;
  assign data[102] = data_102;
  assign data[103] = data_103;
  assign data[104] = data_104;
  assign data[105] = data_105;
  assign data[106] = data_106;
  assign data[107] = data_107;
  assign data[108] = data_108;
  assign data[109] = data_109;
  assign data[110] = data_110;
  assign data[111] = data_111;
  assign data[112] = data_112;
  assign data[113] = data_113;
  assign data[114] = data_114;
  assign data[115] = data_115;
  assign data[116] = data_116;
  assign data[117] = data_117;
  assign data[118] = data_118;
  assign data[119] = data_119;
  assign data[120] = data_120;
  assign data[121] = data_121;
  assign data[122] = data_122;
  assign data[123] = data_123;
  assign data[124] = data_124;
  assign data[125] = data_125;
  assign data[126] = data_126;
  assign data[127] = data_127;
  assign data[128] = data_128;
  assign data[129] = data_129;
  assign data[130] = data_130;
  assign data[131] = data_131;
  assign data[132] = data_132;
  assign data[133] = data_133;
  assign data[134] = data_134;
  assign data[135] = data_135;
  assign data[136] = data_136;
  assign data[137] = data_137;
  assign data[138] = data_138;
  assign data[139] = data_139;
  assign data[140] = data_140;
  assign data[141] = data_141;
  assign data[142] = data_142;
  assign data[143] = data_143;
  assign data[144] = data_144;
  assign data[145] = data_145;
  assign data[146] = data_146;
  assign data[147] = data_147;
  assign data[148] = data_148;
  assign data[149] = data_149;
  assign data[150] = data_150;
  assign data[151] = data_151;
  assign data[152] = data_152;
  assign data[153] = data_153;
  assign data[154] = data_154;
  assign data[155] = data_155;
  assign data[156] = data_156;
  assign data[157] = data_157;
  assign data[158] = data_158;
  assign data[159] = data_159;
  assign data[160] = data_160;
  assign data[161] = data_161;
  assign data[162] = data_162;
  assign data[163] = data_163;
  assign data[164] = data_164;
  assign data[165] = data_165;
  assign data[166] = data_166;
  assign data[167] = data_167;
  assign data[168] = data_168;
  assign data[169] = data_169;
  assign data[170] = data_170;
  assign data[171] = data_171;
  assign data[172] = data_172;
  assign data[173] = data_173;
  assign data[174] = data_174;
  assign data[175] = data_175;
  assign data[176] = data_176;
  assign data[177] = data_177;
  assign data[178] = data_178;
  assign data[179] = data_179;
  assign data[180] = data_180;
  assign data[181] = data_181;
  assign data[182] = data_182;
  assign data[183] = data_183;
  assign data[184] = data_184;
  assign data[185] = data_185;
  assign data[186] = data_186;
  assign data[187] = data_187;
  assign data[188] = data_188;
  assign data[189] = data_189;
  assign data[190] = data_190;
  assign data[191] = data_191;
  assign data[192] = data_192;
  assign data[193] = data_193;
  assign data[194] = data_194;
  assign data[195] = data_195;
  assign data[196] = data_196;
  assign data[197] = data_197;
  assign data[198] = data_198;
  assign data[199] = data_199;
  assign data[200] = data_200;
  assign data[201] = data_201;
  assign data[202] = data_202;
  assign data[203] = data_203;
  assign data[204] = data_204;
  assign data[205] = data_205;
  assign data[206] = data_206;
  assign data[207] = data_207;
  assign data[208] = data_208;
  assign data[209] = data_209;
  assign data[210] = data_210;
  assign data[211] = data_211;
  assign data[212] = data_212;
  assign data[213] = data_213;
  assign data[214] = data_214;
  assign data[215] = data_215;
  assign data[216] = data_216;
  assign data[217] = data_217;
  assign data[218] = data_218;
  assign data[219] = data_219;
  assign data[220] = data_220;
  assign data[221] = data_221;
  assign data[222] = data_222;
  assign data[223] = data_223;
  assign data[224] = data_224;
  assign data[225] = data_225;
  assign data[226] = data_226;
  assign data[227] = data_227;
  assign data[228] = data_228;
  assign data[229] = data_229;
  assign data[230] = data_230;
  assign data[231] = data_231;
  assign data[232] = data_232;
  assign data[233] = data_233;
  assign data[234] = data_234;
  assign data[235] = data_235;
  assign data[236] = data_236;
  assign data[237] = data_237;
  assign data[238] = data_238;
  assign data[239] = data_239;
  assign data[240] = data_240;
  assign data[241] = data_241;
  assign data[242] = data_242;
  assign data[243] = data_243;
  assign data[244] = data_244;
  assign data[245] = data_245;
  assign data[246] = data_246;
  assign data[247] = data_247;
  assign data[248] = data_248;
  assign data[249] = data_249;
  assign data[250] = data_250;
  assign data[251] = data_251;
  assign data[252] = data_252;
  assign data[253] = data_253;
  assign data[254] = data_254;
  assign data[255] = data_255;
  assign data[256] = data_256;
  assign data[257] = data_257;
  assign data[258] = data_258;
  assign data[259] = data_259;
  assign data[260] = data_260;
  assign data[261] = data_261;
  assign data[262] = data_262;
  assign data[263] = data_263;
  assign data[264] = data_264;
  assign data[265] = data_265;
  assign data[266] = data_266;
  assign data[267] = data_267;
  assign data[268] = data_268;
  assign data[269] = data_269;
  assign data[270] = data_270;
  assign data[271] = data_271;
  assign data[272] = data_272;
  assign data[273] = data_273;
  assign data[274] = data_274;
  assign data[275] = data_275;
  assign data[276] = data_276;
  assign data[277] = data_277;
  assign data[278] = data_278;
  assign data[279] = data_279;
  assign data[280] = data_280;
  assign data[281] = data_281;
  assign data[282] = data_282;
  assign data[283] = data_283;
  assign data[284] = data_284;
  assign data[285] = data_285;
  assign data[286] = data_286;
  assign data[287] = data_287;
  assign data[288] = data_288;
  assign data[289] = data_289;
  assign data[290] = data_290;
  assign data[291] = data_291;
  assign data[292] = data_292;
  assign data[293] = data_293;
  assign data[294] = data_294;
  assign data[295] = data_295;
  assign data[296] = data_296;
  assign data[297] = data_297;
  assign data[298] = data_298;
  assign data[299] = data_299;
  assign data[300] = data_300;
  assign data[301] = data_301;
  assign data[302] = data_302;
  assign data[303] = data_303;
  assign data[304] = data_304;
  assign data[305] = data_305;
  assign data[306] = data_306;
  assign data[307] = data_307;
  assign data[308] = data_308;
  assign data[309] = data_309;
  assign data[310] = data_310;
  assign data[311] = data_311;
  assign data[312] = data_312;
  assign data[313] = data_313;
  assign data[314] = data_314;
  assign data[315] = data_315;
  assign data[316] = data_316;
  assign data[317] = data_317;
  assign data[318] = data_318;
  assign data[319] = data_319;
  assign data[320] = data_320;
  assign data[321] = data_321;
  assign data[322] = data_322;
  assign data[323] = data_323;
  assign data[324] = data_324;
  assign data[325] = data_325;
  assign data[326] = data_326;
  assign data[327] = data_327;
  assign data[328] = data_328;
  assign data[329] = data_329;
  assign data[330] = data_330;
  assign data[331] = data_331;
  assign data[332] = data_332;
  assign data[333] = data_333;
  assign data[334] = data_334;
  assign data[335] = data_335;
  assign data[336] = data_336;
  assign data[337] = data_337;
  assign data[338] = data_338;
  assign data[339] = data_339;
  assign data[340] = data_340;
  assign data[341] = data_341;
  assign data[342] = data_342;
  assign data[343] = data_343;
  assign data[344] = data_344;
  assign data[345] = data_345;
  assign data[346] = data_346;
  assign data[347] = data_347;
  assign data[348] = data_348;
  assign data[349] = data_349;
  assign data[350] = data_350;
  assign data[351] = data_351;
  assign data[352] = data_352;
  assign data[353] = data_353;
  assign data[354] = data_354;
  assign data[355] = data_355;
  assign data[356] = data_356;
  assign data[357] = data_357;
  assign data[358] = data_358;
  assign data[359] = data_359;
  assign data[360] = data_360;
  assign data[361] = data_361;
  assign data[362] = data_362;
  assign data[363] = data_363;
  assign data[364] = data_364;
  assign data[365] = data_365;
  assign data[366] = data_366;
  assign data[367] = data_367;
  assign data[368] = data_368;
  assign data[369] = data_369;
  assign data[370] = data_370;
  assign data[371] = data_371;
  assign data[372] = data_372;
  assign data[373] = data_373;
  assign data[374] = data_374;
  assign data[375] = data_375;
  assign data[376] = data_376;
  assign data[377] = data_377;
  assign data[378] = data_378;
  assign data[379] = data_379;
  assign data[380] = data_380;
  assign data[381] = data_381;
  assign data[382] = data_382;
  assign data[383] = data_383;

  always @(posedge clk or negedge reset)
    begin : finaldecision_process
      if (reset == 1'b0) begin
        finaldecision_enb_dec <= 1'b0;
        finaldecision_count <= 5'b00001;
        finaldecision_iterDone <= 1'b0;
        finaldecision_zCount1 <= 9'b000000000;
        finaldecision_zCount2 <= 9'b000000000;
        finaldecision_cntEnb <= 1'b0;
        finaldecision_endD <= 1'b0;
        finaldecision_ctrlEnd <= 1'b0;
      end
      else begin
        if (enb) begin
          finaldecision_enb_dec <= finaldecision_enb_dec_next;
          finaldecision_count <= finaldecision_count_next;
          finaldecision_iterDone <= finaldecision_iterDone_next;
          finaldecision_zCount1 <= finaldecision_zCount1_next;
          finaldecision_zCount2 <= finaldecision_zCount2_next;
          finaldecision_cntEnb <= finaldecision_cntEnb_next;
          finaldecision_endD <= finaldecision_endD_next;
          finaldecision_ctrlEnd <= finaldecision_ctrlEnd_next;
        end
      end
    end

  always @* begin
    finaldecision_t_1 = 9'b000000000;
    finaldecision_t_2 = 9'b000000000;
    finaldecision_enb_dec_temp = finaldecision_enb_dec;
    finaldecision_count_temp = finaldecision_count;
    finaldecision_zCount1_temp = finaldecision_zCount1;
    finaldecision_zCount2_temp = finaldecision_zCount2;
    finaldecision_cntEnb_temp = finaldecision_cntEnb;
    finaldecision_endD_temp = finaldecision_endD;
    finaldecision_ctrlEnd_temp = finaldecision_ctrlEnd;
    if (reset_1 != 1'b0) begin
      finaldecision_enb_dec_temp = 1'b0;
      finaldecision_count_temp = 5'b00001;
      finaldecision_zCount1_temp = 9'b000000000;
      finaldecision_zCount2_temp = 9'b000000000;
      finaldecision_cntEnb_temp = 1'b0;
      finaldecision_endD_temp = 1'b0;
      finaldecision_ctrlEnd_temp = 1'b0;
      finaldecision_starti = 1'b0;
    end
    else begin
      finaldecision_starti = iterdone && ( ! finaldecision_iterDone);
    end
    finaldecision_iterDone_next = iterdone;
    finaldecision_bgn_reg = bgn;
    if (finaldecision_bgn_reg) begin
      finaldecision_countMax = 5'b01010;
    end
    else begin
      finaldecision_countMax = 5'b10110;
    end
    if (liftsize <= 9'b001000000) begin
      finaldecision_zcount = 32'sd1;
    end
    else if (liftsize <= 9'b010000000) begin
      finaldecision_zcount = 32'sd2;
    end
    else if (liftsize <= 9'b011000000) begin
      finaldecision_zcount = 32'sd3;
    end
    else if (liftsize <= 9'b100000000) begin
      finaldecision_zcount = 32'sd4;
    end
    else if (liftsize <= 9'b101000000) begin
      finaldecision_zcount = 32'sd5;
    end
    else begin
      finaldecision_zcount = 32'sd6;
    end
    if (finaldecision_ctrlEnd_temp) begin
      finaldecision_count_temp = 5'b00001;
    end
    if (finaldecision_starti) begin
      finaldecision_enb_dec_temp = iterdone;
      finaldecision_zCount1_temp = 9'b000000001;
      finaldecision_zCount2_temp = 9'b000000001;
    end
    if (finaldecision_enb_dec_temp) begin
      finaldecision_t_1 = finaldecision_zcount[8:0];
      if (finaldecision_zCount1_temp == finaldecision_t_1) begin
        finaldecision_zCount1_temp = 9'b000000001;
        finaldecision_cntEnb_temp = 1'b1;
      end
      else begin
        finaldecision_zCount1_temp = finaldecision_zCount1_temp + 9'b000000001;
        finaldecision_cntEnb_temp = 1'b0;
      end
      if (finaldecision_count_temp == finaldecision_countMax) begin
        finaldecision_endD_temp = 1'b1;
        finaldecision_enb_dec_temp = 1'b0;
      end
      else if (finaldecision_cntEnb_temp) begin
        finaldecision_count_temp = finaldecision_count_temp + 5'b00001;
      end
      finaldecision_validi = 1'b1;
    end
    else begin
      finaldecision_validi = 1'b0;
    end
    if (finaldecision_endD_temp) begin
      finaldecision_t_2 = finaldecision_zcount[8:0];
      if (finaldecision_zCount2_temp == finaldecision_t_2) begin
        finaldecision_zCount2_temp = 9'b000000001;
        finaldecision_ctrlEnd_temp = 1'b1;
        finaldecision_endD_temp = 1'b0;
      end
      else begin
        finaldecision_ctrlEnd_temp = 1'b0;
        finaldecision_zCount2_temp = finaldecision_zCount2_temp + 9'b000000001;
      end
    end
    else begin
      finaldecision_ctrlEnd_temp = 1'b0;
    end
    valid_out = (finaldecision_validi || finaldecision_endD_temp) || finaldecision_ctrlEnd_temp;

    for(finaldecision_t_0_0 = 32'sd0; finaldecision_t_0_0 <= 32'sd383; finaldecision_t_0_0 = finaldecision_t_0_0 + 32'sd1) begin
      data_384[finaldecision_t_0_0] = data[finaldecision_t_0_0] <= 10'sb0000000000;
    end

    start_out = finaldecision_starti;
    end_out = finaldecision_ctrlEnd_temp;
    count = finaldecision_count_temp;
    finaldecision_enb_dec_next = finaldecision_enb_dec_temp;
    finaldecision_count_next = finaldecision_count_temp;
    finaldecision_zCount1_next = finaldecision_zCount1_temp;
    finaldecision_zCount2_next = finaldecision_zCount2_temp;
    finaldecision_cntEnb_next = finaldecision_cntEnb_temp;
    finaldecision_endD_next = finaldecision_endD_temp;
    finaldecision_ctrlEnd_next = finaldecision_ctrlEnd_temp;
  end

  always @(posedge clk or negedge reset)
    begin : dataOut_process
      if (reset == 1'b0) begin
        decbits <= {384{1'b0}};
      end
      else begin
        if (enb) begin
          decbits <= data_384;
        end
      end
    end

  assign decbits_0 = decbits[0];

  assign decbits_1 = decbits[1];

  assign decbits_2 = decbits[2];

  assign decbits_3 = decbits[3];

  assign decbits_4 = decbits[4];

  assign decbits_5 = decbits[5];

  assign decbits_6 = decbits[6];

  assign decbits_7 = decbits[7];

  assign decbits_8 = decbits[8];

  assign decbits_9 = decbits[9];

  assign decbits_10 = decbits[10];

  assign decbits_11 = decbits[11];

  assign decbits_12 = decbits[12];

  assign decbits_13 = decbits[13];

  assign decbits_14 = decbits[14];

  assign decbits_15 = decbits[15];

  assign decbits_16 = decbits[16];

  assign decbits_17 = decbits[17];

  assign decbits_18 = decbits[18];

  assign decbits_19 = decbits[19];

  assign decbits_20 = decbits[20];

  assign decbits_21 = decbits[21];

  assign decbits_22 = decbits[22];

  assign decbits_23 = decbits[23];

  assign decbits_24 = decbits[24];

  assign decbits_25 = decbits[25];

  assign decbits_26 = decbits[26];

  assign decbits_27 = decbits[27];

  assign decbits_28 = decbits[28];

  assign decbits_29 = decbits[29];

  assign decbits_30 = decbits[30];

  assign decbits_31 = decbits[31];

  assign decbits_32 = decbits[32];

  assign decbits_33 = decbits[33];

  assign decbits_34 = decbits[34];

  assign decbits_35 = decbits[35];

  assign decbits_36 = decbits[36];

  assign decbits_37 = decbits[37];

  assign decbits_38 = decbits[38];

  assign decbits_39 = decbits[39];

  assign decbits_40 = decbits[40];

  assign decbits_41 = decbits[41];

  assign decbits_42 = decbits[42];

  assign decbits_43 = decbits[43];

  assign decbits_44 = decbits[44];

  assign decbits_45 = decbits[45];

  assign decbits_46 = decbits[46];

  assign decbits_47 = decbits[47];

  assign decbits_48 = decbits[48];

  assign decbits_49 = decbits[49];

  assign decbits_50 = decbits[50];

  assign decbits_51 = decbits[51];

  assign decbits_52 = decbits[52];

  assign decbits_53 = decbits[53];

  assign decbits_54 = decbits[54];

  assign decbits_55 = decbits[55];

  assign decbits_56 = decbits[56];

  assign decbits_57 = decbits[57];

  assign decbits_58 = decbits[58];

  assign decbits_59 = decbits[59];

  assign decbits_60 = decbits[60];

  assign decbits_61 = decbits[61];

  assign decbits_62 = decbits[62];

  assign decbits_63 = decbits[63];

  assign decbits_64 = decbits[64];

  assign decbits_65 = decbits[65];

  assign decbits_66 = decbits[66];

  assign decbits_67 = decbits[67];

  assign decbits_68 = decbits[68];

  assign decbits_69 = decbits[69];

  assign decbits_70 = decbits[70];

  assign decbits_71 = decbits[71];

  assign decbits_72 = decbits[72];

  assign decbits_73 = decbits[73];

  assign decbits_74 = decbits[74];

  assign decbits_75 = decbits[75];

  assign decbits_76 = decbits[76];

  assign decbits_77 = decbits[77];

  assign decbits_78 = decbits[78];

  assign decbits_79 = decbits[79];

  assign decbits_80 = decbits[80];

  assign decbits_81 = decbits[81];

  assign decbits_82 = decbits[82];

  assign decbits_83 = decbits[83];

  assign decbits_84 = decbits[84];

  assign decbits_85 = decbits[85];

  assign decbits_86 = decbits[86];

  assign decbits_87 = decbits[87];

  assign decbits_88 = decbits[88];

  assign decbits_89 = decbits[89];

  assign decbits_90 = decbits[90];

  assign decbits_91 = decbits[91];

  assign decbits_92 = decbits[92];

  assign decbits_93 = decbits[93];

  assign decbits_94 = decbits[94];

  assign decbits_95 = decbits[95];

  assign decbits_96 = decbits[96];

  assign decbits_97 = decbits[97];

  assign decbits_98 = decbits[98];

  assign decbits_99 = decbits[99];

  assign decbits_100 = decbits[100];

  assign decbits_101 = decbits[101];

  assign decbits_102 = decbits[102];

  assign decbits_103 = decbits[103];

  assign decbits_104 = decbits[104];

  assign decbits_105 = decbits[105];

  assign decbits_106 = decbits[106];

  assign decbits_107 = decbits[107];

  assign decbits_108 = decbits[108];

  assign decbits_109 = decbits[109];

  assign decbits_110 = decbits[110];

  assign decbits_111 = decbits[111];

  assign decbits_112 = decbits[112];

  assign decbits_113 = decbits[113];

  assign decbits_114 = decbits[114];

  assign decbits_115 = decbits[115];

  assign decbits_116 = decbits[116];

  assign decbits_117 = decbits[117];

  assign decbits_118 = decbits[118];

  assign decbits_119 = decbits[119];

  assign decbits_120 = decbits[120];

  assign decbits_121 = decbits[121];

  assign decbits_122 = decbits[122];

  assign decbits_123 = decbits[123];

  assign decbits_124 = decbits[124];

  assign decbits_125 = decbits[125];

  assign decbits_126 = decbits[126];

  assign decbits_127 = decbits[127];

  assign decbits_128 = decbits[128];

  assign decbits_129 = decbits[129];

  assign decbits_130 = decbits[130];

  assign decbits_131 = decbits[131];

  assign decbits_132 = decbits[132];

  assign decbits_133 = decbits[133];

  assign decbits_134 = decbits[134];

  assign decbits_135 = decbits[135];

  assign decbits_136 = decbits[136];

  assign decbits_137 = decbits[137];

  assign decbits_138 = decbits[138];

  assign decbits_139 = decbits[139];

  assign decbits_140 = decbits[140];

  assign decbits_141 = decbits[141];

  assign decbits_142 = decbits[142];

  assign decbits_143 = decbits[143];

  assign decbits_144 = decbits[144];

  assign decbits_145 = decbits[145];

  assign decbits_146 = decbits[146];

  assign decbits_147 = decbits[147];

  assign decbits_148 = decbits[148];

  assign decbits_149 = decbits[149];

  assign decbits_150 = decbits[150];

  assign decbits_151 = decbits[151];

  assign decbits_152 = decbits[152];

  assign decbits_153 = decbits[153];

  assign decbits_154 = decbits[154];

  assign decbits_155 = decbits[155];

  assign decbits_156 = decbits[156];

  assign decbits_157 = decbits[157];

  assign decbits_158 = decbits[158];

  assign decbits_159 = decbits[159];

  assign decbits_160 = decbits[160];

  assign decbits_161 = decbits[161];

  assign decbits_162 = decbits[162];

  assign decbits_163 = decbits[163];

  assign decbits_164 = decbits[164];

  assign decbits_165 = decbits[165];

  assign decbits_166 = decbits[166];

  assign decbits_167 = decbits[167];

  assign decbits_168 = decbits[168];

  assign decbits_169 = decbits[169];

  assign decbits_170 = decbits[170];

  assign decbits_171 = decbits[171];

  assign decbits_172 = decbits[172];

  assign decbits_173 = decbits[173];

  assign decbits_174 = decbits[174];

  assign decbits_175 = decbits[175];

  assign decbits_176 = decbits[176];

  assign decbits_177 = decbits[177];

  assign decbits_178 = decbits[178];

  assign decbits_179 = decbits[179];

  assign decbits_180 = decbits[180];

  assign decbits_181 = decbits[181];

  assign decbits_182 = decbits[182];

  assign decbits_183 = decbits[183];

  assign decbits_184 = decbits[184];

  assign decbits_185 = decbits[185];

  assign decbits_186 = decbits[186];

  assign decbits_187 = decbits[187];

  assign decbits_188 = decbits[188];

  assign decbits_189 = decbits[189];

  assign decbits_190 = decbits[190];

  assign decbits_191 = decbits[191];

  assign decbits_192 = decbits[192];

  assign decbits_193 = decbits[193];

  assign decbits_194 = decbits[194];

  assign decbits_195 = decbits[195];

  assign decbits_196 = decbits[196];

  assign decbits_197 = decbits[197];

  assign decbits_198 = decbits[198];

  assign decbits_199 = decbits[199];

  assign decbits_200 = decbits[200];

  assign decbits_201 = decbits[201];

  assign decbits_202 = decbits[202];

  assign decbits_203 = decbits[203];

  assign decbits_204 = decbits[204];

  assign decbits_205 = decbits[205];

  assign decbits_206 = decbits[206];

  assign decbits_207 = decbits[207];

  assign decbits_208 = decbits[208];

  assign decbits_209 = decbits[209];

  assign decbits_210 = decbits[210];

  assign decbits_211 = decbits[211];

  assign decbits_212 = decbits[212];

  assign decbits_213 = decbits[213];

  assign decbits_214 = decbits[214];

  assign decbits_215 = decbits[215];

  assign decbits_216 = decbits[216];

  assign decbits_217 = decbits[217];

  assign decbits_218 = decbits[218];

  assign decbits_219 = decbits[219];

  assign decbits_220 = decbits[220];

  assign decbits_221 = decbits[221];

  assign decbits_222 = decbits[222];

  assign decbits_223 = decbits[223];

  assign decbits_224 = decbits[224];

  assign decbits_225 = decbits[225];

  assign decbits_226 = decbits[226];

  assign decbits_227 = decbits[227];

  assign decbits_228 = decbits[228];

  assign decbits_229 = decbits[229];

  assign decbits_230 = decbits[230];

  assign decbits_231 = decbits[231];

  assign decbits_232 = decbits[232];

  assign decbits_233 = decbits[233];

  assign decbits_234 = decbits[234];

  assign decbits_235 = decbits[235];

  assign decbits_236 = decbits[236];

  assign decbits_237 = decbits[237];

  assign decbits_238 = decbits[238];

  assign decbits_239 = decbits[239];

  assign decbits_240 = decbits[240];

  assign decbits_241 = decbits[241];

  assign decbits_242 = decbits[242];

  assign decbits_243 = decbits[243];

  assign decbits_244 = decbits[244];

  assign decbits_245 = decbits[245];

  assign decbits_246 = decbits[246];

  assign decbits_247 = decbits[247];

  assign decbits_248 = decbits[248];

  assign decbits_249 = decbits[249];

  assign decbits_250 = decbits[250];

  assign decbits_251 = decbits[251];

  assign decbits_252 = decbits[252];

  assign decbits_253 = decbits[253];

  assign decbits_254 = decbits[254];

  assign decbits_255 = decbits[255];

  assign decbits_256 = decbits[256];

  assign decbits_257 = decbits[257];

  assign decbits_258 = decbits[258];

  assign decbits_259 = decbits[259];

  assign decbits_260 = decbits[260];

  assign decbits_261 = decbits[261];

  assign decbits_262 = decbits[262];

  assign decbits_263 = decbits[263];

  assign decbits_264 = decbits[264];

  assign decbits_265 = decbits[265];

  assign decbits_266 = decbits[266];

  assign decbits_267 = decbits[267];

  assign decbits_268 = decbits[268];

  assign decbits_269 = decbits[269];

  assign decbits_270 = decbits[270];

  assign decbits_271 = decbits[271];

  assign decbits_272 = decbits[272];

  assign decbits_273 = decbits[273];

  assign decbits_274 = decbits[274];

  assign decbits_275 = decbits[275];

  assign decbits_276 = decbits[276];

  assign decbits_277 = decbits[277];

  assign decbits_278 = decbits[278];

  assign decbits_279 = decbits[279];

  assign decbits_280 = decbits[280];

  assign decbits_281 = decbits[281];

  assign decbits_282 = decbits[282];

  assign decbits_283 = decbits[283];

  assign decbits_284 = decbits[284];

  assign decbits_285 = decbits[285];

  assign decbits_286 = decbits[286];

  assign decbits_287 = decbits[287];

  assign decbits_288 = decbits[288];

  assign decbits_289 = decbits[289];

  assign decbits_290 = decbits[290];

  assign decbits_291 = decbits[291];

  assign decbits_292 = decbits[292];

  assign decbits_293 = decbits[293];

  assign decbits_294 = decbits[294];

  assign decbits_295 = decbits[295];

  assign decbits_296 = decbits[296];

  assign decbits_297 = decbits[297];

  assign decbits_298 = decbits[298];

  assign decbits_299 = decbits[299];

  assign decbits_300 = decbits[300];

  assign decbits_301 = decbits[301];

  assign decbits_302 = decbits[302];

  assign decbits_303 = decbits[303];

  assign decbits_304 = decbits[304];

  assign decbits_305 = decbits[305];

  assign decbits_306 = decbits[306];

  assign decbits_307 = decbits[307];

  assign decbits_308 = decbits[308];

  assign decbits_309 = decbits[309];

  assign decbits_310 = decbits[310];

  assign decbits_311 = decbits[311];

  assign decbits_312 = decbits[312];

  assign decbits_313 = decbits[313];

  assign decbits_314 = decbits[314];

  assign decbits_315 = decbits[315];

  assign decbits_316 = decbits[316];

  assign decbits_317 = decbits[317];

  assign decbits_318 = decbits[318];

  assign decbits_319 = decbits[319];

  assign decbits_320 = decbits[320];

  assign decbits_321 = decbits[321];

  assign decbits_322 = decbits[322];

  assign decbits_323 = decbits[323];

  assign decbits_324 = decbits[324];

  assign decbits_325 = decbits[325];

  assign decbits_326 = decbits[326];

  assign decbits_327 = decbits[327];

  assign decbits_328 = decbits[328];

  assign decbits_329 = decbits[329];

  assign decbits_330 = decbits[330];

  assign decbits_331 = decbits[331];

  assign decbits_332 = decbits[332];

  assign decbits_333 = decbits[333];

  assign decbits_334 = decbits[334];

  assign decbits_335 = decbits[335];

  assign decbits_336 = decbits[336];

  assign decbits_337 = decbits[337];

  assign decbits_338 = decbits[338];

  assign decbits_339 = decbits[339];

  assign decbits_340 = decbits[340];

  assign decbits_341 = decbits[341];

  assign decbits_342 = decbits[342];

  assign decbits_343 = decbits[343];

  assign decbits_344 = decbits[344];

  assign decbits_345 = decbits[345];

  assign decbits_346 = decbits[346];

  assign decbits_347 = decbits[347];

  assign decbits_348 = decbits[348];

  assign decbits_349 = decbits[349];

  assign decbits_350 = decbits[350];

  assign decbits_351 = decbits[351];

  assign decbits_352 = decbits[352];

  assign decbits_353 = decbits[353];

  assign decbits_354 = decbits[354];

  assign decbits_355 = decbits[355];

  assign decbits_356 = decbits[356];

  assign decbits_357 = decbits[357];

  assign decbits_358 = decbits[358];

  assign decbits_359 = decbits[359];

  assign decbits_360 = decbits[360];

  assign decbits_361 = decbits[361];

  assign decbits_362 = decbits[362];

  assign decbits_363 = decbits[363];

  assign decbits_364 = decbits[364];

  assign decbits_365 = decbits[365];

  assign decbits_366 = decbits[366];

  assign decbits_367 = decbits[367];

  assign decbits_368 = decbits[368];

  assign decbits_369 = decbits[369];

  assign decbits_370 = decbits[370];

  assign decbits_371 = decbits[371];

  assign decbits_372 = decbits[372];

  assign decbits_373 = decbits[373];

  assign decbits_374 = decbits[374];

  assign decbits_375 = decbits[375];

  assign decbits_376 = decbits[376];

  assign decbits_377 = decbits[377];

  assign decbits_378 = decbits[378];

  assign decbits_379 = decbits[379];

  assign decbits_380 = decbits[380];

  assign decbits_381 = decbits[381];

  assign decbits_382 = decbits[382];

  assign decbits_383 = decbits[383];

  always @(posedge clk or negedge reset)
    begin : startOut_process
      if (reset == 1'b0) begin
        start_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          start_1 <= start_out;
        end
      end
    end

  always @(posedge clk or negedge reset)
    begin : endOut_process
      if (reset == 1'b0) begin
        end_rsvd_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          end_rsvd_1 <= end_out;
        end
      end
    end

  assign valid = valid_out;

  assign shift_1 = (count == 5'b00000 ? fin_shift_0 :
              (count == 5'b00001 ? fin_shift_0 :
              (count == 5'b00010 ? fin_shift_1 :
              (count == 5'b00011 ? fin_shift_2 :
              (count == 5'b00100 ? fin_shift_3 :
              (count == 5'b00101 ? fin_shift_4 :
              (count == 5'b00110 ? fin_shift_5 :
              (count == 5'b00111 ? fin_shift_6 :
              (count == 5'b01000 ? fin_shift_7 :
              (count == 5'b01001 ? fin_shift_8 :
              (count == 5'b01010 ? fin_shift_9 :
              (count == 5'b01011 ? fin_shift_10 :
              (count == 5'b01100 ? fin_shift_11 :
              (count == 5'b01101 ? fin_shift_12 :
              (count == 5'b01110 ? fin_shift_13 :
              (count == 5'b01111 ? fin_shift_14 :
              (count == 5'b10000 ? fin_shift_15 :
              (count == 5'b10001 ? fin_shift_16 :
              (count == 5'b10010 ? fin_shift_17 :
              (count == 5'b10011 ? fin_shift_18 :
              (count == 5'b10100 ? fin_shift_19 :
              (count == 5'b10101 ? fin_shift_20 :
              fin_shift_21))))))))))))))))))))));

  always @(posedge clk or negedge reset)
    begin : shift_reg_process
      if (reset == 1'b0) begin
        shift_2 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          shift_2 <= shift_1;
        end
      end
    end

  assign start = start_1;

  assign end_rsvd = end_rsvd_1;

  assign shift = shift_2;

endmodule  // dec_FinalDecision

