// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRLDPCDecoderHDL\dec_HDL_Algorithm.v
// Created: 2026-06-03 20:20:02
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut_0                     ce_out        1
// dataOut_1                     ce_out        1
// dataOut_2                     ce_out        1
// dataOut_3                     ce_out        1
// dataOut_4                     ce_out        1
// dataOut_5                     ce_out        1
// dataOut_6                     ce_out        1
// dataOut_7                     ce_out        1
// dataOut_8                     ce_out        1
// dataOut_9                     ce_out        1
// dataOut_10                    ce_out        1
// dataOut_11                    ce_out        1
// dataOut_12                    ce_out        1
// dataOut_13                    ce_out        1
// dataOut_14                    ce_out        1
// dataOut_15                    ce_out        1
// dataOut_16                    ce_out        1
// dataOut_17                    ce_out        1
// dataOut_18                    ce_out        1
// dataOut_19                    ce_out        1
// dataOut_20                    ce_out        1
// dataOut_21                    ce_out        1
// dataOut_22                    ce_out        1
// dataOut_23                    ce_out        1
// dataOut_24                    ce_out        1
// dataOut_25                    ce_out        1
// dataOut_26                    ce_out        1
// dataOut_27                    ce_out        1
// dataOut_28                    ce_out        1
// dataOut_29                    ce_out        1
// dataOut_30                    ce_out        1
// dataOut_31                    ce_out        1
// dataOut_32                    ce_out        1
// dataOut_33                    ce_out        1
// dataOut_34                    ce_out        1
// dataOut_35                    ce_out        1
// dataOut_36                    ce_out        1
// dataOut_37                    ce_out        1
// dataOut_38                    ce_out        1
// dataOut_39                    ce_out        1
// dataOut_40                    ce_out        1
// dataOut_41                    ce_out        1
// dataOut_42                    ce_out        1
// dataOut_43                    ce_out        1
// dataOut_44                    ce_out        1
// dataOut_45                    ce_out        1
// dataOut_46                    ce_out        1
// dataOut_47                    ce_out        1
// dataOut_48                    ce_out        1
// dataOut_49                    ce_out        1
// dataOut_50                    ce_out        1
// dataOut_51                    ce_out        1
// dataOut_52                    ce_out        1
// dataOut_53                    ce_out        1
// dataOut_54                    ce_out        1
// dataOut_55                    ce_out        1
// dataOut_56                    ce_out        1
// dataOut_57                    ce_out        1
// dataOut_58                    ce_out        1
// dataOut_59                    ce_out        1
// dataOut_60                    ce_out        1
// dataOut_61                    ce_out        1
// dataOut_62                    ce_out        1
// dataOut_63                    ce_out        1
// ctrlOut_start                 ce_out        1
// ctrlOut_end                   ce_out        1
// ctrlOut_valid                 ce_out        1
// liftingSizeOut                ce_out        1
// nextFrame                     ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec_HDL_Algorithm
// Source Path: NRLDPCDecoderHDL/HDL Algorithm
// Hierarchy Level: 0
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec_HDL_Algorithm
          (clk,
           reset,
           clk_enable,
           dataIn_0,
           dataIn_1,
           dataIn_2,
           dataIn_3,
           dataIn_4,
           dataIn_5,
           dataIn_6,
           dataIn_7,
           dataIn_8,
           dataIn_9,
           dataIn_10,
           dataIn_11,
           dataIn_12,
           dataIn_13,
           dataIn_14,
           dataIn_15,
           dataIn_16,
           dataIn_17,
           dataIn_18,
           dataIn_19,
           dataIn_20,
           dataIn_21,
           dataIn_22,
           dataIn_23,
           dataIn_24,
           dataIn_25,
           dataIn_26,
           dataIn_27,
           dataIn_28,
           dataIn_29,
           dataIn_30,
           dataIn_31,
           dataIn_32,
           dataIn_33,
           dataIn_34,
           dataIn_35,
           dataIn_36,
           dataIn_37,
           dataIn_38,
           dataIn_39,
           dataIn_40,
           dataIn_41,
           dataIn_42,
           dataIn_43,
           dataIn_44,
           dataIn_45,
           dataIn_46,
           dataIn_47,
           dataIn_48,
           dataIn_49,
           dataIn_50,
           dataIn_51,
           dataIn_52,
           dataIn_53,
           dataIn_54,
           dataIn_55,
           dataIn_56,
           dataIn_57,
           dataIn_58,
           dataIn_59,
           dataIn_60,
           dataIn_61,
           dataIn_62,
           dataIn_63,
           ctrlIn_start,
           ctrlIn_end,
           ctrlIn_valid,
           bgn,
           liftingSizeIn,
           ce_out,
           dataOut_0,
           dataOut_1,
           dataOut_2,
           dataOut_3,
           dataOut_4,
           dataOut_5,
           dataOut_6,
           dataOut_7,
           dataOut_8,
           dataOut_9,
           dataOut_10,
           dataOut_11,
           dataOut_12,
           dataOut_13,
           dataOut_14,
           dataOut_15,
           dataOut_16,
           dataOut_17,
           dataOut_18,
           dataOut_19,
           dataOut_20,
           dataOut_21,
           dataOut_22,
           dataOut_23,
           dataOut_24,
           dataOut_25,
           dataOut_26,
           dataOut_27,
           dataOut_28,
           dataOut_29,
           dataOut_30,
           dataOut_31,
           dataOut_32,
           dataOut_33,
           dataOut_34,
           dataOut_35,
           dataOut_36,
           dataOut_37,
           dataOut_38,
           dataOut_39,
           dataOut_40,
           dataOut_41,
           dataOut_42,
           dataOut_43,
           dataOut_44,
           dataOut_45,
           dataOut_46,
           dataOut_47,
           dataOut_48,
           dataOut_49,
           dataOut_50,
           dataOut_51,
           dataOut_52,
           dataOut_53,
           dataOut_54,
           dataOut_55,
           dataOut_56,
           dataOut_57,
           dataOut_58,
           dataOut_59,
           dataOut_60,
           dataOut_61,
           dataOut_62,
           dataOut_63,
           ctrlOut_start,
           ctrlOut_end,
           ctrlOut_valid,
           liftingSizeOut,
           nextFrame);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [3:0] dataIn_0;  // sfix4
  input   signed [3:0] dataIn_1;  // sfix4
  input   signed [3:0] dataIn_2;  // sfix4
  input   signed [3:0] dataIn_3;  // sfix4
  input   signed [3:0] dataIn_4;  // sfix4
  input   signed [3:0] dataIn_5;  // sfix4
  input   signed [3:0] dataIn_6;  // sfix4
  input   signed [3:0] dataIn_7;  // sfix4
  input   signed [3:0] dataIn_8;  // sfix4
  input   signed [3:0] dataIn_9;  // sfix4
  input   signed [3:0] dataIn_10;  // sfix4
  input   signed [3:0] dataIn_11;  // sfix4
  input   signed [3:0] dataIn_12;  // sfix4
  input   signed [3:0] dataIn_13;  // sfix4
  input   signed [3:0] dataIn_14;  // sfix4
  input   signed [3:0] dataIn_15;  // sfix4
  input   signed [3:0] dataIn_16;  // sfix4
  input   signed [3:0] dataIn_17;  // sfix4
  input   signed [3:0] dataIn_18;  // sfix4
  input   signed [3:0] dataIn_19;  // sfix4
  input   signed [3:0] dataIn_20;  // sfix4
  input   signed [3:0] dataIn_21;  // sfix4
  input   signed [3:0] dataIn_22;  // sfix4
  input   signed [3:0] dataIn_23;  // sfix4
  input   signed [3:0] dataIn_24;  // sfix4
  input   signed [3:0] dataIn_25;  // sfix4
  input   signed [3:0] dataIn_26;  // sfix4
  input   signed [3:0] dataIn_27;  // sfix4
  input   signed [3:0] dataIn_28;  // sfix4
  input   signed [3:0] dataIn_29;  // sfix4
  input   signed [3:0] dataIn_30;  // sfix4
  input   signed [3:0] dataIn_31;  // sfix4
  input   signed [3:0] dataIn_32;  // sfix4
  input   signed [3:0] dataIn_33;  // sfix4
  input   signed [3:0] dataIn_34;  // sfix4
  input   signed [3:0] dataIn_35;  // sfix4
  input   signed [3:0] dataIn_36;  // sfix4
  input   signed [3:0] dataIn_37;  // sfix4
  input   signed [3:0] dataIn_38;  // sfix4
  input   signed [3:0] dataIn_39;  // sfix4
  input   signed [3:0] dataIn_40;  // sfix4
  input   signed [3:0] dataIn_41;  // sfix4
  input   signed [3:0] dataIn_42;  // sfix4
  input   signed [3:0] dataIn_43;  // sfix4
  input   signed [3:0] dataIn_44;  // sfix4
  input   signed [3:0] dataIn_45;  // sfix4
  input   signed [3:0] dataIn_46;  // sfix4
  input   signed [3:0] dataIn_47;  // sfix4
  input   signed [3:0] dataIn_48;  // sfix4
  input   signed [3:0] dataIn_49;  // sfix4
  input   signed [3:0] dataIn_50;  // sfix4
  input   signed [3:0] dataIn_51;  // sfix4
  input   signed [3:0] dataIn_52;  // sfix4
  input   signed [3:0] dataIn_53;  // sfix4
  input   signed [3:0] dataIn_54;  // sfix4
  input   signed [3:0] dataIn_55;  // sfix4
  input   signed [3:0] dataIn_56;  // sfix4
  input   signed [3:0] dataIn_57;  // sfix4
  input   signed [3:0] dataIn_58;  // sfix4
  input   signed [3:0] dataIn_59;  // sfix4
  input   signed [3:0] dataIn_60;  // sfix4
  input   signed [3:0] dataIn_61;  // sfix4
  input   signed [3:0] dataIn_62;  // sfix4
  input   signed [3:0] dataIn_63;  // sfix4
  input   ctrlIn_start;
  input   ctrlIn_end;
  input   ctrlIn_valid;
  input   bgn;
  input   [15:0] liftingSizeIn;  // uint16
  output  ce_out;
  output  dataOut_0;  // boolean
  output  dataOut_1;  // boolean
  output  dataOut_2;  // boolean
  output  dataOut_3;  // boolean
  output  dataOut_4;  // boolean
  output  dataOut_5;  // boolean
  output  dataOut_6;  // boolean
  output  dataOut_7;  // boolean
  output  dataOut_8;  // boolean
  output  dataOut_9;  // boolean
  output  dataOut_10;  // boolean
  output  dataOut_11;  // boolean
  output  dataOut_12;  // boolean
  output  dataOut_13;  // boolean
  output  dataOut_14;  // boolean
  output  dataOut_15;  // boolean
  output  dataOut_16;  // boolean
  output  dataOut_17;  // boolean
  output  dataOut_18;  // boolean
  output  dataOut_19;  // boolean
  output  dataOut_20;  // boolean
  output  dataOut_21;  // boolean
  output  dataOut_22;  // boolean
  output  dataOut_23;  // boolean
  output  dataOut_24;  // boolean
  output  dataOut_25;  // boolean
  output  dataOut_26;  // boolean
  output  dataOut_27;  // boolean
  output  dataOut_28;  // boolean
  output  dataOut_29;  // boolean
  output  dataOut_30;  // boolean
  output  dataOut_31;  // boolean
  output  dataOut_32;  // boolean
  output  dataOut_33;  // boolean
  output  dataOut_34;  // boolean
  output  dataOut_35;  // boolean
  output  dataOut_36;  // boolean
  output  dataOut_37;  // boolean
  output  dataOut_38;  // boolean
  output  dataOut_39;  // boolean
  output  dataOut_40;  // boolean
  output  dataOut_41;  // boolean
  output  dataOut_42;  // boolean
  output  dataOut_43;  // boolean
  output  dataOut_44;  // boolean
  output  dataOut_45;  // boolean
  output  dataOut_46;  // boolean
  output  dataOut_47;  // boolean
  output  dataOut_48;  // boolean
  output  dataOut_49;  // boolean
  output  dataOut_50;  // boolean
  output  dataOut_51;  // boolean
  output  dataOut_52;  // boolean
  output  dataOut_53;  // boolean
  output  dataOut_54;  // boolean
  output  dataOut_55;  // boolean
  output  dataOut_56;  // boolean
  output  dataOut_57;  // boolean
  output  dataOut_58;  // boolean
  output  dataOut_59;  // boolean
  output  dataOut_60;  // boolean
  output  dataOut_61;  // boolean
  output  dataOut_62;  // boolean
  output  dataOut_63;  // boolean
  output  ctrlOut_start;
  output  ctrlOut_end;
  output  ctrlOut_valid;
  output  [15:0] liftingSizeOut;  // uint16
  output  nextFrame;


  wire NR_LDPC_Decoder_out1_0;
  wire NR_LDPC_Decoder_out1_1;
  wire NR_LDPC_Decoder_out1_2;
  wire NR_LDPC_Decoder_out1_3;
  wire NR_LDPC_Decoder_out1_4;
  wire NR_LDPC_Decoder_out1_5;
  wire NR_LDPC_Decoder_out1_6;
  wire NR_LDPC_Decoder_out1_7;
  wire NR_LDPC_Decoder_out1_8;
  wire NR_LDPC_Decoder_out1_9;
  wire NR_LDPC_Decoder_out1_10;
  wire NR_LDPC_Decoder_out1_11;
  wire NR_LDPC_Decoder_out1_12;
  wire NR_LDPC_Decoder_out1_13;
  wire NR_LDPC_Decoder_out1_14;
  wire NR_LDPC_Decoder_out1_15;
  wire NR_LDPC_Decoder_out1_16;
  wire NR_LDPC_Decoder_out1_17;
  wire NR_LDPC_Decoder_out1_18;
  wire NR_LDPC_Decoder_out1_19;
  wire NR_LDPC_Decoder_out1_20;
  wire NR_LDPC_Decoder_out1_21;
  wire NR_LDPC_Decoder_out1_22;
  wire NR_LDPC_Decoder_out1_23;
  wire NR_LDPC_Decoder_out1_24;
  wire NR_LDPC_Decoder_out1_25;
  wire NR_LDPC_Decoder_out1_26;
  wire NR_LDPC_Decoder_out1_27;
  wire NR_LDPC_Decoder_out1_28;
  wire NR_LDPC_Decoder_out1_29;
  wire NR_LDPC_Decoder_out1_30;
  wire NR_LDPC_Decoder_out1_31;
  wire NR_LDPC_Decoder_out1_32;
  wire NR_LDPC_Decoder_out1_33;
  wire NR_LDPC_Decoder_out1_34;
  wire NR_LDPC_Decoder_out1_35;
  wire NR_LDPC_Decoder_out1_36;
  wire NR_LDPC_Decoder_out1_37;
  wire NR_LDPC_Decoder_out1_38;
  wire NR_LDPC_Decoder_out1_39;
  wire NR_LDPC_Decoder_out1_40;
  wire NR_LDPC_Decoder_out1_41;
  wire NR_LDPC_Decoder_out1_42;
  wire NR_LDPC_Decoder_out1_43;
  wire NR_LDPC_Decoder_out1_44;
  wire NR_LDPC_Decoder_out1_45;
  wire NR_LDPC_Decoder_out1_46;
  wire NR_LDPC_Decoder_out1_47;
  wire NR_LDPC_Decoder_out1_48;
  wire NR_LDPC_Decoder_out1_49;
  wire NR_LDPC_Decoder_out1_50;
  wire NR_LDPC_Decoder_out1_51;
  wire NR_LDPC_Decoder_out1_52;
  wire NR_LDPC_Decoder_out1_53;
  wire NR_LDPC_Decoder_out1_54;
  wire NR_LDPC_Decoder_out1_55;
  wire NR_LDPC_Decoder_out1_56;
  wire NR_LDPC_Decoder_out1_57;
  wire NR_LDPC_Decoder_out1_58;
  wire NR_LDPC_Decoder_out1_59;
  wire NR_LDPC_Decoder_out1_60;
  wire NR_LDPC_Decoder_out1_61;
  wire NR_LDPC_Decoder_out1_62;
  wire NR_LDPC_Decoder_out1_63;
  wire NR_LDPC_Decoder_out2_start;
  wire NR_LDPC_Decoder_out2_end;
  wire NR_LDPC_Decoder_out2_valid;
  wire [15:0] NR_LDPC_Decoder_out3;  // uint16
  wire NR_LDPC_Decoder_out4;


  dec_NR_LDPC_Decoder u_NR_LDPC_Decoder (.clk(clk),
                                         .reset(reset),
                                         .enb(clk_enable),
                                         .in0_0(dataIn_0),  // sfix4
                                         .in0_1(dataIn_1),  // sfix4
                                         .in0_2(dataIn_2),  // sfix4
                                         .in0_3(dataIn_3),  // sfix4
                                         .in0_4(dataIn_4),  // sfix4
                                         .in0_5(dataIn_5),  // sfix4
                                         .in0_6(dataIn_6),  // sfix4
                                         .in0_7(dataIn_7),  // sfix4
                                         .in0_8(dataIn_8),  // sfix4
                                         .in0_9(dataIn_9),  // sfix4
                                         .in0_10(dataIn_10),  // sfix4
                                         .in0_11(dataIn_11),  // sfix4
                                         .in0_12(dataIn_12),  // sfix4
                                         .in0_13(dataIn_13),  // sfix4
                                         .in0_14(dataIn_14),  // sfix4
                                         .in0_15(dataIn_15),  // sfix4
                                         .in0_16(dataIn_16),  // sfix4
                                         .in0_17(dataIn_17),  // sfix4
                                         .in0_18(dataIn_18),  // sfix4
                                         .in0_19(dataIn_19),  // sfix4
                                         .in0_20(dataIn_20),  // sfix4
                                         .in0_21(dataIn_21),  // sfix4
                                         .in0_22(dataIn_22),  // sfix4
                                         .in0_23(dataIn_23),  // sfix4
                                         .in0_24(dataIn_24),  // sfix4
                                         .in0_25(dataIn_25),  // sfix4
                                         .in0_26(dataIn_26),  // sfix4
                                         .in0_27(dataIn_27),  // sfix4
                                         .in0_28(dataIn_28),  // sfix4
                                         .in0_29(dataIn_29),  // sfix4
                                         .in0_30(dataIn_30),  // sfix4
                                         .in0_31(dataIn_31),  // sfix4
                                         .in0_32(dataIn_32),  // sfix4
                                         .in0_33(dataIn_33),  // sfix4
                                         .in0_34(dataIn_34),  // sfix4
                                         .in0_35(dataIn_35),  // sfix4
                                         .in0_36(dataIn_36),  // sfix4
                                         .in0_37(dataIn_37),  // sfix4
                                         .in0_38(dataIn_38),  // sfix4
                                         .in0_39(dataIn_39),  // sfix4
                                         .in0_40(dataIn_40),  // sfix4
                                         .in0_41(dataIn_41),  // sfix4
                                         .in0_42(dataIn_42),  // sfix4
                                         .in0_43(dataIn_43),  // sfix4
                                         .in0_44(dataIn_44),  // sfix4
                                         .in0_45(dataIn_45),  // sfix4
                                         .in0_46(dataIn_46),  // sfix4
                                         .in0_47(dataIn_47),  // sfix4
                                         .in0_48(dataIn_48),  // sfix4
                                         .in0_49(dataIn_49),  // sfix4
                                         .in0_50(dataIn_50),  // sfix4
                                         .in0_51(dataIn_51),  // sfix4
                                         .in0_52(dataIn_52),  // sfix4
                                         .in0_53(dataIn_53),  // sfix4
                                         .in0_54(dataIn_54),  // sfix4
                                         .in0_55(dataIn_55),  // sfix4
                                         .in0_56(dataIn_56),  // sfix4
                                         .in0_57(dataIn_57),  // sfix4
                                         .in0_58(dataIn_58),  // sfix4
                                         .in0_59(dataIn_59),  // sfix4
                                         .in0_60(dataIn_60),  // sfix4
                                         .in0_61(dataIn_61),  // sfix4
                                         .in0_62(dataIn_62),  // sfix4
                                         .in0_63(dataIn_63),  // sfix4
                                         .in1_start(ctrlIn_start),
                                         .in1_end(ctrlIn_end),
                                         .in1_valid(ctrlIn_valid),
                                         .in2(bgn),
                                         .in3(liftingSizeIn),  // uint16
                                         .out0_0(NR_LDPC_Decoder_out1_0),  // boolean
                                         .out0_1(NR_LDPC_Decoder_out1_1),  // boolean
                                         .out0_2(NR_LDPC_Decoder_out1_2),  // boolean
                                         .out0_3(NR_LDPC_Decoder_out1_3),  // boolean
                                         .out0_4(NR_LDPC_Decoder_out1_4),  // boolean
                                         .out0_5(NR_LDPC_Decoder_out1_5),  // boolean
                                         .out0_6(NR_LDPC_Decoder_out1_6),  // boolean
                                         .out0_7(NR_LDPC_Decoder_out1_7),  // boolean
                                         .out0_8(NR_LDPC_Decoder_out1_8),  // boolean
                                         .out0_9(NR_LDPC_Decoder_out1_9),  // boolean
                                         .out0_10(NR_LDPC_Decoder_out1_10),  // boolean
                                         .out0_11(NR_LDPC_Decoder_out1_11),  // boolean
                                         .out0_12(NR_LDPC_Decoder_out1_12),  // boolean
                                         .out0_13(NR_LDPC_Decoder_out1_13),  // boolean
                                         .out0_14(NR_LDPC_Decoder_out1_14),  // boolean
                                         .out0_15(NR_LDPC_Decoder_out1_15),  // boolean
                                         .out0_16(NR_LDPC_Decoder_out1_16),  // boolean
                                         .out0_17(NR_LDPC_Decoder_out1_17),  // boolean
                                         .out0_18(NR_LDPC_Decoder_out1_18),  // boolean
                                         .out0_19(NR_LDPC_Decoder_out1_19),  // boolean
                                         .out0_20(NR_LDPC_Decoder_out1_20),  // boolean
                                         .out0_21(NR_LDPC_Decoder_out1_21),  // boolean
                                         .out0_22(NR_LDPC_Decoder_out1_22),  // boolean
                                         .out0_23(NR_LDPC_Decoder_out1_23),  // boolean
                                         .out0_24(NR_LDPC_Decoder_out1_24),  // boolean
                                         .out0_25(NR_LDPC_Decoder_out1_25),  // boolean
                                         .out0_26(NR_LDPC_Decoder_out1_26),  // boolean
                                         .out0_27(NR_LDPC_Decoder_out1_27),  // boolean
                                         .out0_28(NR_LDPC_Decoder_out1_28),  // boolean
                                         .out0_29(NR_LDPC_Decoder_out1_29),  // boolean
                                         .out0_30(NR_LDPC_Decoder_out1_30),  // boolean
                                         .out0_31(NR_LDPC_Decoder_out1_31),  // boolean
                                         .out0_32(NR_LDPC_Decoder_out1_32),  // boolean
                                         .out0_33(NR_LDPC_Decoder_out1_33),  // boolean
                                         .out0_34(NR_LDPC_Decoder_out1_34),  // boolean
                                         .out0_35(NR_LDPC_Decoder_out1_35),  // boolean
                                         .out0_36(NR_LDPC_Decoder_out1_36),  // boolean
                                         .out0_37(NR_LDPC_Decoder_out1_37),  // boolean
                                         .out0_38(NR_LDPC_Decoder_out1_38),  // boolean
                                         .out0_39(NR_LDPC_Decoder_out1_39),  // boolean
                                         .out0_40(NR_LDPC_Decoder_out1_40),  // boolean
                                         .out0_41(NR_LDPC_Decoder_out1_41),  // boolean
                                         .out0_42(NR_LDPC_Decoder_out1_42),  // boolean
                                         .out0_43(NR_LDPC_Decoder_out1_43),  // boolean
                                         .out0_44(NR_LDPC_Decoder_out1_44),  // boolean
                                         .out0_45(NR_LDPC_Decoder_out1_45),  // boolean
                                         .out0_46(NR_LDPC_Decoder_out1_46),  // boolean
                                         .out0_47(NR_LDPC_Decoder_out1_47),  // boolean
                                         .out0_48(NR_LDPC_Decoder_out1_48),  // boolean
                                         .out0_49(NR_LDPC_Decoder_out1_49),  // boolean
                                         .out0_50(NR_LDPC_Decoder_out1_50),  // boolean
                                         .out0_51(NR_LDPC_Decoder_out1_51),  // boolean
                                         .out0_52(NR_LDPC_Decoder_out1_52),  // boolean
                                         .out0_53(NR_LDPC_Decoder_out1_53),  // boolean
                                         .out0_54(NR_LDPC_Decoder_out1_54),  // boolean
                                         .out0_55(NR_LDPC_Decoder_out1_55),  // boolean
                                         .out0_56(NR_LDPC_Decoder_out1_56),  // boolean
                                         .out0_57(NR_LDPC_Decoder_out1_57),  // boolean
                                         .out0_58(NR_LDPC_Decoder_out1_58),  // boolean
                                         .out0_59(NR_LDPC_Decoder_out1_59),  // boolean
                                         .out0_60(NR_LDPC_Decoder_out1_60),  // boolean
                                         .out0_61(NR_LDPC_Decoder_out1_61),  // boolean
                                         .out0_62(NR_LDPC_Decoder_out1_62),  // boolean
                                         .out0_63(NR_LDPC_Decoder_out1_63),  // boolean
                                         .out1_start(NR_LDPC_Decoder_out2_start),
                                         .out1_end(NR_LDPC_Decoder_out2_end),
                                         .out1_valid(NR_LDPC_Decoder_out2_valid),
                                         .out2(NR_LDPC_Decoder_out3),  // uint16
                                         .out3(NR_LDPC_Decoder_out4)
                                         );

  assign dataOut_0 = NR_LDPC_Decoder_out1_0;

  assign dataOut_1 = NR_LDPC_Decoder_out1_1;

  assign dataOut_2 = NR_LDPC_Decoder_out1_2;

  assign dataOut_3 = NR_LDPC_Decoder_out1_3;

  assign dataOut_4 = NR_LDPC_Decoder_out1_4;

  assign dataOut_5 = NR_LDPC_Decoder_out1_5;

  assign dataOut_6 = NR_LDPC_Decoder_out1_6;

  assign dataOut_7 = NR_LDPC_Decoder_out1_7;

  assign dataOut_8 = NR_LDPC_Decoder_out1_8;

  assign dataOut_9 = NR_LDPC_Decoder_out1_9;

  assign dataOut_10 = NR_LDPC_Decoder_out1_10;

  assign dataOut_11 = NR_LDPC_Decoder_out1_11;

  assign dataOut_12 = NR_LDPC_Decoder_out1_12;

  assign dataOut_13 = NR_LDPC_Decoder_out1_13;

  assign dataOut_14 = NR_LDPC_Decoder_out1_14;

  assign dataOut_15 = NR_LDPC_Decoder_out1_15;

  assign dataOut_16 = NR_LDPC_Decoder_out1_16;

  assign dataOut_17 = NR_LDPC_Decoder_out1_17;

  assign dataOut_18 = NR_LDPC_Decoder_out1_18;

  assign dataOut_19 = NR_LDPC_Decoder_out1_19;

  assign dataOut_20 = NR_LDPC_Decoder_out1_20;

  assign dataOut_21 = NR_LDPC_Decoder_out1_21;

  assign dataOut_22 = NR_LDPC_Decoder_out1_22;

  assign dataOut_23 = NR_LDPC_Decoder_out1_23;

  assign dataOut_24 = NR_LDPC_Decoder_out1_24;

  assign dataOut_25 = NR_LDPC_Decoder_out1_25;

  assign dataOut_26 = NR_LDPC_Decoder_out1_26;

  assign dataOut_27 = NR_LDPC_Decoder_out1_27;

  assign dataOut_28 = NR_LDPC_Decoder_out1_28;

  assign dataOut_29 = NR_LDPC_Decoder_out1_29;

  assign dataOut_30 = NR_LDPC_Decoder_out1_30;

  assign dataOut_31 = NR_LDPC_Decoder_out1_31;

  assign dataOut_32 = NR_LDPC_Decoder_out1_32;

  assign dataOut_33 = NR_LDPC_Decoder_out1_33;

  assign dataOut_34 = NR_LDPC_Decoder_out1_34;

  assign dataOut_35 = NR_LDPC_Decoder_out1_35;

  assign dataOut_36 = NR_LDPC_Decoder_out1_36;

  assign dataOut_37 = NR_LDPC_Decoder_out1_37;

  assign dataOut_38 = NR_LDPC_Decoder_out1_38;

  assign dataOut_39 = NR_LDPC_Decoder_out1_39;

  assign dataOut_40 = NR_LDPC_Decoder_out1_40;

  assign dataOut_41 = NR_LDPC_Decoder_out1_41;

  assign dataOut_42 = NR_LDPC_Decoder_out1_42;

  assign dataOut_43 = NR_LDPC_Decoder_out1_43;

  assign dataOut_44 = NR_LDPC_Decoder_out1_44;

  assign dataOut_45 = NR_LDPC_Decoder_out1_45;

  assign dataOut_46 = NR_LDPC_Decoder_out1_46;

  assign dataOut_47 = NR_LDPC_Decoder_out1_47;

  assign dataOut_48 = NR_LDPC_Decoder_out1_48;

  assign dataOut_49 = NR_LDPC_Decoder_out1_49;

  assign dataOut_50 = NR_LDPC_Decoder_out1_50;

  assign dataOut_51 = NR_LDPC_Decoder_out1_51;

  assign dataOut_52 = NR_LDPC_Decoder_out1_52;

  assign dataOut_53 = NR_LDPC_Decoder_out1_53;

  assign dataOut_54 = NR_LDPC_Decoder_out1_54;

  assign dataOut_55 = NR_LDPC_Decoder_out1_55;

  assign dataOut_56 = NR_LDPC_Decoder_out1_56;

  assign dataOut_57 = NR_LDPC_Decoder_out1_57;

  assign dataOut_58 = NR_LDPC_Decoder_out1_58;

  assign dataOut_59 = NR_LDPC_Decoder_out1_59;

  assign dataOut_60 = NR_LDPC_Decoder_out1_60;

  assign dataOut_61 = NR_LDPC_Decoder_out1_61;

  assign dataOut_62 = NR_LDPC_Decoder_out1_62;

  assign dataOut_63 = NR_LDPC_Decoder_out1_63;

  assign ctrlOut_start = NR_LDPC_Decoder_out2_start;

  assign ctrlOut_end = NR_LDPC_Decoder_out2_end;

  assign ctrlOut_valid = NR_LDPC_Decoder_out2_valid;

  assign liftingSizeOut = NR_LDPC_Decoder_out3;

  assign nextFrame = NR_LDPC_Decoder_out4;

  assign ce_out = clk_enable;

endmodule  // dec_HDL_Algorithm

