// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRLDPCDecoderHDL\dec_FinalShifts.v
// Created: 2026-06-03 20:19:59
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec_FinalShifts
// Source Path: NRLDPCDecoderHDL/HDL Algorithm/NR LDPC Decoder/DecoderCore/CheckMatrixLUT/FinalShifts
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec_FinalShifts
          (fAddr,
           fShift_0,
           fShift_1,
           fShift_2,
           fShift_3,
           fShift_4,
           fShift_5,
           fShift_6,
           fShift_7,
           fShift_8,
           fShift_9,
           fShift_10,
           fShift_11,
           fShift_12,
           fShift_13,
           fShift_14,
           fShift_15,
           fShift_16,
           fShift_17,
           fShift_18,
           fShift_19,
           fShift_20,
           fShift_21);


  input   [6:0] fAddr;  // ufix7
  output  [8:0] fShift_0;  // ufix9
  output  [8:0] fShift_1;  // ufix9
  output  [8:0] fShift_2;  // ufix9
  output  [8:0] fShift_3;  // ufix9
  output  [8:0] fShift_4;  // ufix9
  output  [8:0] fShift_5;  // ufix9
  output  [8:0] fShift_6;  // ufix9
  output  [8:0] fShift_7;  // ufix9
  output  [8:0] fShift_8;  // ufix9
  output  [8:0] fShift_9;  // ufix9
  output  [8:0] fShift_10;  // ufix9
  output  [8:0] fShift_11;  // ufix9
  output  [8:0] fShift_12;  // ufix9
  output  [8:0] fShift_13;  // ufix9
  output  [8:0] fShift_14;  // ufix9
  output  [8:0] fShift_15;  // ufix9
  output  [8:0] fShift_16;  // ufix9
  output  [8:0] fShift_17;  // ufix9
  output  [8:0] fShift_18;  // ufix9
  output  [8:0] fShift_19;  // ufix9
  output  [8:0] fShift_20;  // ufix9
  output  [8:0] fShift_21;  // ufix9


  wire [44:0] LUT1_table_data [0:127];  // ufix45 [128]
  wire [44:0] vLUT1;  // ufix45
  wire [8:0] fShift_1_1;  // ufix9
  wire [8:0] fShift_2_1;  // ufix9
  wire [8:0] fShift_3_1;  // ufix9
  wire [8:0] fShift_4_1;  // ufix9
  wire [8:0] fShift_5_1;  // ufix9
  wire [44:0] LUT2_table_data [0:127];  // ufix45 [128]
  wire [44:0] vLUT2;  // ufix45
  wire [8:0] fShift_6_1;  // ufix9
  wire [8:0] fShift_7_1;  // ufix9
  wire [8:0] fShift_8_1;  // ufix9
  wire [8:0] fShift_9_1;  // ufix9
  wire [8:0] fShift_10_1;  // ufix9
  wire [44:0] LUT3_table_data [0:127];  // ufix45 [128]
  wire [44:0] vLUT3;  // ufix45
  wire [8:0] fShift_11_1;  // ufix9
  wire [8:0] fShift_12_1;  // ufix9
  wire [8:0] fShift_13_1;  // ufix9
  wire [8:0] fShift_14_1;  // ufix9
  wire [8:0] fShift_15_1;  // ufix9
  wire [44:0] LUT4_table_data [0:127];  // ufix45 [128]
  wire [44:0] vLUT4;  // ufix45
  wire [8:0] fShift_16_1;  // ufix9
  wire [8:0] fShift_17_1;  // ufix9
  wire [8:0] fShift_18_1;  // ufix9
  wire [8:0] fShift_19_1;  // ufix9
  wire [8:0] fShift_20_1;  // ufix9
  wire [17:0] LUT5_table_data [0:127];  // ufix18 [128]
  wire [17:0] vLUT5;  // ufix18
  wire [8:0] fShift_21_1;  // ufix9
  wire [8:0] fShift_22;  // ufix9


  assign LUT1_table_data[0] = 45'h001008040201;
  assign LUT1_table_data[1] = 45'h0010080C0203;
  assign LUT1_table_data[2] = 45'h0050280C0A03;
  assign LUT1_table_data[3] = 45'h00D0682C0A0B;
  assign LUT1_table_data[4] = 45'h01D0686C2A0B;
  assign LUT1_table_data[5] = 45'h01D168EC2A0B;
  assign LUT1_table_data[6] = 45'h01D168EC2A0B;
  assign LUT1_table_data[7] = 45'h09D56AED2A8B;
  assign LUT1_table_data[8] = 45'h002010080002;
  assign LUT1_table_data[9] = 45'h002010080602;
  assign LUT1_table_data[10] = 45'h002010200608;
  assign LUT1_table_data[11] = 45'h00E010201E08;
  assign LUT1_table_data[12] = 45'h00E0D0204E20;
  assign LUT1_table_data[13] = 45'h00E0D0204E50;
  assign LUT1_table_data[14] = 45'h00E3D0210E50;
  assign LUT1_table_data[15] = 45'h00E9D0210E50;
  assign LUT1_table_data[16] = 45'h000010000204;
  assign LUT1_table_data[17] = 45'h005038000204;
  assign LUT1_table_data[18] = 45'h00503800020E;
  assign LUT1_table_data[19] = 45'h019038502A22;
  assign LUT1_table_data[20] = 45'h041178502A4A;
  assign LUT1_table_data[21] = 45'h04117850CA4A;
  assign LUT1_table_data[22] = 45'h04117850CAEA;
  assign LUT1_table_data[23] = 45'h04117850CAEA;
  assign LUT1_table_data[24] = 45'h000028000400;
  assign LUT1_table_data[25] = 45'h0070281C0400;
  assign LUT1_table_data[26] = 45'h007098542000;
  assign LUT1_table_data[27] = 45'h023178C4201C;
  assign LUT1_table_data[28] = 45'h05B338C49054;
  assign LUT1_table_data[29] = 45'h05B6B8C57054;
  assign LUT1_table_data[30] = 45'h05B6B8C57054;
  assign LUT1_table_data[31] = 45'h05B6B8C57054;
  assign LUT1_table_data[32] = 45'h000000000C00;
  assign LUT1_table_data[33] = 45'h000000000C00;
  assign LUT1_table_data[34] = 45'h000000003012;
  assign LUT1_table_data[35] = 45'h000000003012;
  assign LUT1_table_data[36] = 45'h000000003012;
  assign LUT1_table_data[37] = 45'h000000015012;
  assign LUT1_table_data[38] = 45'h000000015012;
  assign LUT1_table_data[39] = 45'h000000015012;
  assign LUT1_table_data[40] = 45'h0060001C0A02;
  assign LUT1_table_data[41] = 45'h01105848200D;
  assign LUT1_table_data[42] = 45'h027108A04C23;
  assign LUT1_table_data[43] = 45'h053268A0A44F;
  assign LUT1_table_data[44] = 45'h05326A00A44F;
  assign LUT1_table_data[45] = 45'h05326CC0A44F;
  assign LUT1_table_data[46] = 45'h05326CC0A44F;
  assign LUT1_table_data[47] = 45'h05326CC0A44F;
  assign LUT1_table_data[48] = 45'h00A050101804;
  assign LUT1_table_data[49] = 45'h00A0B8103204;
  assign LUT1_table_data[50] = 45'h00A0B8783204;
  assign LUT1_table_data[51] = 45'h00A258789A04;
  assign LUT1_table_data[52] = 45'h00A258796A04;
  assign LUT1_table_data[53] = 45'h00A258796A04;
  assign LUT1_table_data[54] = 45'h00A258796A04;
  assign LUT1_table_data[55] = 45'h00A258796A04;
  assign LUT1_table_data[56] = 45'h00504830180B;
  assign LUT1_table_data[57] = 45'h01404830360B;
  assign LUT1_table_data[58] = 45'h03204830720B;
  assign LUT1_table_data[59] = 45'h032228307247;
  assign LUT1_table_data[60] = 45'h0AA5EA1162BF;
  assign LUT1_table_data[61] = 45'h0AA5EA1162BF;
  assign LUT1_table_data[62] = 45'h0AA5EA1162BF;
  assign LUT1_table_data[63] = 45'h0AA5EA1162BF;
  assign LUT1_table_data[64] = 45'h000008000201;
  assign LUT1_table_data[65] = 45'h000018000203;
  assign LUT1_table_data[66] = 45'h004018000207;
  assign LUT1_table_data[67] = 45'h00C05800020F;
  assign LUT1_table_data[68] = 45'h01C05800020F;
  assign LUT1_table_data[69] = 45'h01C15800022F;
  assign LUT1_table_data[70] = 45'h01C35800026F;
  assign LUT1_table_data[71] = 45'h01C7580102EF;
  assign LUT1_table_data[72] = 45'h002010040000;
  assign LUT1_table_data[73] = 45'h005010040603;
  assign LUT1_table_data[74] = 45'h0050101C0609;
  assign LUT1_table_data[75] = 45'h0110701C0615;
  assign LUT1_table_data[76] = 45'h0111301C062D;
  assign LUT1_table_data[77] = 45'h0112B01C665D;
  assign LUT1_table_data[78] = 45'h0112B19D265D;
  assign LUT1_table_data[79] = 45'h0112B19D265D;
  assign LUT1_table_data[80] = 45'h004000000000;
  assign LUT1_table_data[81] = 45'h004028000000;
  assign LUT1_table_data[82] = 45'h00E078000000;
  assign LUT1_table_data[83] = 45'h022118000000;
  assign LUT1_table_data[84] = 45'h04A258000000;
  assign LUT1_table_data[85] = 45'h09A258000000;
  assign LUT1_table_data[86] = 45'h09A258000000;
  assign LUT1_table_data[87] = 45'h09A258000000;
  assign LUT1_table_data[88] = 45'h005028000201;
  assign LUT1_table_data[89] = 45'h005060001008;
  assign LUT1_table_data[90] = 45'h0050D0381016;
  assign LUT1_table_data[91] = 45'h0051B0A81032;
  assign LUT1_table_data[92] = 45'h03D1B188106A;
  assign LUT1_table_data[93] = 45'h03D1B188F06A;
  assign LUT1_table_data[94] = 45'h03D1B188F06A;
  assign LUT1_table_data[95] = 45'h03D1B188F06A;
  assign LUT1_table_data[96] = 45'h007038180602;
  assign LUT1_table_data[97] = 45'h00703818180B;
  assign LUT1_table_data[98] = 45'h01903818180B;
  assign LUT1_table_data[99] = 45'h01915818602F;
  assign LUT1_table_data[100] = 45'h019398186077;
  assign LUT1_table_data[101] = 45'h019398186077;
  assign LUT1_table_data[102] = 45'h019398186077;
  assign LUT1_table_data[103] = 45'h019398186077;
  assign LUT1_table_data[104] = 45'h00700018000A;
  assign LUT1_table_data[105] = 45'h007000180015;
  assign LUT1_table_data[106] = 45'h01D000700015;
  assign LUT1_table_data[107] = 45'h049161205815;
  assign LUT1_table_data[108] = 45'h0A142281086D;
  assign LUT1_table_data[109] = 45'h0A142281086D;
  assign LUT1_table_data[110] = 45'h0A142281086D;
  assign LUT1_table_data[111] = 45'h0A142281086D;
  assign LUT1_table_data[112] = 45'h0010082C120C;
  assign LUT1_table_data[113] = 45'h0010702C1219;
  assign LUT1_table_data[114] = 45'h01B070944619;
  assign LUT1_table_data[115] = 45'h01B21164AE4D;
  assign LUT1_table_data[116] = 45'h01B553057EB5;
  assign LUT1_table_data[117] = 45'h01B553057EB5;
  assign LUT1_table_data[118] = 45'h01B553057EB5;
  assign LUT1_table_data[119] = 45'h01B553057EB5;
  assign LUT1_table_data[120] = 45'h00C0200C1002;
  assign LUT1_table_data[121] = 45'h01B020482E11;
  assign LUT1_table_data[122] = 45'h039110486A2F;
  assign LUT1_table_data[123] = 45'h0392F1386A2F;
  assign LUT1_table_data[124] = 45'h0392F1386AA7;
  assign LUT1_table_data[125] = 45'h0392F1386AA7;
  assign LUT1_table_data[126] = 45'h0392F1386AA7;
  assign LUT1_table_data[127] = 45'h0392F1386AA7;
  assign vLUT1 = LUT1_table_data[fAddr];

  assign fShift_1_1 = vLUT1[8:0];

  assign fShift_0 = fShift_1_1;

  assign fShift_2_1 = vLUT1[17:9];

  assign fShift_1 = fShift_2_1;

  assign fShift_3_1 = vLUT1[26:18];

  assign fShift_2 = fShift_3_1;

  assign fShift_4_1 = vLUT1[35:27];

  assign fShift_3 = fShift_4_1;

  assign fShift_5_1 = vLUT1[44:36];

  assign fShift_4 = fShift_5_1;

  assign LUT2_table_data[0] = 45'h001008040201;
  assign LUT2_table_data[1] = 45'h003008040601;
  assign LUT2_table_data[2] = 45'h003008140E01;
  assign LUT2_table_data[3] = 45'h003048340E09;
  assign LUT2_table_data[4] = 45'h003048742E19;
  assign LUT2_table_data[5] = 45'h023048742E39;
  assign LUT2_table_data[6] = 45'h023048742E79;
  assign LUT2_table_data[7] = 45'h0A344A752E79;
  assign LUT2_table_data[8] = 45'h001008000400;
  assign LUT2_table_data[9] = 45'h001008000A00;
  assign LUT2_table_data[10] = 45'h007008180A06;
  assign LUT2_table_data[11] = 45'h013068180A06;
  assign LUT2_table_data[12] = 45'h013128780A06;
  assign LUT2_table_data[13] = 45'h043129386A06;
  assign LUT2_table_data[14] = 45'h0A3129392A66;
  assign LUT2_table_data[15] = 45'h0A3129392A66;
  assign LUT2_table_data[16] = 45'h004000080600;
  assign LUT2_table_data[17] = 45'h0090001C1005;
  assign LUT2_table_data[18] = 45'h0130001C100F;
  assign LUT2_table_data[19] = 45'h0130006C380F;
  assign LUT2_table_data[20] = 45'h0130010C880F;
  assign LUT2_table_data[21] = 45'h0632810C880F;
  assign LUT2_table_data[22] = 45'h1032838DC8AF;
  assign LUT2_table_data[23] = 45'h1032838DC8AF;
  assign LUT2_table_data[24] = 45'h002018100405;
  assign LUT2_table_data[25] = 45'h009018101205;
  assign LUT2_table_data[26] = 45'h009088101213;
  assign LUT2_table_data[27] = 45'h009168101213;
  assign LUT2_table_data[28] = 45'h009168101213;
  assign LUT2_table_data[29] = 45'h00916810F283;
  assign LUT2_table_data[30] = 45'h00916810F283;
  assign LUT2_table_data[31] = 45'h00916810F283;
  assign LUT2_table_data[32] = 45'h000000000001;
  assign LUT2_table_data[33] = 45'h00000000000A;
  assign LUT2_table_data[34] = 45'h00000000000A;
  assign LUT2_table_data[35] = 45'h00000000002E;
  assign LUT2_table_data[36] = 45'h00000000002E;
  assign LUT2_table_data[37] = 45'h00048000002E;
  assign LUT2_table_data[38] = 45'h00048000002E;
  assign LUT2_table_data[39] = 45'h00048000002E;
  assign LUT2_table_data[40] = 45'h007030080200;
  assign LUT2_table_data[41] = 45'h007088080200;
  assign LUT2_table_data[42] = 45'h01D088602E00;
  assign LUT2_table_data[43] = 45'h01D1E9108600;
  assign LUT2_table_data[44] = 45'h0751E9108658;
  assign LUT2_table_data[45] = 45'h12576BD08708;
  assign LUT2_table_data[46] = 45'h12576BD08708;
  assign LUT2_table_data[47] = 45'h12576BD08708;
  assign LUT2_table_data[48] = 45'h00C030180C08;
  assign LUT2_table_data[49] = 45'h00C030182608;
  assign LUT2_table_data[50] = 45'h026100185A22;
  assign LUT2_table_data[51] = 45'h0262A0185A56;
  assign LUT2_table_data[52] = 45'h08E2A0185A56;
  assign LUT2_table_data[53] = 45'h08E2A0185A56;
  assign LUT2_table_data[54] = 45'h08E2A0185A56;
  assign LUT2_table_data[55] = 45'h08E2A0185A56;
  assign LUT2_table_data[56] = 45'h007068041202;
  assign LUT2_table_data[57] = 45'h007068043002;
  assign LUT2_table_data[58] = 45'h0071587C6C02;
  assign LUT2_table_data[59] = 45'h0433396CE402;
  assign LUT2_table_data[60] = 45'h0BB33B4CE47A;
  assign LUT2_table_data[61] = 45'h0BB33B4CE47A;
  assign LUT2_table_data[62] = 45'h0BB33B4CE47A;
  assign LUT2_table_data[63] = 45'h0BB33B4CE47A;
  assign LUT2_table_data[64] = 45'h000000000201;
  assign LUT2_table_data[65] = 45'h000010000601;
  assign LUT2_table_data[66] = 45'h004010100E05;
  assign LUT2_table_data[67] = 45'h004050300E05;
  assign LUT2_table_data[68] = 45'h014050302E05;
  assign LUT2_table_data[69] = 45'h014150B02E25;
  assign LUT2_table_data[70] = 45'h054150B02E65;
  assign LUT2_table_data[71] = 45'h054152B12EE5;
  assign LUT2_table_data[72] = 45'h002008000401;
  assign LUT2_table_data[73] = 45'h002008000401;
  assign LUT2_table_data[74] = 45'h008038000407;
  assign LUT2_table_data[75] = 45'h008038300407;
  assign LUT2_table_data[76] = 45'h0080F8900407;
  assign LUT2_table_data[77] = 45'h038278906407;
  assign LUT2_table_data[78] = 45'h03857A106407;
  assign LUT2_table_data[79] = 45'h03857A106407;
  assign LUT2_table_data[80] = 45'h004010100402;
  assign LUT2_table_data[81] = 45'h004038100402;
  assign LUT2_table_data[82] = 45'h00E088101802;
  assign LUT2_table_data[83] = 45'h00E088604002;
  assign LUT2_table_data[84] = 45'h036088604002;
  assign LUT2_table_data[85] = 45'h086088604002;
  assign LUT2_table_data[86] = 45'h086088604002;
  assign LUT2_table_data[87] = 45'h086088604002;
  assign LUT2_table_data[88] = 45'h001008180C03;
  assign LUT2_table_data[89] = 45'h008008340C03;
  assign LUT2_table_data[90] = 45'h008078340C11;
  assign LUT2_table_data[91] = 45'h008158340C2D;
  assign LUT2_table_data[92] = 45'h040159140C65;
  assign LUT2_table_data[93] = 45'h0B015AD4EC65;
  assign LUT2_table_data[94] = 45'h0B015AD4EC65;
  assign LUT2_table_data[95] = 45'h0B015AD4EC65;
  assign LUT2_table_data[96] = 45'h007018140202;
  assign LUT2_table_data[97] = 45'h01001838140B;
  assign LUT2_table_data[98] = 45'h02201880140B;
  assign LUT2_table_data[99] = 45'h04601880142F;
  assign LUT2_table_data[100] = 45'h04625880142F;
  assign LUT2_table_data[101] = 45'h04625880142F;
  assign LUT2_table_data[102] = 45'h04625880142F;
  assign LUT2_table_data[103] = 45'h04625880142F;
  assign LUT2_table_data[104] = 45'h007008180A06;
  assign LUT2_table_data[105] = 45'h007060182006;
  assign LUT2_table_data[106] = 45'h01D110182006;
  assign LUT2_table_data[107] = 45'h01D270182006;
  assign LUT2_table_data[108] = 45'h01D53018D006;
  assign LUT2_table_data[109] = 45'h01D53018D006;
  assign LUT2_table_data[110] = 45'h01D53018D006;
  assign LUT2_table_data[111] = 45'h01D53018D006;
  assign LUT2_table_data[112] = 45'h006028041602;
  assign LUT2_table_data[113] = 45'h00609004160F;
  assign LUT2_table_data[114] = 45'h006090044A29;
  assign LUT2_table_data[115] = 45'h006090D4B25D;
  assign LUT2_table_data[116] = 45'h0063D27582C5;
  assign LUT2_table_data[117] = 45'h0063D27582C5;
  assign LUT2_table_data[118] = 45'h0063D27582C5;
  assign LUT2_table_data[119] = 45'h0063D27582C5;
  assign LUT2_table_data[120] = 45'h002068000205;
  assign LUT2_table_data[121] = 45'h0110683C0205;
  assign LUT2_table_data[122] = 45'h011068B40223;
  assign LUT2_table_data[123] = 45'h011068B47A5F;
  assign LUT2_table_data[124] = 45'h011068B56AD7;
  assign LUT2_table_data[125] = 45'h011068B56AD7;
  assign LUT2_table_data[126] = 45'h011068B56AD7;
  assign LUT2_table_data[127] = 45'h011068B56AD7;
  assign vLUT2 = LUT2_table_data[fAddr];

  assign fShift_6_1 = vLUT2[8:0];

  assign fShift_5 = fShift_6_1;

  assign fShift_7_1 = vLUT2[17:9];

  assign fShift_6 = fShift_7_1;

  assign fShift_8_1 = vLUT2[26:18];

  assign fShift_7 = fShift_8_1;

  assign fShift_9_1 = vLUT2[35:27];

  assign fShift_8 = fShift_9_1;

  assign fShift_10_1 = vLUT2[44:36];

  assign fShift_9 = fShift_10_1;

  assign LUT3_table_data[0] = 45'h001000040201;
  assign LUT3_table_data[1] = 45'h0010000C0203;
  assign LUT3_table_data[2] = 45'h0010200C0207;
  assign LUT3_table_data[3] = 45'h0090600C1207;
  assign LUT3_table_data[4] = 45'h0090E00C1207;
  assign LUT3_table_data[5] = 45'h0290E08C5227;
  assign LUT3_table_data[6] = 45'h0692E08C5227;
  assign LUT3_table_data[7] = 45'h0696E28C52A7;
  assign LUT3_table_data[8] = 45'h001008040200;
  assign LUT3_table_data[9] = 45'h001020100203;
  assign LUT3_table_data[10] = 45'h001050280203;
  assign LUT3_table_data[11] = 45'h00105058020F;
  assign LUT3_table_data[12] = 45'h01911058320F;
  assign LUT3_table_data[13] = 45'h01929058920F;
  assign LUT3_table_data[14] = 45'h07929059520F;
  assign LUT3_table_data[15] = 45'h1392935AD20F;
  assign LUT3_table_data[16] = 45'h004000040001;
  assign LUT3_table_data[17] = 45'h009028040006;
  assign LUT3_table_data[18] = 45'h013078040006;
  assign LUT3_table_data[19] = 45'h013078542806;
  assign LUT3_table_data[20] = 45'h01307854782E;
  assign LUT3_table_data[21] = 45'h01307855187E;
  assign LUT3_table_data[22] = 45'h0B307AD5187E;
  assign LUT3_table_data[23] = 45'h0B307AD5187E;
  assign LUT3_table_data[24] = 45'h0030300C0001;
  assign LUT3_table_data[25] = 45'h003068280E01;
  assign LUT3_table_data[26] = 45'h0110D8282A01;
  assign LUT3_table_data[27] = 45'h02D0D828621D;
  assign LUT3_table_data[28] = 45'h02D29828621D;
  assign LUT3_table_data[29] = 45'h09D61829421D;
  assign LUT3_table_data[30] = 45'h09D61829421D;
  assign LUT3_table_data[31] = 45'h09D61829421D;
  assign LUT3_table_data[32] = 45'h007000000800;
  assign LUT3_table_data[33] = 45'h010000000800;
  assign LUT3_table_data[34] = 45'h010000000800;
  assign LUT3_table_data[35] = 45'h010000000800;
  assign LUT3_table_data[36] = 45'h010000009800;
  assign LUT3_table_data[37] = 45'h010480009890;
  assign LUT3_table_data[38] = 45'h010480009890;
  assign LUT3_table_data[39] = 45'h010480009890;
  assign LUT3_table_data[40] = 45'h004028101204;
  assign LUT3_table_data[41] = 45'h00F08010120F;
  assign LUT3_table_data[42] = 45'h00F08068120F;
  assign LUT3_table_data[43] = 45'h00F1E1186A3B;
  assign LUT3_table_data[44] = 45'h00F1E1191A3B;
  assign LUT3_table_data[45] = 45'h00F763D91AEB;
  assign LUT3_table_data[46] = 45'h00F763D91AEB;
  assign LUT3_table_data[47] = 45'h00F763D91AEB;
  assign LUT3_table_data[48] = 45'h005010240C0A;
  assign LUT3_table_data[49] = 45'h012010580C17;
  assign LUT3_table_data[50] = 45'h02C010C00C31;
  assign LUT3_table_data[51] = 45'h060011900C31;
  assign LUT3_table_data[52] = 45'h0C8011900C99;
  assign LUT3_table_data[53] = 45'h0C8011900C99;
  assign LUT3_table_data[54] = 45'h0C8011900C99;
  assign LUT3_table_data[55] = 45'h0C8011900C99;
  assign LUT3_table_data[56] = 45'h00C048140E03;
  assign LUT3_table_data[57] = 45'h01B0C0502C03;
  assign LUT3_table_data[58] = 45'h01B0C0506821;
  assign LUT3_table_data[59] = 45'h0572A050685D;
  assign LUT3_table_data[60] = 45'h0CF66231585D;
  assign LUT3_table_data[61] = 45'h0CF66231585D;
  assign LUT3_table_data[62] = 45'h0CF66231585D;
  assign LUT3_table_data[63] = 45'h0CF66231585D;
  assign LUT3_table_data[64] = 45'h000000000001;
  assign LUT3_table_data[65] = 45'h000000080403;
  assign LUT3_table_data[66] = 45'h000000080C03;
  assign LUT3_table_data[67] = 45'h000040080C0B;
  assign LUT3_table_data[68] = 45'h0000C0082C0B;
  assign LUT3_table_data[69] = 45'h0001C0886C0B;
  assign LUT3_table_data[70] = 45'h0003C088EC4B;
  assign LUT3_table_data[71] = 45'h0003C088EC4B;
  assign LUT3_table_data[72] = 45'h000008000002;
  assign LUT3_table_data[73] = 45'h0000080C0005;
  assign LUT3_table_data[74] = 45'h00003824000B;
  assign LUT3_table_data[75] = 45'h00009824180B;
  assign LUT3_table_data[76] = 45'h00009824180B;
  assign LUT3_table_data[77] = 45'h000218E4780B;
  assign LUT3_table_data[78] = 45'h000518E4786B;
  assign LUT3_table_data[79] = 45'h000518E4786B;
  assign LUT3_table_data[80] = 45'h0000180C0001;
  assign LUT3_table_data[81] = 45'h000018200A06;
  assign LUT3_table_data[82] = 45'h000018481E10;
  assign LUT3_table_data[83] = 45'h0000B8481E24;
  assign LUT3_table_data[84] = 45'h0001F8E86E24;
  assign LUT3_table_data[85] = 45'h00047A286E24;
  assign LUT3_table_data[86] = 45'h00047A286E24;
  assign LUT3_table_data[87] = 45'h00047A286E24;
  assign LUT3_table_data[88] = 45'h000008000800;
  assign LUT3_table_data[89] = 45'h000040001607;
  assign LUT3_table_data[90] = 45'h000040383207;
  assign LUT3_table_data[91] = 45'h000120A83223;
  assign LUT3_table_data[92] = 45'h000120A8A223;
  assign LUT3_table_data[93] = 45'h00012268A223;
  assign LUT3_table_data[94] = 45'h00012268A223;
  assign LUT3_table_data[95] = 45'h00012268A223;
  assign LUT3_table_data[96] = 45'h0000181C0201;
  assign LUT3_table_data[97] = 45'h000060400201;
  assign LUT3_table_data[98] = 45'h0000F0882601;
  assign LUT3_table_data[99] = 45'h0000F1182601;
  assign LUT3_table_data[100] = 45'h000332382649;
  assign LUT3_table_data[101] = 45'h000332382649;
  assign LUT3_table_data[102] = 45'h000332382649;
  assign LUT3_table_data[103] = 45'h000332382649;
  assign LUT3_table_data[104] = 45'h000028181002;
  assign LUT3_table_data[105] = 45'h000080441002;
  assign LUT3_table_data[106] = 45'h000130441018;
  assign LUT3_table_data[107] = 45'h000290441044;
  assign LUT3_table_data[108] = 45'h000291A4109C;
  assign LUT3_table_data[109] = 45'h000291A4109C;
  assign LUT3_table_data[110] = 45'h000291A4109C;
  assign LUT3_table_data[111] = 45'h000291A4109C;
  assign LUT3_table_data[112] = 45'h000050101607;
  assign LUT3_table_data[113] = 45'h0000B8441607;
  assign LUT3_table_data[114] = 45'h0000B8441607;
  assign LUT3_table_data[115] = 45'h000259147E3B;
  assign LUT3_table_data[116] = 45'h00059AB54EA3;
  assign LUT3_table_data[117] = 45'h00059AB54EA3;
  assign LUT3_table_data[118] = 45'h00059AB54EA3;
  assign LUT3_table_data[119] = 45'h00059AB54EA3;
  assign LUT3_table_data[120] = 45'h000000240A07;
  assign LUT3_table_data[121] = 45'h000000242807;
  assign LUT3_table_data[122] = 45'h000000246407;
  assign LUT3_table_data[123] = 45'h0001E114DC43;
  assign LUT3_table_data[124] = 45'h0005A2F5CC43;
  assign LUT3_table_data[125] = 45'h0005A2F5CC43;
  assign LUT3_table_data[126] = 45'h0005A2F5CC43;
  assign LUT3_table_data[127] = 45'h0005A2F5CC43;
  assign vLUT3 = LUT3_table_data[fAddr];

  assign fShift_11_1 = vLUT3[8:0];

  assign fShift_10 = fShift_11_1;

  assign fShift_12_1 = vLUT3[17:9];

  assign fShift_11 = fShift_12_1;

  assign fShift_13_1 = vLUT3[26:18];

  assign fShift_12 = fShift_13_1;

  assign fShift_14_1 = vLUT3[35:27];

  assign fShift_13 = fShift_14_1;

  assign fShift_15_1 = vLUT3[44:36];

  assign fShift_14 = fShift_15_1;

  assign LUT4_table_data[0] = 45'h000008040201;
  assign LUT4_table_data[1] = 45'h000008040603;
  assign LUT4_table_data[2] = 45'h000028140603;
  assign LUT4_table_data[3] = 45'h000068140603;
  assign LUT4_table_data[4] = 45'h000068540613;
  assign LUT4_table_data[5] = 45'h000168544633;
  assign LUT4_table_data[6] = 45'h000168544633;
  assign LUT4_table_data[7] = 45'h00056A554633;
  assign LUT4_table_data[8] = 45'h000000000000;
  assign LUT4_table_data[9] = 45'h003000000003;
  assign LUT4_table_data[10] = 45'h009030000009;
  assign LUT4_table_data[11] = 45'h009090001809;
  assign LUT4_table_data[12] = 45'h009090604809;
  assign LUT4_table_data[13] = 45'h009090604809;
  assign LUT4_table_data[14] = 45'h069391E10869;
  assign LUT4_table_data[15] = 45'h129394E10929;
  assign LUT4_table_data[16] = 45'h003008080803;
  assign LUT4_table_data[17] = 45'h0080301C1208;
  assign LUT4_table_data[18] = 45'h008080441212;
  assign LUT4_table_data[19] = 45'h008080943A12;
  assign LUT4_table_data[20] = 45'h030080948A12;
  assign LUT4_table_data[21] = 45'h030080948A12;
  assign LUT4_table_data[22] = 45'h0D0583148AB2;
  assign LUT4_table_data[23] = 45'h0D0583148AB2;
  assign LUT4_table_data[24] = 45'h002008140200;
  assign LUT4_table_data[25] = 45'h002040301000;
  assign LUT4_table_data[26] = 45'h0020B0302C00;
  assign LUT4_table_data[27] = 45'h0020B0A02C00;
  assign LUT4_table_data[28] = 45'h0020B1802C00;
  assign LUT4_table_data[29] = 45'h072431802C00;
  assign LUT4_table_data[30] = 45'h072431802C00;
  assign LUT4_table_data[31] = 45'h072431802C00;
  assign LUT4_table_data[32] = 45'h000000080000;
  assign LUT4_table_data[33] = 45'h009000081200;
  assign LUT4_table_data[34] = 45'h009000083600;
  assign LUT4_table_data[35] = 45'h02D000083600;
  assign LUT4_table_data[36] = 45'h07500008C600;
  assign LUT4_table_data[37] = 45'h07500009E600;
  assign LUT4_table_data[38] = 45'h07500009E600;
  assign LUT4_table_data[39] = 45'h07500009E600;
  assign LUT4_table_data[40] = 45'h0080480C0602;
  assign LUT4_table_data[41] = 45'h0080480C060D;
  assign LUT4_table_data[42] = 45'h0080480C0623;
  assign LUT4_table_data[43] = 45'h0081A8BC0623;
  assign LUT4_table_data[44] = 45'h0601AA1C0623;
  assign LUT4_table_data[45] = 45'h1101AA1C0623;
  assign LUT4_table_data[46] = 45'h1101AA1C0623;
  assign LUT4_table_data[47] = 45'h1101AA1C0623;
  assign LUT4_table_data[48] = 45'h006040300E08;
  assign LUT4_table_data[49] = 45'h0060A8300E15;
  assign LUT4_table_data[50] = 45'h020178300E15;
  assign LUT4_table_data[51] = 45'h054318307649;
  assign LUT4_table_data[52] = 45'h0BC3183146B1;
  assign LUT4_table_data[53] = 45'h0BC3183146B1;
  assign LUT4_table_data[54] = 45'h0BC3183146B1;
  assign LUT4_table_data[55] = 45'h0BC3183146B1;
  assign LUT4_table_data[56] = 45'h007020000E0C;
  assign LUT4_table_data[57] = 45'h016098000E0C;
  assign LUT4_table_data[58] = 45'h034188780E2A;
  assign LUT4_table_data[59] = 45'h034188780E2A;
  assign LUT4_table_data[60] = 45'h03418878FE2A;
  assign LUT4_table_data[61] = 45'h03418878FE2A;
  assign LUT4_table_data[62] = 45'h03418878FE2A;
  assign LUT4_table_data[63] = 45'h03418878FE2A;
  assign LUT4_table_data[64] = 45'h000000000000;
  assign LUT4_table_data[65] = 45'h000000000000;
  assign LUT4_table_data[66] = 45'h000000000000;
  assign LUT4_table_data[67] = 45'h000000000000;
  assign LUT4_table_data[68] = 45'h000000000000;
  assign LUT4_table_data[69] = 45'h000000000000;
  assign LUT4_table_data[70] = 45'h000000000000;
  assign LUT4_table_data[71] = 45'h000000000000;
  assign LUT4_table_data[72] = 45'h000000000000;
  assign LUT4_table_data[73] = 45'h000000000000;
  assign LUT4_table_data[74] = 45'h000000000000;
  assign LUT4_table_data[75] = 45'h000000000000;
  assign LUT4_table_data[76] = 45'h000000000000;
  assign LUT4_table_data[77] = 45'h000000000000;
  assign LUT4_table_data[78] = 45'h000000000000;
  assign LUT4_table_data[79] = 45'h000000000000;
  assign LUT4_table_data[80] = 45'h000000000000;
  assign LUT4_table_data[81] = 45'h000000000000;
  assign LUT4_table_data[82] = 45'h000000000000;
  assign LUT4_table_data[83] = 45'h000000000000;
  assign LUT4_table_data[84] = 45'h000000000000;
  assign LUT4_table_data[85] = 45'h000000000000;
  assign LUT4_table_data[86] = 45'h000000000000;
  assign LUT4_table_data[87] = 45'h000000000000;
  assign LUT4_table_data[88] = 45'h000000000000;
  assign LUT4_table_data[89] = 45'h000000000000;
  assign LUT4_table_data[90] = 45'h000000000000;
  assign LUT4_table_data[91] = 45'h000000000000;
  assign LUT4_table_data[92] = 45'h000000000000;
  assign LUT4_table_data[93] = 45'h000000000000;
  assign LUT4_table_data[94] = 45'h000000000000;
  assign LUT4_table_data[95] = 45'h000000000000;
  assign LUT4_table_data[96] = 45'h000000000000;
  assign LUT4_table_data[97] = 45'h000000000000;
  assign LUT4_table_data[98] = 45'h000000000000;
  assign LUT4_table_data[99] = 45'h000000000000;
  assign LUT4_table_data[100] = 45'h000000000000;
  assign LUT4_table_data[101] = 45'h000000000000;
  assign LUT4_table_data[102] = 45'h000000000000;
  assign LUT4_table_data[103] = 45'h000000000000;
  assign LUT4_table_data[104] = 45'h000000000000;
  assign LUT4_table_data[105] = 45'h000000000000;
  assign LUT4_table_data[106] = 45'h000000000000;
  assign LUT4_table_data[107] = 45'h000000000000;
  assign LUT4_table_data[108] = 45'h000000000000;
  assign LUT4_table_data[109] = 45'h000000000000;
  assign LUT4_table_data[110] = 45'h000000000000;
  assign LUT4_table_data[111] = 45'h000000000000;
  assign LUT4_table_data[112] = 45'h000000000000;
  assign LUT4_table_data[113] = 45'h000000000000;
  assign LUT4_table_data[114] = 45'h000000000000;
  assign LUT4_table_data[115] = 45'h000000000000;
  assign LUT4_table_data[116] = 45'h000000000000;
  assign LUT4_table_data[117] = 45'h000000000000;
  assign LUT4_table_data[118] = 45'h000000000000;
  assign LUT4_table_data[119] = 45'h000000000000;
  assign LUT4_table_data[120] = 45'h000000000000;
  assign LUT4_table_data[121] = 45'h000000000000;
  assign LUT4_table_data[122] = 45'h000000000000;
  assign LUT4_table_data[123] = 45'h000000000000;
  assign LUT4_table_data[124] = 45'h000000000000;
  assign LUT4_table_data[125] = 45'h000000000000;
  assign LUT4_table_data[126] = 45'h000000000000;
  assign LUT4_table_data[127] = 45'h000000000000;
  assign vLUT4 = LUT4_table_data[fAddr];

  assign fShift_16_1 = vLUT4[8:0];

  assign fShift_15 = fShift_16_1;

  assign fShift_17_1 = vLUT4[17:9];

  assign fShift_16 = fShift_17_1;

  assign fShift_18_1 = vLUT4[26:18];

  assign fShift_17 = fShift_18_1;

  assign fShift_19_1 = vLUT4[35:27];

  assign fShift_18 = fShift_19_1;

  assign fShift_20_1 = vLUT4[44:36];

  assign fShift_19 = fShift_20_1;

  assign LUT5_table_data[0] = 18'b000000001000000001;
  assign LUT5_table_data[1] = 18'b000000011000000011;
  assign LUT5_table_data[2] = 18'b000000011000000011;
  assign LUT5_table_data[3] = 18'b000000011000000011;
  assign LUT5_table_data[4] = 18'b000010011000000011;
  assign LUT5_table_data[5] = 18'b000010011000000011;
  assign LUT5_table_data[6] = 18'b001010011000000011;
  assign LUT5_table_data[7] = 18'b011010011010000011;
  assign LUT5_table_data[8] = 18'b000000000000000000;
  assign LUT5_table_data[9] = 18'b000000011000000011;
  assign LUT5_table_data[10] = 18'b000001001000001001;
  assign LUT5_table_data[11] = 18'b000001001000010101;
  assign LUT5_table_data[12] = 18'b000001001000010101;
  assign LUT5_table_data[13] = 18'b000001001000010101;
  assign LUT5_table_data[14] = 18'b001101001000010101;
  assign LUT5_table_data[15] = 18'b001101001011010101;
  assign LUT5_table_data[16] = 18'b000000011000000011;
  assign LUT5_table_data[17] = 18'b000000011000000011;
  assign LUT5_table_data[18] = 18'b000001101000000011;
  assign LUT5_table_data[19] = 18'b000100001000000011;
  assign LUT5_table_data[20] = 18'b000100001000101011;
  assign LUT5_table_data[21] = 18'b000100001001111011;
  assign LUT5_table_data[22] = 18'b000100001100011011;
  assign LUT5_table_data[23] = 18'b000100001100011011;
  assign LUT5_table_data[24] = 18'b000000100000000001;
  assign LUT5_table_data[25] = 18'b000001011000001000;
  assign LUT5_table_data[26] = 18'b000011001000010110;
  assign LUT5_table_data[27] = 18'b000011001000110010;
  assign LUT5_table_data[28] = 18'b000011001000110010;
  assign LUT5_table_data[29] = 18'b010001001000110010;
  assign LUT5_table_data[30] = 18'b010001001000110010;
  assign LUT5_table_data[31] = 18'b010001001000110010;
  assign LUT5_table_data[32] = 18'b000000000000000000;
  assign LUT5_table_data[33] = 18'b000000000000001001;
  assign LUT5_table_data[34] = 18'b000010010000001001;
  assign LUT5_table_data[35] = 18'b000010010000001001;
  assign LUT5_table_data[36] = 18'b000010010000001001;
  assign LUT5_table_data[37] = 18'b000010010000001001;
  assign LUT5_table_data[38] = 18'b000010010000001001;
  assign LUT5_table_data[39] = 18'b000010010000001001;
  assign LUT5_table_data[40] = 18'b000000010000000000;
  assign LUT5_table_data[41] = 18'b000001101000001011;
  assign LUT5_table_data[42] = 18'b000001101000001011;
  assign LUT5_table_data[43] = 18'b000001101000110111;
  assign LUT5_table_data[44] = 18'b001100101010001111;
  assign LUT5_table_data[45] = 18'b001100101010001111;
  assign LUT5_table_data[46] = 18'b001100101010001111;
  assign LUT5_table_data[47] = 18'b001100101010001111;
  assign LUT5_table_data[48] = 18'b000000001000000011;
  assign LUT5_table_data[49] = 18'b000001110000010000;
  assign LUT5_table_data[50] = 18'b000101000000101010;
  assign LUT5_table_data[51] = 18'b001011100000101010;
  assign LUT5_table_data[52] = 18'b001011100000101010;
  assign LUT5_table_data[53] = 18'b001011100000101010;
  assign LUT5_table_data[54] = 18'b001011100000101010;
  assign LUT5_table_data[55] = 18'b001011100000101010;
  assign LUT5_table_data[56] = 18'b000000101000000101;
  assign LUT5_table_data[57] = 18'b000000101000000101;
  assign LUT5_table_data[58] = 18'b000000101000000101;
  assign LUT5_table_data[59] = 18'b001000001001000001;
  assign LUT5_table_data[60] = 18'b001000001001000001;
  assign LUT5_table_data[61] = 18'b001000001001000001;
  assign LUT5_table_data[62] = 18'b001000001001000001;
  assign LUT5_table_data[63] = 18'b001000001001000001;
  assign LUT5_table_data[64] = 18'b000000000000000000;
  assign LUT5_table_data[65] = 18'b000000000000000000;
  assign LUT5_table_data[66] = 18'b000000000000000000;
  assign LUT5_table_data[67] = 18'b000000000000000000;
  assign LUT5_table_data[68] = 18'b000000000000000000;
  assign LUT5_table_data[69] = 18'b000000000000000000;
  assign LUT5_table_data[70] = 18'b000000000000000000;
  assign LUT5_table_data[71] = 18'b000000000000000000;
  assign LUT5_table_data[72] = 18'b000000000000000000;
  assign LUT5_table_data[73] = 18'b000000000000000000;
  assign LUT5_table_data[74] = 18'b000000000000000000;
  assign LUT5_table_data[75] = 18'b000000000000000000;
  assign LUT5_table_data[76] = 18'b000000000000000000;
  assign LUT5_table_data[77] = 18'b000000000000000000;
  assign LUT5_table_data[78] = 18'b000000000000000000;
  assign LUT5_table_data[79] = 18'b000000000000000000;
  assign LUT5_table_data[80] = 18'b000000000000000000;
  assign LUT5_table_data[81] = 18'b000000000000000000;
  assign LUT5_table_data[82] = 18'b000000000000000000;
  assign LUT5_table_data[83] = 18'b000000000000000000;
  assign LUT5_table_data[84] = 18'b000000000000000000;
  assign LUT5_table_data[85] = 18'b000000000000000000;
  assign LUT5_table_data[86] = 18'b000000000000000000;
  assign LUT5_table_data[87] = 18'b000000000000000000;
  assign LUT5_table_data[88] = 18'b000000000000000000;
  assign LUT5_table_data[89] = 18'b000000000000000000;
  assign LUT5_table_data[90] = 18'b000000000000000000;
  assign LUT5_table_data[91] = 18'b000000000000000000;
  assign LUT5_table_data[92] = 18'b000000000000000000;
  assign LUT5_table_data[93] = 18'b000000000000000000;
  assign LUT5_table_data[94] = 18'b000000000000000000;
  assign LUT5_table_data[95] = 18'b000000000000000000;
  assign LUT5_table_data[96] = 18'b000000000000000000;
  assign LUT5_table_data[97] = 18'b000000000000000000;
  assign LUT5_table_data[98] = 18'b000000000000000000;
  assign LUT5_table_data[99] = 18'b000000000000000000;
  assign LUT5_table_data[100] = 18'b000000000000000000;
  assign LUT5_table_data[101] = 18'b000000000000000000;
  assign LUT5_table_data[102] = 18'b000000000000000000;
  assign LUT5_table_data[103] = 18'b000000000000000000;
  assign LUT5_table_data[104] = 18'b000000000000000000;
  assign LUT5_table_data[105] = 18'b000000000000000000;
  assign LUT5_table_data[106] = 18'b000000000000000000;
  assign LUT5_table_data[107] = 18'b000000000000000000;
  assign LUT5_table_data[108] = 18'b000000000000000000;
  assign LUT5_table_data[109] = 18'b000000000000000000;
  assign LUT5_table_data[110] = 18'b000000000000000000;
  assign LUT5_table_data[111] = 18'b000000000000000000;
  assign LUT5_table_data[112] = 18'b000000000000000000;
  assign LUT5_table_data[113] = 18'b000000000000000000;
  assign LUT5_table_data[114] = 18'b000000000000000000;
  assign LUT5_table_data[115] = 18'b000000000000000000;
  assign LUT5_table_data[116] = 18'b000000000000000000;
  assign LUT5_table_data[117] = 18'b000000000000000000;
  assign LUT5_table_data[118] = 18'b000000000000000000;
  assign LUT5_table_data[119] = 18'b000000000000000000;
  assign LUT5_table_data[120] = 18'b000000000000000000;
  assign LUT5_table_data[121] = 18'b000000000000000000;
  assign LUT5_table_data[122] = 18'b000000000000000000;
  assign LUT5_table_data[123] = 18'b000000000000000000;
  assign LUT5_table_data[124] = 18'b000000000000000000;
  assign LUT5_table_data[125] = 18'b000000000000000000;
  assign LUT5_table_data[126] = 18'b000000000000000000;
  assign LUT5_table_data[127] = 18'b000000000000000000;
  assign vLUT5 = LUT5_table_data[fAddr];

  assign fShift_21_1 = vLUT5[8:0];

  assign fShift_20 = fShift_21_1;

  assign fShift_22 = vLUT5[17:9];

  assign fShift_21 = fShift_22;

endmodule  // dec_FinalShifts

